### ISSUE TITLE
Feature: Code Action when elm provides close enough names

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#100]
If there is a naming error, `elm make` provides names that are close. They can be used to add code actions to automatically fix the error.

### Downside
This would really on string parsing the compiler message. Not sure how things will be with an elm update changing the messages and backward compability.

### Example error message

```shell
[Elm] [E] NAMING ERROR - I cannot find a `MultipleChoice.view1` variable:

72|                     MultipleChoice.view1
                        ^^^^^^^^^^^^^^^^^^^^
The `MultipleChoice` module does not expose a `view1` variable. These names seem
close though:

    MultipleChoice.view
    multipleChoiceMessage
    AgePicker.view
    Statement.view

Hint: Read <https://elm-lang.org/0.19.0/imports> to see how `import`
declarations work in Elm.
```

**Comment by Razzeee** [comment]
Should work now with https://github.com/elm-tooling/elm-language-server/commit/c35e52ee6c2d3695349d15fdb7529aef4b465f0c

Let's see when it breaks. We will need to align it if we can ever get rid of the `#` in our messages.
