### ISSUE TITLE
Uses 100% cpu and seems to hang

### ISSUE THREAD

**Issue by tj** [elm-tooling/elm-language-server#101]
This only seems to happen with certain files, I'll try to figure out how to reproduce it but I'm running into scenarios where it just gets stuck using 100% cpu, and I have to manually kill it.

**Comment by tj** [comment]
nevermind I'm an idiot, I was missing the `module` declaration, I'll re-open if it happens anywhere else

**Comment by Razzeee** [comment]
I'm actually already trying to find it. It should not happen under any circumstance.

Here's another file that has this behavior as soon as you change something in the file https://github.com/harrysarson/welsh-whacker/blob/master/src/Design/Icons.elm

**Comment by Razzeee** [comment]
cutting down the generated symbols seems to fix this https://github.com/elm-tooling/elm-language-server/commit/82bc065c47f5aa893b47cc7cf88129356d42c658

Seems to happen when https://github.com/elm-tooling/elm-language-server/blob/master/src/providers/documentSymbolProvider.ts tries to pass too many items.
