### ISSUE TITLE
[Bug] Renaming will remove constructors from export and imports

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#102]
#### TLDR

Export `(..)` of a custom type will be dropped accidentally be using the rename action.

#### Reproduce the issue

Starting with this file

```elm
module Main exposing (Exported(..))

type Exported
    = Exported
```

Renaming the type `Exported` to `ExportedRenamed` will lead to this:

```elm
module Main exposing (ExportedRenamed)

type ExportedRenamed
    = Exported
```

Also imports will drop `(..)`. The constructors aren't exposed anymore. Code is not compiling anymore.

**Comment by Razzeee** [comment]
Fixed by https://github.com/elm-tooling/elm-language-server/commit/d3fceb53b8adeb56045f27439d8ac4383903a6db
