### ISSUE TITLE
[Feature] Add missing imports as fix

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#105]
Whenever there is a `Naming Error`:

```
[Elm] [E] NAMING ERROR - I cannot find a `Color` type:

13|     { white : Color
                  #^^^^^#
These names seem close though:

    #Bool#
    #Char#
    #Cmd#
    #Float#

#Hint#: Read <https://elm-lang.org/0.19.0/imports> to see how `import`
declarations work in Elm.
```

It can be a typo, but it's also possible something wasn't imported. The language server could match (in this case) `Color` against what is known in source files and dependencies.

If there is a hit, it could be suggested as a fix.

If the fix is applied, it can add a new line `import Module exposing (Color)` as second line and trigger `elm-format` which will do the merging of imports.

In my opinion this is one of the missing killer features :)

**Comment by Razzeee** [comment]
I was thinking about another (but probably harder option).
We can find every type or function via tree-sitter and see if we can resolve it correctly. Then underline every occurrence of the ones we could not resolve.
Adding a fix for these should be simple then.

Pro:
- Instant feedback on typing
- No external dependency

Contra:
- Might be harder on cpu and therefor battery
