### ISSUE TITLE
Atom support

### ISSUE THREAD

**Issue by razzeee** [elm-tooling/elm-language-server#106]
It would be awesome if someone could look at atom and how to get the language server to work with it.

**Comment by andys8** [comment]
I looked into it once and I think the haskell ide plugin would be a nice starting point. It's a only a few lines of code. Would be great if somebody would start the plugin who is using the Atom editor and can verify everything is working fine.

Repository: https://github.com/Tehnix/ide-haskell-hie
Implementation: https://github.com/Tehnix/ide-haskell-hie/blob/master/lib/ide-haskell-hie.js

**Comment by Razzeee** [comment]
I prepared this https://github.com/elm-tooling/ide-elm
It's working partially, paths seem wrong in diagnostics, can't figure out why.

**Comment by icidasset** [comment]
@razzeee I've updated the dependencies of your package https://github.com/elm-tooling/ide-elm locally here to all the latest versions, and it seems to work?

<img width="451" alt="Screenshot 2021-11-18 at 15 50 50" src="https://user-images.githubusercontent.com/296665/142438990-a41c5fbf-3304-4398-9da0-f2133e86de99.png">

Linter warnings and the like are showing up as well.
I don't have any symbols yet though, not sure how that is usually provided.

<img width="709" alt="Screenshot 2021-11-18 at 15 59 01" src="https://user-images.githubusercontent.com/296665/142439920-3b837de2-cdc6-4d44-bbbf-1d052d38de79.png">

Which paths exactly did you have trouble with?

**Comment by razzeee** [comment]
> Which paths exactly did you have trouble with?

From reading back I would think the paths in diagnostics, so probably a panel, where you get all your errors/warnings. Or inline warnings?

**Comment by razzeee** [comment]
Can you upstream this, if it works for you?

**Comment by icidasset** [comment]
> Can you upstream this, if it works for you?

Sure thing: https://github.com/elm-tooling/ide-elm/pull/1
