### ISSUE TITLE
Feature: Code Action when elm provides close enough typo fix

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#108]
`TYPE MISMATCH` provides this line: "So maybe #denim# should be #denimBlue#?"
It could be used as proposal for a code fix.

```
[Elm] [E] TYPE MISMATCH - This `colors` record does not have a `denim` field:

204|                     { label = el [ Font.bold, Font.color colors.denim ] <| text "MyText"
                                                                     #^^^^^#
This is usually a typo. Here are the `colors` fields that are most similar:

    { denimBlue : Color
    , alto : Color
    , black : Color
    , gray : Color
    , ...
    }


So maybe #denim# should be #denimBlue#?
```

Related to #100

**Comment by Razzeee** [comment]
Same should be done with module name mismatch

https://elmlang.slack.com/files/U1FCZNA7R/FLFFCRBJT/screenshot_from_2019-07-13_10-33-00.png

**Comment by Razzeee** [comment]
Landed the later one with https://github.com/elm-tooling/elm-language-server/pull/110

We should probably scan the elm errors for more errors of this type

**Comment by Razzeee** [comment]
Added more of these, in fact for all I could find via the github search in the compiler repo.
https://github.com/elm-tooling/elm-language-server/commit/7abad16db4a379ce46b5e974b059879109aa7a4e
