### ISSUE TITLE
Feature: Insert some punctuation and operators on newline

### ISSUE THREAD

**Issue by tj** [elm-tooling/elm-language-server#109]
It might be too fancy but I thought it might be nice to have an option which inserts `,`, `|>` and possibly others when you enter a new line

**Comment by Razzeee** [comment]
Would be awesome, the problem is, how would we know that a user wants that in that moment. We also would need to figure out the correct indentation.

**Comment by tj** [comment]
Hmm yeah maybe it wouldn't work so well in practice haha. In a few scenarios I think it'd be ok, since it's syntactically required (module exports, record commas), but for pipes yeah maybe not, I'll give that some more thought!

**Comment by Razzeee** [comment]
As I see no way to implement this and nobody seems to work on this, I'm going to close this for now.
