### ISSUE TITLE
documentSymbolProvider & workspaceSymbolProvider

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#11]
These are basically done from my POV, but i really want feedback on the symbols we're recognizing and how we are mapping them.

This is how we map them currently.

This is a list of SymbolKind we're using:
- File (for whole files)
- Function (for functions)
- Module (for a module)
- Operator (for every operator like `+` or `|>`)
- Enum (For custom types)
- EnumMember (for every member of a custom type)
- *Struct* (for a type alias)
- Number (for numbers)
- String (for strings)

These are also available in the languague server spec:
- Namespace
- Package (not sure these should map to imports?)
- Class
- Method
- Property
- Field (might be better for a type alias?)
- Constructor
- Interface
- Variable
- Constant
- Boolean (should be possible have to check)
- Array (could also be added and mapped to lists)
- Object
- Key
- Null
- Event
- TypeParameter (not sure what this is supposed to be)

I would really like feedback here.

**Comment by pehota** [comment]
@Razzeee ,
The mapping does make sense to me. 
I didn't really get your comment regarding the `Boolean`s since it seems as a straightforward mapping.
I understand `TypeParameter` as a `type variable` (a `generic` if you will).

**Comment by Razzeee** [comment]
I've added lists and boolean for now.

Field seems to be uninteresting, at least judging from the icon.

**Comment by bengolds** [comment]
Having solid autocomplete on type variables would be worthwhile -- would make code more readable to have longer names in type variables as opposed to `a` `b` `c`.

`Constant` would be valuable, but it's not obvious to me how to detect if something _is_ a constant. If you check that it has no parameters, that doesn't distinguish from partially applied functions.
```elm
-- name should be detected as a constant.
name = "Bob"

-- double should not be treated as a constant.
double = (*) 2
``` 

If you check its type signature, type aliases can screw with that:
```elm
-- double is obviously a function!
double : Int -> Int
double = (*) 2

type alias NumberFunc = Int -> Int

-- Less obvious that double is a constant without expanding the type aliases.
double: NumberFunc
double = (*) 2
``` 
If this has enough compiler access or the ability to expand type aliases, then this would be easier and worthwhile.

Lastly, I'm not entirely sure where record fields are in your current mapping. Are they `TypeMembers`? Or `Fields`?

**Comment by Razzeee** [comment]
Autocomplete is not part of this issue.

I feel like elm has no constants, thats just a function. Might be very confusing for people otherwise.

Well record or type alias would be a struct. But your asking for the items that make this up? No mapped yet. `Field` might work in that context. Not sure what `TypeMembers` is referencing.
