### ISSUE TITLE
Readme: Configuring elm-analyse

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#112]
The readme could contain some lines / links about using elm-analyse and it's configuration.

* There is optional configuration
* The file is called `elm-analyse.json`
* It has to be next to `elm.json` in each project
* All existing rules are enabled by default
* The rules names can be looked up and disabled

https://stil4m.github.io/elm-analyse/#/configuration

https://stil4m.github.io/elm-analyse/#/messages

**Comment by jinjor** [comment]
I located `elm-analyse.json` next to `elm.json` but warnings continue showing.
What am I missing?

```json
{
  "checks": {
    "ImportAll": false,
    "SingleFieldRecord": false,
    "UnusedVariable": false,
    "TriggerWords": []
  }
}

```

**Comment by andys8** [comment]
@jinjor Tested it with vscode (current version, current extension), and it works as expected for me.
Can you provide more information in a new issue or in slack? Are both files in git root, or is the project structure more complex?

**Comment by jinjor** [comment]
Thanks, I opened #123

**Comment by andys8** [comment]
@razzeee The readme changes are enough to close the issue for me. If you think more information makes sense, leave the issue open. Otherwise it can be closed :)
