### ISSUE TITLE
High CPU Usage when parsing fails?

### ISSUE THREAD

**Issue by antew** [elm-tooling/elm-language-server#114]
This was reported on Slack and I think I found one way to reproduce it reliably, if anyone else can try it out it would be good to have confirmation!

### Steps to Reproduce
1. `git clone https://github.com/rtfeldman/elm-spa-example`
2. Open the project in an editor with the language server enabled.
3. Open `src/Main.elm`
4. Give it a second for the warnings to show up
5. Delete from line 1 to line 35 (this block below)
```
module Main exposing (main)

import Api exposing (Cred)
import Article.Slug exposing (Slug)
import Avatar exposing (Avatar)
import Browser exposing (Document)
import Browser.Navigation as Nav
import Html exposing (..)
import Json.Decode as Decode exposing (Value)
import Page exposing (Page)
import Page.Article as Article
import Page.Article.Editor as Editor
import Page.Blank as Blank
import Page.Home as Home
import Page.Login as Login
import Page.NotFound as NotFound
import Page.Profile as Profile
import Page.Register as Register
import Page.Settings as Settings
import Route exposing (Route)
import Session exposing (Session)
import Task
import Time
import Url exposing (Url)
import Username exposing (Username)
import Viewer exposing (Viewer)



-- NOTE: Based on discussions around how asset management features
-- like code splitting and lazy loading have been shaping up, it's possible
-- that most of this file may become unnecessary in a future release of Elm.
-- Avoid putting things in this module unless there is no alternative!
-- See https://discourse.elm-lang.org/t/elm-spa-in-0-19/1800/2 for more.
```
5. CPU usage will spike to 99% and stay there, even if you undo the changes, it seems like you have to kill and restart the language server.

From taking a profile while this is happening it looks like this is the callstack, it gets stuck somewhere in trying to find a function.
![image](https://user-images.githubusercontent.com/1693421/61593172-1664b700-abaa-11e9-8488-5a3a7e3eedf2.png)

**Comment by Razzeee** [comment]
I can't seem to really get the parser stuck, running a copy of that file. Copied to https://github.com/Razzeee/tree-sitter-elm/blob/master/examples/test.elm and running https://github.com/Razzeee/tree-sitter-elm/blob/master/package.json#L26

But I found the two errors I mentioned here. (one is inside a comment)
Not sure they are connected at all.
https://github.com/tree-sitter/tree-sitter/issues/394

**Comment by Razzeee** [comment]
It doesn't seem to matter what I change, even if I remove just the comment it happens. 

Even if I remove some type constructor or a type annotation

**Comment by andys8** [comment]
Is it reasonable to consider a hotfix that'll timeout `findfunction`, cancel and recover? Would it even be possible?

**Comment by Razzeee** [comment]
While I'm able to get the 100% cpu useage, I can't get a callstack that's similar or point's at `findFunction`. It even keeps happening, when I empty out `findFunction`.

Seems like we might need to revert to the old way of supplying tree-sitter.

**Comment by Razzeee** [comment]
Not sure it really is `findFunction`, it seems to start for me when we pass https://github.com/elm-tooling/elm-language-server/blob/master/src/forest.ts#L81
Or does not happen at all, when I comment it out. Still, I have no idea how that could trigger it.

The new tree should already be parsed at that point, so in theory it can't be the wasm update/the parser.

**Comment by Razzeee** [comment]
https://github.com/tree-sitter/tree-sitter/issues/404

**Comment by Razzeee** [comment]
If you can, please test with master. I will very likely prepare a release very soon.

**Comment by antew** [comment]
Tested on latest master and the issue no longer happens for me :-)

**Comment by andys8** [comment]
Wow, that's great news. Will try it.

**Comment by ymtszw** [comment]
Re-enabled for a whole work way, and it works smooth! (VSCode 1.36.1)
Deeply appreciated ❤️
