### ISSUE TITLE
neovim with nvim-cmp completions not working

### ISSUE THREAD

**Issue by KunaPrime** [elm-tooling/elm-language-server#1163]
using neovim and https://github.com/hrsh7th/nvim-cmp server is started found and attached but there is no auto completion
suggestions for and files in elm project 
 
## Expected Behavior
completion suggestions should be usable and found 

## Current Behavior
no completion suggestions 

## Your Environment

elm-language-server: 2.5.2
node: v20.10.0
nvim:  v0.10.0-dev+1974-g714b07519

**Comment by razzeee** [comment]
you'll need to post logs

**Comment by KunaPrime** [comment]
i was able to find this via `LspLog`: 

```
[START][2024-02-01 17:39:10] LSP logging initiated
[ERROR][2024-02-01 17:39:10] ...lsp/handlers.lua:562	"Unhandled Rejection at: Promise [object Promise] reason:, TypeError: Failed to parse URL from /usr/local/lib/node_modules/@elm-tooling/elm-language-server/node_modules/web-tree-sitter/tree-sitter.wasm"
```

**Comment by KunaPrime** [comment]
if there are other logs that i can look for please direct me where to look. 
Thank you

**Comment by KunaPrime** [comment]
@hingew that's the solution. Thanks!!
