### ISSUE TITLE
Document setup with LanguageClient-neovim

### ISSUE THREAD

**Issue by lpil** [elm-tooling/elm-language-server#119]
It'd be great to have documentation on usage with https://github.com/autozimu/LanguageClient-neovim

I tried this configuration but received an error

```viml
let g:LanguageClient_serverCommands = {
      \ 'elm': ['elm-language-server', '--stdio'],
      \ }
```

![Screenshot 2019-07-28 at 13 40 04](https://user-images.githubusercontent.com/6134406/62006778-3877af80-b13d-11e9-9bf0-3e4a3b240fec.png)

**Comment by Razzeee** [comment]
Against which version of the server did you try?

**Comment by lpil** [comment]
Version 1.2.1, thank you

**Comment by andys8** [comment]
Hmm, the documentation doesn't give a lot of details in the example. https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md#5-configure-this-plugin

I would try it with `elm-language-server` 1.1.1, but that's a guess. The configuration doesn't set paths for the necessary binaries (`elm-format`) and others. So it could be that those need to be set (but there should be defaults). It could be that a binary is missing in the path. But with this error, no existing example configuration and no useful error message, it's hard to tell.

Would be nice if the result of this issue would be a working configuration and some tipps for other users.

**Comment by lpil** [comment]
I have elm and elm-format on my path, that should be enough?

Here's an example config for some other language servers

```viml
let g:LanguageClient_serverCommands = {
      \ 'rust': ['rustup', 'run', 'stable', 'rls'],
      \ 'python': ['pyls'],
      \ 'go': ['gopls']
      \ }
```

**Comment by andys8** [comment]
Documentation says `elm-test`, too. Not sure what happens when you don't have tests.

Today was a new version released: 1.2.2

**Comment by Razzeee** [comment]
Does this work for you now?

**Comment by lpil** [comment]
After updating elm-language-server I no longer get an error at start but when I attempt to do something like look up a type definition I get an error message `[LC] sending on a disconnected channel`.

**Comment by Razzeee** [comment]
Any more logs?

**Comment by lpil** [comment]
Here's the logs from me starting nvim, opening an elm file in an elm project and attempting to look up a type definition

```
#######
LanguageClient 0.1.146 ec4af74cc389f802c3c43a660c963049848a8a93
#######
19:30:39 WARN unnamed src/language_server_protocol.rs:892 Failed to get initializationOptions: Failed to read file (/Users/louis.pilfordnationwide.co.uk/src/lpil/waive/assets/.vim/settings.json): No such file or directory (os error 2)
19:30:39 WARN unnamed src/language_server_protocol.rs:2834 Failed to get workspace settings: Failed to read file (/Users/louis.pilfordnationwide.co.uk/src/lpil/waive/assets/.vim/settings.json): No such file or directory (os error 2)
19:30:39 ERROR unnamed src/rpchandler.rs:13 Error handling message: Message not handled: MethodCall { jsonrpc: Some(V2), method: "workspace/configuration", params: Map({"items": Array([Object({"section": String("elmLS")})])}), id: Num(0) }

Message: {"jsonrpc":"2.0","method":"workspace/configuration","params":{"items":[{"section":"elmLS"}]},"id":0}

Error: ErrorMessage { msg: "Message not handled: MethodCall { jsonrpc: Some(V2), method: \"workspace/configuration\", params: Map({\"items\": Array([Object({\"section\": String(\"elmLS\")})])}), id: Num(0) }" }
19:30:39 ERROR reader-Some("elm") src/rpcclient.rs:35 Thread reader-Some("elm") exited with error: Custom { kind: UnexpectedEof, error: StringError("failed to fill whole buffer") }
19:30:44 ERROR unnamed src/rpchandler.rs:13 Error handling message: sending on a disconnected channel

Message: {"jsonrpc":"2.0","method":"languageClient/findLocations","params":{"bufnr":1,"filename":"/Users/louis.pilfordnationwide.co.uk/src/lpil/waive/assets/src/Html/Form.elm","gotoCmd":null,"handle":true,"languageId":"elm","method":"textDocument/typeDefinition","position":{"character":4,"line":82}},"id":1}

Error: "SendError(..)"
19:30:45 ERROR writer-Some("elm") src/rpcclient.rs:46 Thread writer-Some("elm") exited with error: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }
/tmp/LanguageClient-neovim.log (END)
```

**Comment by Razzeee** [comment]
For starters, it seems like that doesn't implement "workspace/configuration". https://github.com/autozimu/LanguageClient-neovim/issues/177

**Comment by Razzeee** [comment]
Can you test against https://github.com/elm-tooling/elm-language-server/pull/156

You probably need to https://github.com/elm-tooling/elm-language-server#alternative-compile-and-install-from-source with that branch

**Comment by lpil** [comment]
That works, thank you :)

**Comment by Razzeee** [comment]
That's great, can you document how to handle this client? Would be neat if you could amend the readme :)

**Comment by lpil** [comment]
Will do!
