### ISSUE TITLE
[SublimeText - LSP integration] elm-language-server fails to find elm.json if elm app is in child folder

### ISSUE THREAD

**Issue by pdamoc** [elm-tooling/elm-language-server#121]
Steps to reproduce: 

1. create a folder `foo` and inside it create a folder named `frontend`. 
2. inside `frontend` initialize an elm app and create a `src/Main.elm` 
3. open `foo` in sublime and then select `foo/frontend/src/Main.elm` from the sidebar

you should see an error in Sublime's console like 

```
elm: Error: Cannot find module '/path/to/foo/elm.json'
```

Environment: OSX 10.14.5, node 10.13.0 installed with `asdf` 

as a temporary bypass for this bug, if the `frontend` folder is added to the sidebar (drag and drop) and is arranged to be the top (first) folder of the project, this error stops.

**Comment by Razzeee** [comment]
Interesting, coc and kakoune configs have the concept of rootPatterns or roots, that let's the client detect and accordingly start the server.

**Comment by Razzeee** [comment]
To make this a bit more transparent to anyone not familiar with the language server spec, here's what the docs say

>Server lifetime
>The current protocol specification defines that the lifetime of a server is managed by the client (e.g. a tool like VS Code or Emacs). It is up to the client to decide when to start (process-wise) and when to shutdown a server.

https://microsoft.github.io/language-server-protocol/specification#initialize

So I'm trying to say, that we need to address this in the client.

**Comment by Razzeee** [comment]
So as it turns out, we will probably need to implement searching for elm.json on the server side (too)

**Comment by Razzeee** [comment]
I changed the server to enable this. It's only in master right now.

**Comment by Razzeee** [comment]
I've released a new version of the server, it should work fine. I'm closing this, but feel free to reopen or send a new issue. Thank you!
