### ISSUE TITLE
Wrong file URI gets returned by elm-make

### ISSUE THREAD

**Issue by bengolds** [elm-tooling/elm-language-server#124]
I'm not sure how I ended up in this state, but right now the extension is showing an error in a file with an extra `/` in it. VSCode won't open that file because of the extra slash. I think this is also causing the error to not get cleared; the error has been fixed and the project is building just fine.

<img width="505" alt="wrong-uri" src="https://user-images.githubusercontent.com/446007/62745534-33014b80-ba00-11e9-9e54-460e970db2aa.png">

## Steps to Reproduce (for bugs)
I will keep my eye on this to get a consistent repro.

## Your Environment
* Version used: 0.4.2
* Editor used: VSCode
* Operating System and version: MacOS 10.14.5

**Comment by Razzeee** [comment]
Is it just a `/` too many or is there also something missing?

**Comment by bengolds** [comment]
To my eyes, that's the only thing missing.

**Comment by Razzeee** [comment]
You mean to many, not missing :)

**Comment by Razzeee** [comment]
Did you end up there again or was this a one time only thing?

**Comment by bengolds** [comment]
Haha, good catch!

I've been on vacation for the last few weeks. I'll keep my eye out for it on 0.6.

**Comment by Razzeee** [comment]
I'll close this for now, feel free to reopen.
