### ISSUE TITLE
crypto deprecation warning

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#130]
There is a deprecation warning in the messages. Not that important. Node 11.11.0

https://github.com/elm-tooling/elm-language-server/blob/2aacf7e448fda9c597cd3ab085739b541452ee47/src/providers/diagnostics/elmMakeDiagnostics.ts#L2

https://github.com/nodejs/node/issues/23203#issuecomment-491963401

**Comment by Razzeee** [comment]
https://github.com/elm-tooling/elm-language-server/commit/039318ee619130b1959af014869cffe8b9912a02
