### ISSUE TITLE
Support multiple elm versions

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#132]
With upcoming 0.19.1 release and the current ability to configure the path for elm in a global manner, it might be hard to use `elm-language-server` with two projects in different versions.

## Solutions

* Automatically search for `./node_modules/.bin/elm` in each directory as a default
* Let the users configure a path* for each elm version* in their configuration and pick by version
* Install all elm versions automatically with the language-server and choose depending on `elm.json`
* Extend README with section how to configure `elm-language-server` on a project basis different editors

**Comment by andys8** [comment]
Hmm, the more I think about it: Maybe a user setting `"elmPath": "./node_modules/.bin/elm"` is enough. 

Having a fallback to use `elm` (global) if the path doesn't succeed would be nice.

**Comment by Razzeee** [comment]
Well having a fallback might potentially hide what's happening? But might not be a problem as a mismatch in `elm.json` would cause the compiler to fail.

**Comment by Razzeee** [comment]
Do you think this is okay to be closed now?

**Comment by andys8** [comment]
Yeah, with the upcoming work that you've done it should be much easier to have multi version projects. We can test it with the upcoming release candidate, once it's published. Let's close the issue for now.
