### ISSUE TITLE
globby import looks weird

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#150]
https://github.com/elm-tooling/elm-language-server/blob/25c8da33a257c33e10ebe727213e37e1fda9dd80/src/elmWorkspace.ts#L27

It's valid syntax and if it's intended that way, and also the order is necessary (I hope it's not), then the linting has to be disabled with `// tslint:disable-next-line:ordered-imports`.

Otherwise sort imports to make linter happy.

**Comment by Razzeee** [comment]
Should look better with https://github.com/elm-tooling/elm-language-server/commit/a5aa59da3596c36abc7b0e44957f1ec1f9090896

The order is not needed for the program, but nice for us as maintainers.
