### ISSUE TITLE
Wrong import in test doesn't show up and breaks diagnostic

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#158]
## Expected Behavior
Marks wrong import as diagnostic

## Current Behavior
* diagnostics not working
* wrong import not underlined

![image](https://user-images.githubusercontent.com/13085980/65352119-1bfe6d80-dbea-11e9-94de-493ae0f2f15a.png)

## Possible Solution
No idea

## Steps to Reproduce (for bugs)
1. Open https://github.com/folkertdev/elm-flate/blob/58585f0431d06f32294f5035d8bb354ad0e4d520/tests/TestDeflate.elm
2. Expect errors (`import Text` is wrong) or introduce new ones

## Context

`elm-test make` is complaining

```
elm-test make tests/TestDeflate.elm   --report json --output /dev/null

{"type":"error","path":"/tmp/elm-flate/tests/TestDeflate.elm","title":"UNKNOWN IMPORT","message":["The
TestDeflate module has a bad import:\n\n    ",{"bold":false,"underline":false,"color":"RED","string":"import Text"},"\n\nI cannot find that module! Is there a typo in the module name?\n\nThe \"source-directories\" field of your elm.json tells me to look in directories\nlike src, but it is not in any of them. Maybe it is in a package that is not\ninstalled yet?"]}
```

## Your Environment

* Version used: 1.4.1
* Editor used: Vim 8.1
* Environment name and version (e.g. node.js 5.4): node 11.11.0
* Operating System and version: Linux

**Comment by andys8** [comment]
```

**Comment by andys8** [comment]
The wrong path won't be the case for other files in the same directory (`tests/Example.elm`).

## Wanted error
```
[Trace - 9:54:51 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///tmp/elm-flate/tests/Example.elm",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 37,
                    "character": 4
                },
                "end": {
                    "line": 37,
                    "character": 23
                }
            },
            "message": "NAMING ERROR - I cannot find a `textCompressedBytes` variable:\n\n38|     textCompressedBytes\n        #^^^^^^^^^^^^^^^^^^^#\nThese names seem close though:\n\n    #textComp1ressedBytes#\n    #decompressed#\n    #Decode.bytes#\n    #Encode.bytes#\n\n#Hint#: Read <https://elm-lang.org/0.19.0/imports> to see how `import`\ndeclarations work in Elm.",
            "severity": 1,
            "source": "Elm"
        }
    ]
}
```

**Comment by Razzeee** [comment]
This fixes the URI https://github.com/elm-tooling/elm-language-server/commit/7ec09cc107d2a383535cf9a8206d71f891b740b0

But as elm-test does not recognize the line and position of the error, we can't highlight anything. 

Does this resolve everything?

**Comment by andys8** [comment]
Confirming the change solves the issue:

![image](https://user-images.githubusercontent.com/13085980/65372162-9d96df80-dc6c-11e9-8707-358ee74291b8.png)
