### ISSUE TITLE
ElmLS randomly crashes with Unexpected JSON error

### ISSUE THREAD

**Issue by jschomay** [elm-tooling/elm-language-server#161]
ElmLS runs just fine for a while, but after a couple minutes, something that I do will crash it with the following error:

```elm
SyntaxError: Unexpected number in JSON at position 1
    at JSON.parse (<anonymous>)
    at execaError.stderr.split.forEach (/usr/local/lib/node_modules/@elm-tooling/elm-language-server/out/providers/diagnostics/elmMakeDiagnostics.js:146:54)
    at Array.forEach (<anonymous>)
    at ElmMakeDiagnostics.<anonymous> (/usr/local/lib/node_modules/@elm-tooling/elm-language-server/out/providers/diagnostics/elmMakeDiagnostics.js:145:55)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/@elm-tooling/elm-language-server/out/providers/diagnostics/elmMakeDiagnostics.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)

/usr/local/lib/node_modules/@elm-tooling/elm-language-server/node_modules/web-tree-sitter/tree-sitter.js:1
(function (exports, require, module, __filename, __dirname) { var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.quit=function(e,t){throw t},Module.preRun=[],Module.postRun=[];var n,r=!1,a=!1,i=!1;r="object"==typeof window,a="function"==typeof importScripts,i="object"==typeof process&&"function"==typeof require&&!r&&!a,n=!r&&!i&&!a;var o,l,u="";i?(u=__dirname+"/",Module.read=function shell_read(e,t){var n;return o||(o=require("fs")),l||(l=require("path")),e=l.normalize(e),n=o.readFileSync(e),t?n:n.toString()},Module.readBinary=function readBinary(e){var t=Module.read(e,!0);return t.buffer||(t=new Uint8Array(t)),assert(t.buffer),t},process.arg
abort({}). Build with -s ASSERTIONS=1 for more info.
[Error  - 4:03:26 PM] Connection to server got closed. Server will not be restarted.
[Error  - 4:03:26 PM] elm-language-server exited with code: 7
```

I'm not certain what is triggering this, but it might be the diagnostics.

## Expected Behavior
Not to crash, or to restart if it crashes maybe?

## Current Behavior
Crashes and I have to do a `:CocRestart` to fire it up again every couple minutes.

## Possible Solution
Figure out what JSON is being returned, though I'm not sure how to do this.

## Steps to Reproduce (for bugs)
1.  Open a src/test file in https://github.com/jschomay/subway-game/tree/rules-parser in vim using coc (other files may work too)
2.  Notice the ElmLS works for a while
3.  Make some changes, or maybe just wait for a while or view a diagnostic
4.  Notice ElmLS has crashed and `:CocInfo` shows the error above.

## Context
I just want to use ElmLS with coc.

## Your Environment

* Version used: ElmLS 1.4.1, Elm elm@0.19.0-no-deps
* Editor used: vim 8.1
* Environment name and version (e.g. node.js 5.4): node v10.10.0
* Operating System and version: OSX 10.11.6

**Comment by Razzeee** [comment]
Yeah, elm 0.19.0 is able to return invalid json. I'm aware of that but hoped for 0.19.1 to be out soon, but as that might take some more time, I should probably look into keeping this from crashing.

**Comment by jschomay** [comment]
That's a bummer. Preventing crashes would at least make the tool still
useful overall, so I would appreciate that!

**Comment by Razzeee** [comment]
This hopefully helps with that https://github.com/elm-tooling/elm-language-server/commit/d6fe77cbc6661d1b1bd51fc98aba79c834d0b1e0

Are you able to test this, from master? I could not replicate the error on my end.

**Comment by jschomay** [comment]
Cool.  I tried to try it, but I seem to forget how to update to a branch.  I tried:

`npm update -g @elm-tooling/elm-language-server@master`, but it didn't seem to do anything.  I also tried that with `install` and it said "no matching version".  Can you remind me how to get `master`, and I'll give it a shot.

Thanks!

**Comment by andys8** [comment]
@jschomay I think it's not possible to install via npm (only). The repository has to be cloned, built and linked. There is a description how to to that here: https://github.com/elm-tooling/elm-language-server/blob/master/README.md#alternative-compile-and-install-from-source

**Comment by jschomay** [comment]
I tested it out and I think you've solved the problem (I am still getting the invalid JSON errors, but elmLS isn't crashing).

```
[Info  - 8:02:36 PM] Diagnostics were requested due to a file open or save
[Warn  - 8:02:37 PM] Received an invalid json, skipping error.
[Warn  - 8:02:37 PM] Received an invalid json, skipping error.
[Warn  - 8:02:37 PM] Received an invalid json, skipping error.
... lots of these messages, then more normal logs
[Info  - 8:02:38 PM] Received new elm-analyse report with 24 messages
etc...
```

Thank you for fixing that.  Hopefully the invalid JSON issue gets fixed eventually.
