### ISSUE TITLE
Long running time at 100% CPU

### ISSUE THREAD

**Issue by mpizenberg** [elm-tooling/elm-language-server#162]
Config: node 12.9.1 + elm 0.19 + neovim + coc + elm-language-server 1.4.1

The language server runs at 100% CPU for a long time (on the order of a minute) at every change saved in the file.

This behaviors occurs for me while editing `src/Main.elm` from https://github.com/billstclair/mammudeck. It is a 8299 loc file so it is possibly a performance issue but not necessarily.

**Comment by Razzeee** [comment]
This commit fixes the performance problem. https://github.com/elm-tooling/elm-language-server/commit/6bbc41b4a6dacd08144018c39abd53344e0ed7af

But I still have problems with the server restarting due to the elm-format integration failing.
