### ISSUE TITLE
Show user facing error for elm files without project or in wrong directory

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#167]
As a follow up of #163 I think it might be helpful, if the elm-language-server could provide user facing and helpful error messages for wrong setups, where

* there is an elm file but no project
* the elm files are not part of the directories specified in `elm.json` `source-directories`.

## Expected Behavior

Helpful error message or elm compiler error visible for user

## Current Behavior

I didn't have a look so far. This is currently based on #163, so assumptions could be wrong.

**Comment by Razzeee** [comment]
Closed by https://github.com/elm-tooling/elm-language-server/commit/96715f8c33eb23fb1cb46a9640a8c049410a7a7d

**Comment by andys8** [comment]
Cool :)

Regarding the writable test: I'm thinking about if `Array.some` would be better matching the issue than `Array.every`?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

I'm not sure about the actual use cases. In theory, if one file can be edited and a second can't be edited, it'll lead to issues. Therefore `some`.
But everything is fine for example but there is one non-editable editor generated lock file in the workspace ... and this non-editable file is causing the error. Then it'll be better to go with `every`.

**Comment by Razzeee** [comment]
I played around with every, but was not happy about it.
