### ISSUE TITLE
Documentation: Troubleshooting

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#168]
I feel like there is a bunch of people trying out the language server and it's not working for them, often because of missing configuration or installs. In the long term it would be great to improve error messages in these cases.

As a first step I think it would help to provide documentation for troubleshooting.

* How to collect information / logs and report them (e.g. in vs code or vim)
* Later: collect common mistakes (e.g. binaries not installed or not on path, no elm project)

**Comment by Razzeee** [comment]
How would you suggest to start with this?

**Comment by andys8** [comment]
What would we also people who have an issue like "it crashes"?

* Set the language server logging to verbose (is this actually necessary?)
* Copy message log and paste it in the issue (More detailed description for several editors, maybe images)
* Make sure the versions are up-to-date (`elm-language-server --version`)
* Make sure elm is installed (command e.g. `which elm elm-format elm-test`)
* Copy past configuration (depending on the editor and issue)

Is there something else we can do to improve I've troubleshooting in the first place?

* Check for binaries and throw errors
* Check for versions?
* Add a script to collect data?
* Make sure errors contain information and are visible in messages or for the user for cases like crashes

(I know some of these are already targeted in recent changes)

**Comment by andys8** [comment]
> Check for binaries and throw errors

Looks like there are error messages for cases where the binary isn't found: https://github.com/elm-tooling/elm-language-server/search?q=notFoundText&unscoped_q=notFoundText

**Comment by andys8** [comment]
I started a FAQ section for Vim specific questions (partly redundant): https://github.com/elm-tooling/elm-vim#faq

Maybe a similar section makes sense for `elm-language-server`. Haskell ide engine has a [troubleshooting](https://github.com/haskell/haskell-ide-engine#troubleshooting) section and it's a good example.

**Comment by Razzeee** [comment]
Yes, we should have that too

**Comment by Razzeee** [comment]
I close this for now, as it's still unclear how to proceed. Another option would be to move this to a discussion.
