### ISSUE TITLE
codeActions provider

### ISSUE THREAD

**Issue by bengolds** [elm-tooling/elm-language-server#17]
This is a quite [open-ended provider](https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction) that would be the main place for us to integrate refactoring capabilities.

The `codeAction` spec has some pre-defined Code Action namespaces. I think some editors may display the code actions to the user differently based on the namespace of each action. Some features to support (and their corresponding namespaces) would be:

`Base kind for quickfix actions: 'quickfix'`
- [ ] Add type annotation
- [ ] Automatically add `import` (if a user uses a value from a package they haven't imported yet, add an import line)
- [ ] Replace with... (suggestion for types from elm-make)
- [ ] Add missing case patterns
- [ ] Install package

`Base kind for refactoring extraction actions: 'refactor.extract'`
- [ ] Extract to `let` statement
- [ ] Extract to new function
- [ ] Extract to type alias

`Base kind for refactoring inline actions: 'refactor.inline'`
- [ ] Inline `let` statement
- [ ] Inline function
- [ ] Inline type alias

`Base kind for refactoring rewrite actions: 'refactor.rewrite'`
- [ ] Qualify/unqualify imported value
- [ ] Reorder parameters

**Comment by Razzeee** [comment]
As this seems to be pretty open ended, I would like to close this and have single ticket's for each or at least something that's more realistic to be achived.
