### ISSUE TITLE
Don’t autocomplete when typing `of` in `case … of`

### ISSUE THREAD

**Issue by lydell** [elm-tooling/elm-language-server#177]
## Expected Behavior
No autocomplete when typing the `of` in `case … of`, so that one can press Enter to make a new line without accidentally expanding `of`.

## Current Behavior
When typing the `of` in `case … of` I get autocomplete like anywhere else, such as for something called `Offset` or the `case of` snippet. Many times I type `of<Enter>` in one go and as such accidentally autocomplete.

## Possible Solution
Don’t provide any autocomplete when typing the `of` in a `case … of`. In this case, you never need autocomplete for anything, and after typing `of` you _have_ to enter a newline. If anything, it could offer to autocomplete the word `of`. That does perhaps not save much, but could potentially help beginners who haven’t learned all the words yet. Or it could offer autocomplete for the word `of` plus all branches of the entire `case … of` if the type of `…` could be detected. But now I’m thinking too far ahead :)

## Steps to Reproduce (for bugs)

Starting code:

```elm
module Main exposing (..)

type Offset = Offset Int

foo : Maybe String -> String
foo m =
    "TODO"
```

Erase `"TODO"` and start typing `case m of`. Notice how you get autocomplete for `Offset` and the `case of` snippet.

## Context
This is a minor annoyance I encounter from time to time.

I _could_ use the `case of` snippet more. Then I don’t even need to type `of<Enter>`. But I often forget to use snippets. And sometimes it feels easier to just type it all out. ¯\\\_(ツ)\_/¯

As mentioned in the "Possible Solution" above, this kind of sparks various ambitious side ideas such as generally context-aware autocomplete and type-aware code generation.

## Your Environment
* Version used: 0.6.0
* Editor name and version:  VSCode 1.39.2
* Environment name and version: Node.js v12.8.0
* Operating System and version: macOS Mojave

**Comment by lydell** [comment]
Wow, quick fix!

Does this add `of` as a suggestion _in addition_ to the others? If so, it might not solve the problem. If I use the `case of` snippet a lot, VSCode might select that one by default, couldn’t it? It feels like VSCode has started to remember which autocomplete suggestions I use the most lately.

**Comment by Razzeee** [comment]
I prioritized the `of` suggestion :)
So that's at least what the api enables me to do.
