### ISSUE TITLE
`--version` is not working as expected if installed via npm

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#178]
## Issue

It's using the `package.json` in the working directory...

### Directory without `package.json`
```shell
elm-language-server -v
/home/user/.npm-global/lib/node_modules/@elm-tooling/elm-language-server/node_modules/web-tree-sitte
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):
ule.hasOwnProperty(e)&&(t[e]=Module[e]);Module.arguments=[],Module.thisProgram="./this.program",Module.
a="function"==typeof importScripts,i="object"==typeof process&&"function"==typeof require&&!r&&!a,n=!r&
,l||(l=require("path")),e=l.normalize(e),n=o.readFileSync(e),t?n:n.toString()},Module.readBinary=functi
gv.length>1&&(Module.thisProgram=process.argv[1]

Error: ENOENT: no such file or directory, open '/home/user/dotfiles/package.json'
    at Object.openSync (fs.js:447:3)
    at Object.readFileSync (fs.js:349:35)
    at Function.module.exports.sync (/home/user/.npm-global/lib/node_modules/@elm-tooling/elm-langua
    at getVersion (/home/user/.npm-global/lib/node_modules/@elm-tooling/elm-language-server/node_mod
    at Object.<anonymous> (/home/user/.npm-global/lib/node_modules/@elm-tooling/elm-language-server/
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)))))
```

## Directory with `package.json`

It shows the local version...

```
elm-language-server -v
1.0.0
```

## Related code

https://github.com/elm-tooling/elm-language-server/blob/5a39e7159ecb710e13f2d04102dbbeb27d2b289f/src/index.ts#L18

## Fixes

* Make the typescript import (disallowed by current config) of `package.json` work and replace dependency
* Copy current version into code or file in compile step
* Look for other dependencies that actually work as expected

**Comment by BrianHicks** [comment]
I get this in the 1.4.2 built by nix, too.

**Comment by Razzeee** [comment]
Doesn't seem to work on windows at all
![image](https://user-images.githubusercontent.com/5943908/67210963-3a8a9b00-f41a-11e9-8383-154f68e0fca1.png)

Will try on linux at home.

At work we're using https://www.npmjs.com/package/pjson to log the current version on runtime, not sure if this would work for us too.

**Comment by andys8** [comment]
For windows: It doesn't recognize the arg. So it probably has to be handled differently for windows?

**Comment by Razzeee** [comment]
Probably, not sure when I will be able to test this on a windows machine

**Comment by Razzeee** [comment]
I also would like us to be able to change the help text and add more stuff.

**Comment by Razzeee** [comment]
Forget about that windows log, I somehow ended up calling the old haskell version of the server...

**Comment by andys8** [comment]
If we add more args and help, we should probably use a args parser library. Current implementation feels hacky.
