### ISSUE TITLE
Clean up errors from removed files

### ISSUE THREAD

**Issue by lydell** [elm-tooling/elm-language-server#184]
## Expected Behavior
When a file with errors in it is removed, those errors are removed from VSCode as well.

## Current Behavior
When a file with errors in it is removed, ElmLS seems to think that the file still exists. The error counter in the bottom status bar does not decrease. When I use the "Go to Next Problem in Files" command (<kbd>F8</kbd>) a couple of times, it will eventually try to access the errors in the removed file, showing an error notification in the bottom-right corner of the window:

> Unable to open 'NewFile.elm': Unable to read file (Error: File not found (/Users/lydell/stuff/elm/src/NewFile.elm)).

## Possible Solution
Clean up when files are removed.

## Steps to Reproduce (for bugs)

1. Right-click on your `src/` folder in the sidebar and choose "New File".
2. Call it `NewFile.elm`.
3. Add the following code to it:

    ```elm
    module NewFile exposing (..)

    x : String
    x =
        1
    ```

4. Save. Notice how the `String`/`1` error is highlighted.
5. Right-click on the file in the sidebar and choose "Delete".
6. Press <kbd>F8</kbd> to jump to next error a couple of times.

## Context
I built a feature in a project the other day where the hardest part was coming up with a good API for it. So I played around with lots of different approaches. Naturally, my code was just sketches at this point and full of errors. From time to time I would create a new file to group the API better, then I’d remove some that I realized I didn’t need.

I look at the error counter a lot and use <kbd>F8</kbd> to jump to the next error as a way of finding what to work on next. Then I bumped into the error notification a lot.

The only way to get rid of the stale errors that I’ve found is to use the "Reload Window" command.

## Your Environment
* Version used: 0.6.0
* Editor name and version:  VSCode 1.39.2
* Environment name and version: Node.js v12.8.0
* Operating System and version: macOS Mojave

**Comment by Razzeee** [comment]
Closed via https://github.com/elm-tooling/elm-language-server/commit/769796efe8d057e4d6b35ae0f7e538d2145c66cc

We still need to remove the file from the ast.
