### ISSUE TITLE
Hovering on local parameters should give type

### ISSUE THREAD

**Issue by AllNamesRTaken** [elm-tooling/elm-language-server#189]
Hovering on a local parameter only tells me that it is just that. I would like it to tell me its type so that I do not have to scroll around to find out.
![image](https://user-images.githubusercontent.com/479546/68341233-506db080-00e8-11ea-864c-6c5a3b885bd6.png)

Also when I hover on a scoped property of e.g. an Alias I get no information at all.
![image](https://user-images.githubusercontent.com/479546/68341415-b1958400-00e8-11ea-813d-47d14dfe338f.png)

## Expected Behavior
I expect the popup to show just like it does when hovering on functions.
![image](https://user-images.githubusercontent.com/479546/68341587-0c2ee000-00e9-11ea-90c5-664449a37b7f.png)

## Current Behavior
Currently no hover information is shown for the explained cases.

## Possible Solution
Since the information is there at compile time I guess we have to detect and show it but I have no experience with the language server and cannot estimate the complexity of the task.

## Context
As an Elm beginner I need all the help I can get and that includes information on types I have defined higher up.

## Your Environment
Elm 0.19.0
Windows 10
VSCode 1.39.2
Elm 0.7.2 plugin
node: 12.0.0

**Comment by Razzeee** [comment]
I would have thought that your first example would work. So it's either an oversight or a bug on my part.

I don't think I had time to work on the second one yet.

Anyway, to get the best experience, we should implement type inference. As this currently only get's the types that you define in your code.
