### ISSUE TITLE
Have the option to have Elm check my code as I type, without saving.

### ISSUE THREAD

**Issue by AllNamesRTaken** [elm-tooling/elm-language-server#190]
I would like to have elm check my code continuously as a I type without having to save all the time out have autosave on.

## Expected Behavior
Elm gets the current state and compiles it draws squiggles etc as I type my code without having to save it.

## Current Behavior
Elm does not check my code until I save or turn on autosave (which then is editor wide).

## Possible Solution
I do not know the architecture as of writing this but I imagine opening up the language server to either have code passed to it in other ways or saving as temp files and telling it to use those instead when compiling.

## Context
As a beginner Elm dev I find it gave me an unpolished experience that I out of the box got no feedback on my code as I typed and then found out that I had to turn on autosave which is editor wide and affects my other environments and languages as well.

## Your Environment
Elm 0.19
Windows 10
VS-code 1.39.2
Elm plugin 0.7.2
node 12.0.0

**Comment by Razzeee** [comment]
I think we're basically blocked by the elm compiler here. Only thing we could do is, do all these checks on our own in the language server.

**Comment by meowgorithm** [comment]
For what it's worth I've noticed that the [Elm language server under ALE](https://github.com/dense-analysis/ale/blob/8097d51e3357f4ab3e31c5614dee94a0a5807b9a/ale_linters/elm/elm_ls.vim) shows compiler errors on change, whereas with CoC and VSCode it does not.

And I will add that's (with ALE) it's quite wonderful getting Elm compiler feedback as you type.

**Comment by Razzeee** [comment]
It's probably just saving your file all the time.

**Comment by meowgorithm** [comment]
Ah, you're right. It's actually not overwriting the file in place; it's writing to `$TMPDIR` and linting against that.

**Comment by jmbockhorst** [comment]
Now with type inference support, we can create the diagnostics like the elm compiler ourselves and update them without saving.

**Comment by Razzeee** [comment]
Another layer beside type inference would be to get error messages from tree-sitter as described in https://github.com/elm-tooling/elm-language-server/issues/6 but not yet implemented in tree-sitter.

**Comment by jmbockhorst** [comment]
I would say this is done now. We will always be improving it, but its mostly there.
