### ISSUE TITLE
Feature: auto import

### ISSUE THREAD

**Issue by jonathanmoregard** [elm-tooling/elm-language-server#193]
## Expected Behavior
When activating quickfix through the vscode command "editor.action.quickFix" while the cursor is on a call site for an **unimported** function or type; I want the option to import the module containing the function/type.

The Haskell Language Server for haskell (https://marketplace.visualstudio.com/items?itemName=alanz.vscode-hie-server) does this pretty well  

Like this (Maybe is not imported here, quickFix allows me to import it, so that mapMaybe is available):
![image](https://user-images.githubusercontent.com/10191435/67378177-24e6b400-f587-11e9-8f36-6b687b5a33fb.png)
(command for displaying context menu: "editor.action.quickFix")

## Current Behavior
No import action available through quickfix.

## Context
When coding, I spend a lot of time importing things as new needs arise. If this could be done automatically I'd be a very happy person

**Comment by NikosEfthias** [comment]
this would be amazing
