### ISSUE TITLE
[Feature] Jump to definition for destructured field

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#197]
```
demo : Model -> Html Msg
demo { form } =
    div []
        [ submitArea form ]
```

## Expected Behavior
* Cursor on `form` (last line) jumps to file and record field `form` (preferred)
* ... jumps to argument in line 2 (alternative but less useful)

## Current Behavior
It doesn't

**Comment by Razzeee** [comment]
This should work with master now. Destructured let functions won't work for now.

```
viewPage page toMsg config =
            let
                { title, body } =
                    Page.view viewer page config
            in
            { title = title
            , body = List.map (Html.map toMsg) body
            }
```

**Comment by Razzeee** [comment]
Should also work now
