### ISSUE TITLE
Easily mass-remove unused function

### ISSUE THREAD

**Issue by namoscagnm** [elm-tooling/elm-language-server#201]
## Expected Behavior
I see uncountable warnings of unused functions in my Elm project and would like to remove them all, but it takes way too much time. It would be nice to have following options:
 - Remove all unused functions in a file
 - Remove all unused functions in a directory
 - Remove all unused functions in project 

## Current Behavior
I see uncountable warnings of unused functions in my Elm project and would like to remove them all, but it takes way too much time because its a manual process

## Possible Solution
CLI: Generate a file with all unused functions, and use this file to a functionDeleter script, which would read it and delete.
GUI: A menu asking to remove all unused functions for project, and I can click "go ahead" or cherry-pick them

## Steps to Reproduce (for bugs)
Not applicable

## Context
After starting to work in an OpenSource Elm project, I see many unused functions inherited from previous commits, and now I need to delete them all, but this will take too much time.

## Your Environment

* Version used: elmtooling.elm-ls-vscode 0.7.4
* Editor name and version (e.g. VSCode 1.36.1):  VSCode 1.41.1
* Environment name and version (e.g. node.js 5.4): Unknown
* Linux Mint 18

**Comment by Razzeee** [comment]
We at least have this on a file level, but it might fix other things too, not only unused functions.

**Comment by Razzeee** [comment]
Should be pretty good with the latest version. I don't think we want project level and directory level options. It would probably be too hidden and only useful in rare cases. Closing for now.
