### ISSUE TITLE
Show function/variable/Type type info in popup

### ISSUE THREAD

**Issue by girishso** [elm-tooling/elm-language-server#202]
Show function/variable/type alias/custom type "type" info in popup on hover or some hotkey press.

## Expected Behavior
![image](https://user-images.githubusercontent.com/35009/71557954-97867b00-2a73-11ea-945f-22d91aa926f2.png)

Better still, showing function docs with link to the documentation/jumping to definition (like atom elmjutsu)
![image](https://user-images.githubusercontent.com/35009/71606774-ed554300-2b99-11ea-8f7a-be6c0f7536fc.png)

## Current Behavior
There's no way of seeing type info currently.

## Possible Solution
The only way possible currently is to jump to the definition.

## Context
It helps to know function/variable/type alias/custom type definition without having to jump to definition then back.

## Your Environment

* Version used: vscode plugin 0.7.4
* Editor used: vscode
* Environment name and version (e.g. node.js 5.4):
* Operating System and version: Mac OS 10.13.6

**Comment by Razzeee** [comment]
I'm not sure, what part your exactly asking for.

Here's what we currently show:
![image](https://user-images.githubusercontent.com/5943908/72389229-2bb93900-3728-11ea-832d-132bc3626e00.png)

Do you mean a hint if the symbol is a type, a type alias or a function?

**Comment by girishso** [comment]
Cool, that's exactly what I was asking for! Is that a very recent addition?

Couple of things still missing
1. It seems to only work for external elm packages, not the project (user defined) functions/types.
2. Link to the documentation for external packages or jumping to definition for user defined functions/types.

**Comment by Razzeee** [comment]
No, it shouldn't be recent at all.

1. Should work fine with user defined things, at least it does for me
2. Jumping to definitions should be working fine. Embedding links to websites is unfortunately not possible as far as I can tell.

Can you test whatever is not working for you on the spa example (https://github.com/rtfeldman/elm-spa-example) so that we have a common codebase to understand each other better? Are you sure you have no other plugins interfering?

**Comment by Razzeee** [comment]
Any update on this?

**Comment by girishso** [comment]
Yes, it does indeed work for user defined things. Guess some other plugins were interfering.

But all it does is shows docs for the user defined types.
![image](https://user-images.githubusercontent.com/35009/73045820-83c50d80-3e95-11ea-90b1-66c7384801b9.png)

I really like how atom does it..
![image](https://user-images.githubusercontent.com/35009/73045888-cb4b9980-3e95-11ea-877e-3bfd7411950b.png)

Secondly, VSCode doesn't show any popup for custom type constructors
![image](https://user-images.githubusercontent.com/35009/73045945-0352dc80-3e96-11ea-9f6b-b32a134d62d7.png)

VSCode user defined functions:
![image](https://user-images.githubusercontent.com/35009/73046219-36e23680-3e97-11ea-95e6-199f18f71176.png)

Atom user defined functions: Notice the type annotation hyper links
![image](https://user-images.githubusercontent.com/35009/73046152-f08cd780-3e96-11ea-8b9b-018d8feac3b3.png)

Will be happy to contribute.

**Comment by Razzeee** [comment]
I don't think we can hyperlink, but everything else should be possible. Hyperlinks would be needed in the language server protocol, I think there are some issues in their github repo about that.

**Comment by Razzeee** [comment]
I'm now showing the code for type annotations in hovers and autocompletions. I'm going to close this for now. It would be helpful if you open multiple tickets for each different thing your still missing, as it will make communication much easier.

**Comment by girishso** [comment]
Mind blowing!
![image](https://user-images.githubusercontent.com/35009/73316657-9060b180-4259-11ea-8a27-3f2633389f3b.png)

Thanks @Razzeee !
