### ISSUE TITLE
Elm analyse version out of sync with mainline

### ISSUE THREAD

**Issue by jgresty** [elm-tooling/elm-language-server#203]
## Expected Behavior
Running elm language server produces the same warnings as mainline elm analyse.

## Current Behavior
Elm language server does not produce all the warnings that mainline elm analyse produces. 

## Possible Solution
Change dependency for elm analyse to use mainline published package.

## Context
I am running elm language server in my editor and elm analyse in CI, it is really frustrating when a warning appears in CI that was not raised to me while editing. I can see in db43b4a4d99d4990a5dbdbeb51e13fc81843752c that the dependency on elm analyse was changed to a fork but there is no clear reason why this changed happened and the fork is now 6 months out of date.

## Your Environment
* Version used: 1.4.6
* Editor used: n/a
* Environment name and version (e.g. node.js 5.4): n/a 
* Operating System and version: n/a

**Comment by Razzeee** [comment]
There are some essential changes like
https://github.com/stil4m/elm-analyse/pull/222#issuecomment-570531428 that
we need to mainline first.

**Comment by Razzeee** [comment]
Master should be up to date again. Moving stuff upstream should be tracked in a different issue.
