### ISSUE TITLE
Windows path to file form analyse not matching

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#21]
@antew Windows seems to report the whole path here:
https://github.com/elm-tooling/elm-language-server/blob/master/server/src/providers/diagnostics/elmAnalyseDiagnostics.ts#L76

Like: `message.file == "..\..\..\c:\development\Weiterbildung\elm-spa-example\src\Main.elm"`

**Comment by Razzeee** [comment]
Only seems to affect file opening/changing paths. Other seem fine.

**Comment by antew** [comment]
Oh that's weird, I'll check it out.

**Comment by Razzeee** [comment]
After I saw that it started to work normal after a restart. Not sure why this was.

**Comment by Razzeee** [comment]
![image](https://user-images.githubusercontent.com/5943908/57626273-da075000-7595-11e9-984a-f40791dde13b.png)

> Only seems to affect file opening/changing paths. Other seem fine.

Also seems like it does not run on the whole project in these cases, only the files I actively opened.

**Comment by antew** [comment]
It was messing up on getting a relative path to the file that elm-analyse needs, #26 should fix it :)
