### ISSUE TITLE
import aliases generate unused error regardless of being used.

### ISSUE THREAD

**Issue by NikosEfthias** [elm-tooling/elm-language-server#215]
When you `import Something.Something as Something` my ide always produces an error saying Something is unused
![image](https://user-images.githubusercontent.com/9097437/73891326-7a707380-488d-11ea-8460-6fc4f0f7b697.png)
![image](https://user-images.githubusercontent.com/9097437/73891338-81978180-488d-11ea-90cc-68986cc52f51.png)

## Expected Behavior

No warnings produced

## Steps to Reproduce (for bugs)

1. install Ale plugin for neovim
2. set linter back-end to elm_ls `:let b:ale_linters = ['elm_ls']<cr>`
3.enable Ale if disabled `:ALEEnable`
4.run the linter `:ALELint`

## Context

I jump errors using various keybindings one of which is used to jump to the first error or warning and this issue is a huge productivity problem, in this case, reporting a false warning.

## Your Environment

* Version used:`1.5.0`
* Editor used:`neovim`
* Environment name and version (e.g. node.js 5.4): `node.js v12.14.1`
* Operating System and version:`Pop!_OS 19.10`

**Comment by Razzeee** [comment]
These are generated by elm-analyze, can you run that tool normally and check if you get the same output?

**Comment by NikosEfthias** [comment]
Yes, elm-analyse definitely reports that one
![image](https://user-images.githubusercontent.com/9097437/73927458-e3d29f80-48ea-11ea-800b-b708da2c23d2.png)

**Comment by Razzeee** [comment]
Are you sure your using it? I would be very surprised, if you were the first one to get this error. I think the code has been unchanged for quiet some time. Anyway, you will need to raise that problem with `elm-analyze` then https://github.com/stil4m/elm-analyse

I'll close this for now.

**Comment by NikosEfthias** [comment]
I did an `npm install -g elm-analyse` then ran `elm-analyse` on my project root.
Is there anything else to it ?

**Comment by Razzeee** [comment]
My question was, if your sure your using `Api` in your file? If you remove `as Api` from `import Api.Api as Api`, does your code still compile?
