### ISSUE TITLE
Add if else snippet and completion support

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-server#219]
Currently there is no if then else support, which makes it difficult to write them. A snippet would be nice. Also, the word `then` always autocompletes to `Maybe.andThen` when pressing enter or tab, which makes it hard to write if else statements.

**Comment by Razzeee** [comment]
So I guess it might make sense to also add `then` and other keywords to the autocompletions. `let`, `in` and `if` come to mind.
