### ISSUE TITLE
Show type information on hovers using type inference

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-server#234]
It should infer types of union type data and show completions for those data types.

``` elm
type alias Data = 
    { field : String
    }


type Msg = 
    GotData (Result Http.Error Data)


update : Msg -> Model -> ( Model, Cmd Msg )
update msg model =
    case msg of
        GotData result ->
            case result of
                Ok data ->
                    ( model, Cmd.none )

                Err error ->
                    ( model, Cmd.none )
```

In this case, hovering should show types for `result`, `data`, and `error` as `Result`, `Data`, and `Http.Error`, respectively. Using `data.` and `error.` should show completions for those types.

**Comment by jmbockhorst** [comment]
@Razzeee I was wondering if we needed to split the code that finds definitions and does hovers. 

In the example above, hovering over `data` should show that it is `Data` type, but if I "Go to definition" (F12) on `data`, should it jump to the `Data` definition? Its not really the definition, just the type. If not, I believe that we would need to split the code to be different for hovers and go to definition, since they share the same logic now.

Maybe for hovers, instead of `findDefinitionNodeByReferencingNode`, a new function like `findTypeDefinitionNode` (?) that handles these more specific cases to always return the type.

**Comment by Razzeee** [comment]
I actually don't think we need to do that. The design should be composable, so far it made sense to always go to the source of a thing and figure stuff out from there.

The question is, would your proposed `findTypeDefinitionNode` also go via the source/definition, or could it skip it? In most cases, where we go to the source, it makes it pretty easy to figure  out other stuff, like what is the type of `model` -> just check in the the line above, going from the source. In the future we might be able to do this with our own type inference.

Regarding `findTypeDefinitionNode`
Pro:
* Better for performance

Contra:
* Might not be as understandable as having the old design

**Comment by jmbockhorst** [comment]
The idea of a `findTypeDefinitionNode` would be to always find the type of every variable. This would use the current find definition function for some cases, and handle special cases as well. It would allow some variables to have the proper type, but not have to be tied as a reference to that type. 

To solve this problem, we would need to add cases to `findDefinitionNodeFromReferencingNode` (That's all that the hover provider uses), which would also affect other things like "Go to definition". In the example above, `data` would reference the type alias `Data`, `error` -> `Http.Error`, etc. Is that behavior that we want?

**Comment by Razzeee** [comment]
Yeah, the split behavior is what we want, but ideally we only need to ask the type inference to get the type for us. Whenever we get that implemented :D

**Comment by jmbockhorst** [comment]
Oh, sorry. Type inference is what I meant by the `findTypeDefinitionNode` function. Do you already have a separate issue/plan for that?

**Comment by Razzeee** [comment]
well there is a branch, but as I'm doing this in my free time, there is no eta.
