### ISSUE TITLE
Removing last exposed from should remove expose syntax

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#236]
We also need to be able to expose functions on modules that have nothing exposed so far

Prevent `module Test exposing ()` instead do `module Test`

`module Test` -> `module Test exposing (, something)` (this might actually be fixable with elm-format? )

FYI @jmbockhorst

**Comment by jmbockhorst** [comment]
I don’t believe that it is fixable with elm-format, because I think I played around with that.

**Comment by Razzeee** [comment]
Yeah, it would be better to fix it anyway, will look at it this evening, if I find some time.

**Comment by Razzeee** [comment]
Fixed by https://github.com/elm-tooling/elm-language-server/commit/b12d157f7c0723c823b0c5ffde2a45e7bb2a6015
