### ISSUE TITLE
Missing language features in imported files

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-server#240]
There are no language features in any imported or external files (hovers, definitions, etc). This has broken some behavior with record completions with definitions external files and probably more. 

Steps to repro:
- Jump to `String.elm` using "Go to Definition" on `String` type
- In `String.elm`, try to hover over anything or jump to other definitions of types.
- Nothing works.

**Comment by Razzeee** [comment]
Can you write up how to test this? I'm not sure I'm understanding what exactly the problem is.

**Comment by jmbockhorst** [comment]
I updated with steps to repro. I'm not what is going on because I tried in 1.6.3 and it didn't work either, but I thought for sure this was working when I was adding record completions from imported files.

**Comment by Razzeee** [comment]
Hrm, might be a change in a newer vscode version? The commands that ask for most of the data don't seem to be triggered for files outside of the project folder anymore.
Can't easily install an old vscode version on my current setup, will try again tomorrow.

**Comment by jmbockhorst** [comment]
I tried an older version of vscode and it still didn't work. After some investigation, it looks like it is being stopped here: https://github.com/elm-tooling/elm-language-client-vscode/blob/5ddd070d120c20e03c16eab973414e008b06a738/client/src/extension.ts#L94

Did this ever work?

**Comment by Razzeee** [comment]
I thought so, still it would be confusing. Especially if you have multiple projects open. As those central files would be imported from everywhere.

**Comment by jmbockhorst** [comment]
I think we will need to be able to find references in external files for many language features using imported functions and types.

**Comment by Razzeee** [comment]
I think that's still working fine, the frontend just doesn't ask for it on
those files.

**Comment by jmbockhorst** [comment]
Ah, of course. Then, I need to go back and see what broke the record completions for imported functions.
