### ISSUE TITLE
Request textDocument/codeAction failed with message: Cannot read property 'localeCompare' of undefined

### ISSUE THREAD

**Issue by domenkozar** [elm-tooling/elm-language-server#242]
Since yesterday (seems like due to version update), my VSCode Elm integration no longer works and errors out with:

```
[Info  - 11:03:29 AM] A code action was requested
[Error - 11:03:29 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'localeCompare' of undefined
  Code: -32603 
```

**Comment by Razzeee** [comment]
@jmbockhorst any idea for this?

**Comment by domenkozar** [comment]
My wild guess is that I'm using a package not in https://github.com/elm-tooling/elm-language-server/blob/9dced362758e5591e15f43d34d22a81ba164829c/src/providers/ranking.ts

**Comment by jmbockhorst** [comment]
@domenkozar you are correct. This is the line that is failing: https://github.com/elm-tooling/elm-language-server/blob/b1c0dfb3b434a15d8b02b426fae0953a90f8a5b6/src/util/importUtils.ts#L65

**Comment by Razzeee** [comment]
@jmbockhorst can you do a fix or should I go ahead?

**Comment by jmbockhorst** [comment]
I think #243 should do it.

**Comment by Razzeee** [comment]
@domenkozar can you test master? Otherwise I'm just going to push a new hotfix today.

**Comment by domenkozar** [comment]
Is there a way to tell VSCode extension where is elm-language-server?

**Comment by Razzeee** [comment]
No, you would need to checkout the client https://github.com/elm-tooling/elm-language-client-vscode#contributing--debugging and run it via the included build steps

**Comment by domenkozar** [comment]
I'll wait for the release, looking at the diff it seems like it should work :)

**Comment by Razzeee** [comment]
Okay, will prepare something in a few hours.

**Comment by domenkozar** [comment]
Works, thank you!
