### ISSUE TITLE
Record update autocompletions not working in vim

### ISSUE THREAD

**Issue by bengolds** [elm-tooling/elm-language-server#245]
The new record update autocompletion doesn't seem to work in neovim with CoC:

Expected (works in VSCode):
<img width="756" alt="ScreenCapture at Thu Apr 2 10:53:01 PDT 2020" src="https://user-images.githubusercontent.com/446007/78282118-9d578680-74d0-11ea-9184-b0a0a0016759.png">

Current (fails in neovim)
<img width="823" alt="ScreenCapture at Thu Apr 2 10:52:33 PDT 2020" src="https://user-images.githubusercontent.com/446007/78281942-56699100-74d0-11ea-9d35-398cd2c6c6c1.png">
It appears the autocompletions have no context -- the fact that `fieldNumberOne` and `fieldNumberTwo` even show up in the list seems to just be Vim's token completion.

## Your Environment
* Version used: Elm LS 1.7.0
* Editor used: nvim, master branch of CoC
* Operating System and version: Mac 10.15.3

**Comment by jmbockhorst** [comment]
Actually, it doesn't seem to be working in VSCode either (The completion would have some documentation). This is because currently it needs to closing `}` for it to understand that it is updating a record. This is a case we could look at handling as well.

**Comment by Razzeee** [comment]
The completions you see in vscode are not from the language server, but from vscode in checking which words are used in you file. You can see that by looking at the symbol used.

**Comment by Razzeee** [comment]
Has this been fixed via lsp-mode?

**Comment by Razzeee** [comment]
Closing due to no feedback
