### ISSUE TITLE
Autocomplete for record access

### ISSUE THREAD

**Issue by bengolds** [elm-tooling/elm-language-server#247]
This is a feature request.

Based off of the "autocomplete for record updates" feature in 1.7.0, it'd be nice to see the same feature for record access. e.g.

```elm
bob = 
  { name = "Bob"
  , age = 32
  , address = "Nowhere"
  }

shipTo =
  bob.|
     -- Would be nice to see autocomplete show name, age, and address here.
```

I'm not sure if this would require more type annotation than the record update feature -- but it'd be handy!

**Comment by jmbockhorst** [comment]
@Razzeee is there something in the client grammar that needs updated for this to work? I can get the server to send the correct completions to the client, but VSCode still isn’t showing them.

**Comment by Razzeee** [comment]
That shouldn't be the case, are you sending them as `bob.name` or as `bob`? The range field on the completion might also cause problems I guess?

**Comment by jmbockhorst** [comment]
I was just sending `name` with the range starting after the `.`. Wouldn't that be the ideal completion?

**Comment by Razzeee** [comment]
Might be, but you probably need to change the range then, from memory I would think that the range expects it to be `bob.name`. 

It's kind of a hack, as I build completions this way to be able to complete stuff not based on sections, but complete stuff. So you will write `Htm` and get `Html.Attributes.class` in the list, most other languages would just complete `Html`, let you enter a point and then figure out the next section. I mostly did it the other way, as it seemed easier.

**Comment by bengolds** [comment]
This works great in the newest version! 🙌
