### ISSUE TITLE
completionProvider v2

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#25]
- [x] Local available functions due to let
- [x] Local available parameters from functions wrapping
- [x] Complete on type alias access
- [x] Complete parameters from switch

Context sensitive completions:
- [x] Complete imports 
  - [x] Exposing list
  - [x] Import name
- [x] Complete modules
  - [x] Exposing list
  - [x] Disable completions for module name

**Comment by bengolds** [comment]
Mind if I take this on? I was looking at it today and I think I’ve got a grasp on how to do it.

I did have one spot of difficulty — when typing the import statement from the left, tree-sitter doesn’t know what node we’re in. 

For example, if ^ is the cursor:
import Html exposing (Html, ^ div) <— tree-sitter says our node is type “exposing_list”, with parent node of “import_clause” 👍
import Html exposing (^ <— tree-sitter says our node is type “ERROR” with parent node of type “file” 👎

I could try to regex the line before the cursor? Is there another approach I should think about?

**Comment by Razzeee** [comment]
Yeah, i'm not sure how to do that too.

So either do some testing around that or implement the other features, which I also think make a bigger impact.

**Comment by bengolds** [comment]
Another approach occurred to me last night; what if we add an “incomplete_import_clause” to the grammar? It could then handle these two cases:

import ^ <— give a list of all importable modules
import X exposing (^ <— give a list of all exported values

Having the parser be more error tolerant is probably only a good thing. Mayhaps something like this could work for incomplete functions when writing let statements? 🤔

**Comment by Razzeee** [comment]
in general, i think it's possible to write the tree sitter in a way that it will still parse the incomplete import correctly, with the error node inside the correct node.

i mostly spend time on getting the happy path of the parser to work. so that's probably how I would want to do this.

**Comment by Razzeee** [comment]
Updated this issue. As I just ticked of a task.
