### ISSUE TITLE
Module function and local variable same name doesn't show correct documentation

### ISSUE THREAD

**Issue by romariolopezc** [elm-tooling/elm-language-server#252]
## Expected Behavior
When having the cursor in `Form.for|m` (| is the cursor), the correct documentation should pop out about the module, instead, the documentation of the `Html.form` fn is being shown. The local variable `form` is a type alias defining a record, but is showing `Html Msg` and saying local parameter, which both are wrong.

## Current Behavior
Cursor in `Form.for|m`
![image](https://user-images.githubusercontent.com/6199588/78456563-b04d9080-7661-11ea-9700-dde55b80f54b.png)

Cursor in `Form.form` (Showing correct documentation)
![image](https://user-images.githubusercontent.com/6199588/78456571-bb082580-7661-11ea-9b5a-d760f838c233.png)

## Possible Solution
If the function is scoped (Module name), look for the module documentation?

## Context

I'm trying to see the documentation of `Form.form`

## Your Environment

* Version used: 1.7.1
* Editor used: NeoVim
* Environment name and version (e.g. node.js 5.4): Node 10.17.0
* Operating System and version: Arch Linux 5.5.13-arch2-1

**Comment by Razzeee** [comment]
Thank you for reporting this!
