### ISSUE TITLE
Many irrelevant completions are offered after typing ModuleName Dot

### ISSUE THREAD

**Issue by frou** [elm-tooling/elm-language-server#257]
With the following file, I position the caret after `Html` and type `.` to request completions

```elm
module Main exposing (..)

import Html


main =
    Html
```

## Expected Behavior

Only stuff from the `Html` module is offered as completions.

## Current Behavior

A huge amount of stuff including language keywords, operators, functions & types from other modules, snippets, etc, are offered in addition to Html stuff (which is itself way down the list).

<img width="403" alt="Screenshot 2020-04-18 at 15 04 34" src="https://user-images.githubusercontent.com/172663/79639834-08b67f00-8186-11ea-919b-e8cad70b0460.png">

[Click here for complete log from Sublime LSP](https://gist.githubusercontent.com/frou/7244ce62dec7405dbdf806c4a4cb828c/raw/14f8ee02edabdc17cfef05ab924591974384346e/gistfile1.txt)

## Your Environment

* Version used:
  * elm-language-server v1.7.2
  * node v13.12.0
* Editor used
  * Sublime Text 3 v3210
  * LSP for Sublime v0.9.8 
* Operating System and version
  * macOS 10.15.4

---

cc @predragnikolic

**Comment by Razzeee** [comment]
This actually seems to be a problem with the sublime lsp implementation of completions, we had the same with CoC for Vim in this issue https://github.com/elm-tooling/elm-language-server/issues/211

And this on coc side of things:
https://github.com/neoclide/coc.nvim/issues/1530

Can you create an issue on the sublime lsp repo?

**Comment by frou** [comment]
It's not clear to me why the Server sends the huge list of completions in the first place. If they weren't sent over the wire at all, then there'd be no need for the Client to to filter most of them out?

**Comment by Razzeee** [comment]
Yes, the list can probably be cut down. But that doesn't change, that the client is not correctly filtering as soon as it hits a `.`. As we're sending complete items (`Html.span`) instead of doing `Html` then `span` we need to have the client correctly filter that. This should explain it best https://github.com/microsoft/language-server-protocol/issues/898#issuecomment-593968008

**Comment by frou** [comment]
@Razzeee Thanks and I appreciate your time dealing with this. Here's what comes to mind to me (Feel free to tell me I'm full of it!):

At a more abstract level, if we think about the division of responsibilities between Server and Client in LSP. It's the Server that's supposed to have ALL the "smarts" about its given language.

So in response to a completion request at the precise position following ModuleName Dot, it should only respond with stuff that's both valid in terms of language semantics (i.e. no symbolic operators, keywords, ...) *and* relevant (i.e. not relating to other modules).

Ultimately, it's the Server's responsibility to take all language semantics and scoping into account, BEFORE it sends the response. The fact that some Clients, based on simple string matching, bump irrelevant stuff to the end of the completion widget (or hide them) is just masking a breakdown in responsibilities of Server vs Client.

**Comment by Razzeee** [comment]
In theory you're right. But clients do have way more stuff to configure, that not gets send to the server. Have a look at `editor.snippetSuggestions` for vscode for e.g.

Handling all these custom rules on the server side would be a huge task I think, so a middle ground might be the best in this case.

**Comment by frou** [comment]
I no longer see the irrelevant completions in Sublime Text 3 😃 Not aware of what fixed it (this LS, the ST LSP plugin, or both) but I'll close this issue now.

It looks like there's a broadly similar issue still open, from someone with a completely different enivornment: https://github.com/elm-tooling/elm-language-server/issues/258
