### ISSUE TITLE
Autocompletion for records misbehaviour when typing the "dot"

### ISSUE THREAD

**Issue by romariolopezc** [elm-tooling/elm-language-server#258]
## Expected Behavior

Display the same list as writing the record name

## Current Behavior

When clicking dot, the autocomplete doesn't show the previous list that was correct

## Possible Solution

Show the same list?

## Steps to Reproduce (for bugs)

1. Define a record
2. Start to write the name when using the record, the list will display the record attributes correctly
![image](https://user-images.githubusercontent.com/6199588/79678253-01f82e00-81bf-11ea-8f3b-5473a4c15827.png)

3. When pressing "." the list will display not related items
![image](https://user-images.githubusercontent.com/6199588/79678257-0a506900-81bf-11ea-9543-8ace254f116b.png)

## Your Environment

* Version used: 1.7.2
* Editor used: Neovim
* Environment name and version (e.g. node.js 5.4):
* Operating System and version: ArchLinux

I think this one can be related: https://github.com/elm-tooling/elm-language-server/issues/252 (under cursor document)

**Comment by romariolopezc** [comment]
I just checked and Module. has the same behaviour. This was already reported and fixed. Seems like a regression #252

**Comment by Razzeee** [comment]
Are you on the lastest coc version (I assume your using coc, I have no idea about vim)? There was a fix included for this.

**Comment by romariolopezc** [comment]
Yes, I'm on the latest of branch: release

Neovim, using coc

**Comment by Razzeee** [comment]
I guess your also hitting a case of https://github.com/elm-tooling/elm-language-server/pull/251

Can you confirm, that it works fine again, as soon as you enter something after the `.`?

**Comment by romariolopezc** [comment]
I updated coc to: `a956ac8 fix(util): set buflisted=1 for coc#util#open_files (6 hours ago)` and is the same behaviour. 

GIF:
![coc-wrong-autocompletion](https://user-images.githubusercontent.com/6199588/79787197-3a595280-830c-11ea-8ca0-2d8e9323e38c.gif)

**Comment by Razzeee** [comment]
Can you test this with elm-spa-example? Lets go for the article file and the model there. I tested this with VSCode and it seems to work fine for me.

![Peek 2020-04-20 21-53](https://user-images.githubusercontent.com/5943908/79793746-5f23e900-8351-11ea-9034-6ea9cda18925.gif)

**Comment by romariolopezc** [comment]
Same behaviour:
![coc-wrong-autocompletion-2](https://user-images.githubusercontent.com/6199588/79872543-8909f980-83ab-11ea-8743-9e28965e0397.gif)

**Comment by Narice** [comment]
same here in doom emacs with the latest elm-language-server git version built from source

**Comment by Razzeee** [comment]
Can we retest this, I would still think that the problem is in the client used, but there have been various improvements since then.

**Comment by romariolopezc** [comment]
I just tested and is working as expected in NVim
![image](https://user-images.githubusercontent.com/6199588/91647760-f4339e80-ea23-11ea-8803-e92ce35c55da.png)
