### ISSUE TITLE
elm-language-server error in emacs?

### ISSUE THREAD

**Issue by zeta-00** [elm-tooling/elm-language-server#261]
here's the error that i posted in elm/reddit:

 https://www.reddit.com/r/elm/comments/g7cfea/elmlanguageserver_error_in_emacs/   

if you could explain to me what's going on and how to fix this, thanks in advance

**Comment by Razzeee** [comment]
Hey, haven't seen that before. It's weird, that the crash log says node 10 but your print says node 12.

**Comment by zeta-00** [comment]
@Razzeee  , ya that's weird, i need to double check to see how nix does things they might package elm/elm-language-server together with node, so i won't need to install it separately. Anyways, I finally got elm-ls up and running by setting: export NODE_OPTIONS="--max-old-space-size=4096"  , but now 2 other errors are being thrown?

eldoc error: (args-out-of-range HomePage.elm 4 5) [2 times]
company-call-backend-raw: Company: backend company-lsp error "[yas] ‘yas-expand-snippet’ needs properly setup ‘yas-minor-mode’" with args (post-completion import)

**Comment by zeta-00** [comment]
@Razzeee , ok, so i somewhat fixed the yasnippet error by setting `(yas-global-mode +1)` in my .emacs, anyways, as for the eldoc error, when i activate the debugger in emacs and start typing this error gets thrown?

Debugger entered--Lisp error: (args-out-of-range #<buffer HomePage.elm> 2 3)
  buffer-substring-no-properties(3 2)
  elm-oracle--function-at-point()
  elm-oracle--item-at-point()
  elm-oracle--type-at-point()
  elm-eldoc()
  apply(elm-eldoc nil)
  #f(advice-wrapper :before-until #f(compiled-function (&rest args) #<bytecode 0x11130d5>) elm-eldoc)()
  apply(#f(advice-wrapper :before-until #f(compiled-function (&rest args) #<bytecode 0x11130d5>) elm-eldoc) nil)
  #f(advice-wrapper :before-until #f(advice-wrapper :before-until #f(compiled-function (&rest args) #<bytecode 0x11130d5>) elm-eldoc) lsp-eldoc-function)()
  eldoc-print-current-symbol-info()
  #f(compiled-function () #<bytecode 0x2002c3>)()
  apply(#f(compiled-function () #<bytecode 0x2002c3>) nil)
  timer-event-handler([t 0 0 500000 nil #f(compiled-function () #<bytecode 0x2002c3>) nil idle 0])

**Comment by zeta-00** [comment]
also, elm-ls takes a long time to initialize(about 10 seconds) ? i have lsp setup for other languages and it loads almost instantly so i have no idea what's going on there?

**Comment by Razzeee** [comment]
the elm oracle stuff seems weird, we're not using elm-oracle in any way. so you either installed something wrong or still have traces of an old setup.

init can take long on big repos.

**Comment by zeta-00** [comment]
@Razzeee , ok, i disabled eldoc using by placing: `(global-eldoc-mode -1)` in my .emacs, which removed all those errors being thrown. As long as elm/elm-lsp does not depend on eldoc, then i should be good to go.

**Comment by ni-ko-o-kin** [comment]
Which elm-mode version are you using?

**Comment by zeta-00** [comment]
@ni-ko-o-kin , here's what emacs returned for the elm-mode package:


elm-mode is an external package.

     Status: External in ‘/nix/store/ldr6cdv2s6hsv7ma0gbq1rnh9nns7qbz-emacs-packages-deps/share/emacs/site-lisp/elpa/elm-mode-20191228.2356/’ (unsigned).
    Version: 20191228.2356
    Summary: Major mode for Elm
   Requires: f-0.17, s-1.7.0, emacs-25.1, dash-2.13.0,
               reformatter-0.3
   Homepage: https://github.com/jcollard/elm-mode

**Comment by ni-ko-o-kin** [comment]
try to use the latest version which is https://github.com/jcollard/elm-mode/commit/7782be0814b52f7c35a09b21a4839c1502a4707f

and the latest version for lsp-mode too!

**Comment by Razzeee** [comment]
Can I close this?

**Comment by zeta-00** [comment]
@Razzeee , ok, so i was able to fix that node out of memory error with this environment variable, now the elm language server works(it takes a while to load though):

export NODE_OPTIONS="--max-old-space-size=4096"

**Comment by zeta-00** [comment]
@Razzeee @ni-ko-o-kin , thanks for the help everyone, i have elm language server working now, so go ahead and close this issue.
