### ISSUE TITLE
Support code comments in the document symbol provider

### ISSUE THREAD

**Issue by Kurren123** [elm-tooling/elm-language-server#264]
I've read in a few places that it's not unusual for Elm files to be long. To me this means that the outline view (which relies on the document symbol provider) needs to be used more for navigation than a language with typically shorter files. I have seen the NoRedInk guys suggest using comments to help with navigation. Eg in the [elm guide](https://guide.elm-lang.org/architecture/buttons.html), we have code like this:

```elm
import Browser
import Html exposing (Html, button, div, text)
import Html.Events exposing (onClick)



-- MAIN


main =
  Browser.sandbox { init = init, update = update, view = view }



-- MODEL

type alias Model = Int

init : Model
init =
  0


-- UPDATE
```

... and so on. I would suggest a setting provided by the IDE/text editor where we the user can specify a regex for single line comments, and if a comment matches this regex then the comment appears as a "folder" in symbols provider and every symbol under the comment goes under the folder (until the next "folder" comment is found). By default this regex can be set to anything with all caps (something like `[A-Z]+`), to match the convention already out there. So the example above would give document symbols as:

```
file
    MAIN
        main
    MODEL
        Model
        init
    UPDATE
```

I would be happy to try and make this happen. Please let me know if something like this would be acceptable.

Thanks

**Comment by Razzeee** [comment]
Thanks for reaching out. I'm not too keen on adding more settings, as it makes maintaining and using the server harder. And I'm not sure the benefit of this feature is worth that.

I will post this in slack, to get some other opinions.

**Comment by bengolds** [comment]
I'd personally really appreciate this -- it'd make the outline much easier to work with. It would also help with navigating new files.

My 2 cents is not to have it be configurable, but to instead have a standard format and a `section` snippet in that format. 

Additionally, having it as a top-level fold wouldn't be so bad either; that way, the fully folded document would look like:

```
module Main exposing (..)

> -- MODEL

> -- UPDATE

> -- VIEW


```

**Comment by Kurren123** [comment]
@bengolds  I’m absolutely fine with no configuration And only top level. Anything to make longer files easier to navigate. 

Although I think code folding is a separate thing from the outline. I think one is the document symbol provider and one is the code folding provider.

**Comment by sentience** [comment]
I don't personally use the outline view, but I have no objection with this in principle. The `-- ALL CAPS SECTION NAME` is a pretty widespread community standard.

**Comment by Razzeee** [comment]
> Although I think code folding is a separate thing from the outline. I think one is the document symbol provider and one is the code folding provider.

Correct, if we implement this, we will not only have to check how the outline behaves now, but also how breadcrumbs and document symbols work. And if it's non problematic.

**Comment by pehota** [comment]
I am a heavy outline user (Vim + coc.nvim). In my opinion adding more lines of text in the outline window will unnecessarily clutter the space. If one knows what they're looking for it won't matter which `folder` it falls under. One would just type the name they want to jump to and be done with it.

**Comment by sentience** [comment]
@pehota If you're navigating by typing names and not looking at the panel anyway, does the clutter you describe matter? I wonder if users who are using the panel to browse for what they're looking for (because they _don't_ know the name) would find the structure more of a help than a hindrance.

**Comment by pehota** [comment]
@sentience what I meant by knowing what one is looking for is knowing if they’re looking for a view function, an update or main one, or a type. My experience shows that most devs name view functions with names starting with view, update functions with names starting with update. If I have to look for a view function in a file I am unfamiliar with I would either start typing view or render. Same goes for update functions and types (typing type lists all types). If we had to use the proposed functionality, devs would have to remember to put the functions under the correct section. Otherwise it would be pointless. This introduces one more thing a dev needs to remember and take care of. If this functionality gets introduced, it would be nice to have a way to turn it off too.

**Comment by Kurren123** [comment]
@pehota under that same argument, wouldn’t devs need to remember to pretend `update` to all their update functions etc? Often I put large helper functions near the update functions that use them which aren’t prefixed with `update`, which would be left out of your search. 

I agree I think there should be a way to turn it off. But I think if we can’t add any more settings to the language server then we should close this.

**Comment by Kurren123** [comment]
@pehota also another reminder that this won’t be just for `view` and `update` functions. Take [this](https://github.com/rtfeldman/elm-spa-example/blob/master/src/Author.elm) source file for example. He uses the headings `— FETCH`, `— FOLLOWING`, `— SERIALIZATION`. Again, functions under these headings have no specific prefix so they wouldn’t be searchable using your method unless you know what you’re looking for.

**Comment by Razzeee** [comment]
I'm going to close this, as I don't think we should do this. Feel free to use this issue to talk about in further.
