### ISSUE TITLE
Renaming a module can still result in a MODULE NAME MISMATCH error

### ISSUE THREAD

**Issue by phollyer** [elm-tooling/elm-language-server#265]
Behavior differs depending on the order that the module name and file name are changed.

## Expected Behavior
It should not matter whether the file name is changed before the module name, or the module name is changed before the file name. Behavior should be the same.

## Current Behavior
1. Changing the file name, and then changing the module name results in the changes being picked up ok.
2. Changing the module name, and then changing the file name result in the changes not being picked and the `MODULE NAME MISMATCH` error remains. 

## Possible Solution
Above my paygrade.

## Steps to Reproduce (for bugs)
1. Change the module name
2. Change the file name to match

## Context
A restart of Sublime is required for the changes to be picked up.

## Your Environment
* Version used: 0.0.1
* Editor used: Sublime Text 3.2.2 build 3211
* Environment name and version (e.g. node.js 5.4): node.js 10.8.0
* Operating System and version: OSX 10.15.3

**Comment by phollyer** [comment]
### Context (update)

Renaming the file name to something else, and then the module name to match gets the server back on track without needing to restart Sublime.

**Comment by phollyer** [comment]
Correction: It seems that once the server has got into a bit of a tizz that the only way to rectify is to restart Sublime.

Also, until restarted, non-existent modules (due to being renamed) are still displayed in the popup hints when typing in the `import ...` statement. 

So, if the module name is changed before the file name, the server seems to behave strangely until Sublime is restarted.

**Comment by Razzeee** [comment]
This should now work, if you use the rename on the module and the sublime client supports the needed capabilities. Can you retest this?

**Comment by Razzeee** [comment]
I'll close this for now, feel free to reopen.
