### ISSUE TITLE
Documentation for using elm-language-server with VSCode, sans elm-language-client-vscode

### ISSUE THREAD

**Issue by johncmunson** [elm-tooling/elm-language-server#266]
I've been having issues with [elm-language-client-vscode](https://github.com/elm-tooling/elm-language-client-vscode), and I recently opened up [this issue](https://github.com/elm-tooling/elm-language-client-vscode/issues/103).

I considered dropping down to this lower level library until the issue mentioned above is resolved, but the README seems to have incomplete documentation regarding VSCode integration.

It basically just assumes elm-language-client-vscode is working and refers you to that.

It would be nice to have docs explaining how to get elm-language-server up and running with VSCode. My use case is just to hold me over, but I'm sure other people have use cases as well.

**Comment by Razzeee** [comment]
I guess that would mean, that you need a generic lsp client, I don't think such an extension exists for vscode.

**Comment by johncmunson** [comment]
Ah, well that's a bummer. That's surprising, considering Microsoft invented LSP as a direct result of lessons learned building VSCode. Granted, I still know very little about LSP in general, so take anything I say with a grain of salt.

**Comment by Razzeee** [comment]
Well, I guess vscode "suffers" from always getting a first party vscode addon due to it being invented there? I guess nobody had a reason to create a generic implementation. :/
