### ISSUE TITLE
Problem with tree-sitter

### ISSUE THREAD

**Issue by Daniel-V1** [elm-tooling/elm-language-server#27]
Hi, I'm really excited about this thing because I love Elm, and I'd like to use it in my preferred environment, which is actually emacs. 

This may just be me being dumb, but I keep getting:

[Trace - 06:25:31 PM]
Received notification 'window/logMessage'.

Params: 
{
  "message": "Rebuilding tree-sitter for local Electron version",
  "type": 3
}

and then nothing after that. I've run npm install in the root directory, and in the client directory and server directory. Is there anything else that I need to do to get tree-sitter/the server to work? 

Thanks for this project, and thanks in advance for any help you can give me!

**Comment by Razzeee** [comment]
So you won't be able to use this client, did you try with something like https://github.com/emacs-lsp/lsp-mode ?

You may also need to switch the tree sitter implementation to the node and not electron version.

See this commit, as it talks about just that https://github.com/elm-tooling/elm-language-server/commit/a1d15e8f950faa74a8379eddb20d664e2a1b712b#diff-e8ca13a8bcbbbcab61976c9eaf3d00dd

**Comment by Daniel-V1** [comment]
Yep, was trying to add a client in the lsp-mode. 

Looks like that was it! I passed node in the initialization parameters and now the language server works! All I'm getting back currently is an error from elm-analyse about parsing the file, but hopefully I can work through that.

Thanks again!

**Comment by Razzeee** [comment]
If you figure it out, please send a PR with some instruction :)

**Comment by Daniel-V1** [comment]
It wound up being my short experience with elm lol. I didn't have a module declaration at the top of the file, and elm-analyse was very unhappy with that, but couldn't tell me why. Maybe I should open something there for better messaging, or perhaps a suggesting in that case. I got it all working now and its awesome! Thank you so much for this project!

**Comment by Razzeee** [comment]
Your welcome, it's still early development and hopefully only getting better.
