### ISSUE TITLE
Jump to module resolves to non-exposed library modules

### ISSUE THREAD

**Issue by BendingBender** [elm-tooling/elm-language-server#274]
When using the packages `elm/parser` and `cuducos/elm-format-number@8.1.1` (note the 8.1.1 here, the problem [was workarounded](https://github.com/cuducos/elm-format-number/issues/31) in 8.1.2), elm-ls resolves `import Parser` declarations as the non-exposed `Parser` module from `elm-format-number` instead of the publicly exposed `Parser` module from `elm/parser`.

## Expected Behavior
I expect elm-ls to resolve imported library packages only to packages that can actually be imported. In my example, the `Parser` package was not on the list of `exposed-modules` in the `elm-format-number`'s `elm.json`.

## Current Behavior
Currently, Cmd-click jumps to the non-exposed `Parser` package from `elm-format-number` and auto-completion only resolves the symbols from this private package instead of only considering the publicly exposed `Parser` package from `elm/parser`.

## Possible Solution
I suppose that the package resolution mechanism should filter out all identically-named packages from libraries that are not on the `exposed-modules` list.

## Steps to Reproduce (for bugs)
1. install both, `elm/parser` and `cuducos/elm-format-number` (< 8.1.2, 7.0.0 has the same issue)
2. import the parser module: `import Parser`
3. try to use auto-completion feature to resolve symboils from `elm/parser`'s `Parser` or jump to module functionality to jump to `elm/parser`'s `Parser`

## Context
Inconvenience to look up method names/definitions.

## Your Environment
* Version used: elmtooling.elm-ls-vscode@0.10.2
* Editor used: vscode 1.45.1
* Environment name and version (e.g. node.js 5.4): 10.20.0
* Operating System and version: Mac OS 10.14.6 (Darwin x64 18.7.0)

**Comment by Razzeee** [comment]
Agreed, seems like an oversight. I probably didn't parse `exposed-modules` as you suggest.
