### ISSUE TITLE
Looking for an elm client

### ISSUE THREAD

**Issue by markfirmware** [elm-tooling/elm-language-server#286]
I would like an elm client that demonstrates working with an lsp server. It does not need to do anything purposeful except demonstrate json rpc interactions with a server.

Perhaps there is an elm app that is used to test the server?

Thanks, Mark.

**Comment by Razzeee** [comment]
Can I ask, what your trying to do? We only have a typescript client. But I guess you could forward those calls via ports.

**Comment by markfirmware** [comment]
I am looking for an elm 0.19.1 example that calls json rpc. I know that lsp uses that format so I thought maybe your language server might have an elm client even just for testing, or that you might know of an example.

The target json rpc server is a microcontroller using json rpc over a serial port that is then bridged to a socket.

**Comment by Razzeee** [comment]
There was an elm 0.18 package https://package.elm-lang.org/packages/martin-volf/elm-jsonrpc/1.0.0 and https://github.com/ionif/elm-chorus is in the process of talking with jsonrpc, not sure how helpful that will be at this moment.

**Comment by markfirmware** [comment]
Ok, thanks very much.
