### ISSUE TITLE
Reduce weight of auto-import suggestions

### ISSUE THREAD

**Issue by sparksp** [elm-tooling/elm-language-server#287]
## Expected Behaviour

If an already imported module provides a function (without `exposing` it) then the qualified name should be suggested before the auto-import suggestions.

If the value being suggested has already been used elsewhere in the file I expect the top suggestion to match that use. For example, if I have already used `Set.member` in the file then typing `member` should present `Set.member` above the auto-import suggestion (assuming that `member` has not been exposed on import).

## Current Behaviour

Continuing with the previous example, if there is no `member` in scope (declared or exposed on import) then the top suggestion(s) for "member" are to auto-import it from various modules; the available fully-qualified suggestions then follow. In the case of `member` there's up to 6 possible auto-imports to skip over.

If `member` has been exposed on import already then calling it is the top suggestion, followed by auto-import suggestions for the remaining modules (up to 5), and finally the fully-qualified suggestions.  This seems to suggest an additional problem, since you wouldn't want to auto-import `member` from more than one module in the same file.

## Possible Solution

Suggestions should favour things that are already available over auto-import, for example:

1. In-scope named value (let value, case value, function parameter, top-level declaration, etc.)
2. Exposed value from imported module (e.g., `member` from `import Set exposing (member)`)
3. Qualified values from imported module (e.g., `Dict.member` from `import Dict` and `List.member` from default `import List`)^
4. Auto-import suggestions

^ Further weighting could be applied to (3) based on scope and whether the qualified value appears in the file already; for example showing `List.member` above `Dict.member` if `List.member` has already been used in the file; or showing the best match if we're following `something |>`.

## Context

I've been writing [elm-review] tests where I `import Review.Test` and then fully qualify function calls, including `Review.Test.expectErrors`, `Review.Test.atExactly` and `Review.Test.whenFixed`. Previously it was sufficient to start typing `expectErrors` or `atExactly` and accept the top suggestion to get the fully qualified name.

When importing I typically only expose types from modules that match the module name, and fully-qualify everything else, so I'm unlikely to want auto-import to expose functions for me.  For example I `import Html exposing (Html)` and then use `Html.div` later; or `import Review.Rule as Rule exposing (Rule)` and use `Rule.*` later.

[elm-review]: https://package.elm-lang.org/packages/jfmengels/elm-review/latest/

## Your Environment

* Version used: elmtooling.elm-ls-vscode 1.0.0
* Editor used: VSCode 1.45.1
* Operating System and version: macOS Catalina 10.15.5

**Comment by Razzeee** [comment]
@jmbockhorst

**Comment by jmbockhorst** [comment]
Thanks for the detailed feedback! After using it the last few days, I have also noticed that the sorting needs some work. I will try to work on improving this in the next week. I definitely want this feature to be based on what is the most productive for the average user, so the feedback helps a lot.

**Comment by Razzeee** [comment]
Should we close this for now and maybe reopen it if the next release doesn't address it? (the changes have been merged)

**Comment by jmbockhorst** [comment]
Yeah I think we can close it as those changes should’ve covered most of it.

**Comment by sparksp** [comment]
This is much improved now, thank-you so much! I'm getting much fewer accidental imports with the most recent version.
