### ISSUE TITLE
Auto complete for external packages (including core) have stopped working for me since the release of 1.0.0

### ISSUE THREAD

**Issue by Kurren123** [elm-tooling/elm-language-server#288]
[Simple sample repository](https://github.com/Kurren123/elm-vscode-bug). 

I clone this, run `elm make` and it compiles just fine. Autocomplete works fine for functions of modules defined in this project, but not for functions in other modules such as `Html`:

![image](https://user-images.githubusercontent.com/3525980/84401586-5a660d80-abfb-11ea-94de-25dea777b703.png)

## My Environment
* Version used: 1.0.0
* Editor name and version: VSCode 1.46
* Environment name and version:

![image](https://user-images.githubusercontent.com/3525980/84402175-07d92100-abfc-11ea-94a1-6dc74c55b9a9.png)

* Operating System and version: Windows 10 Enterprise 64 bit

Please let me know if there is any more info you need

**Comment by Kurren123** [comment]
@Razzeee  Thanks for the update but the error seems like it's still there even after updating the extension to v1.0.1 and restarting vscode. 

![image](https://user-images.githubusercontent.com/3525980/84494674-d581ff00-aca1-11ea-915f-4f65c450f0cb.png)

There are more autocomplete suggestions than before so something did change, but still none from `Html`.

**Comment by Razzeee** [comment]
Seems fine to me on linux, will test on windows shortly

![image](https://user-images.githubusercontent.com/5943908/84495134-f3a02d00-acaa-11ea-84c4-cb0303a83759.png)

**Comment by Razzeee** [comment]
It's a problem on windows due to file paths being handled wrong. Sorry, will push another update :)

**Comment by Kurren123** [comment]
No problem at all, I'm just grateful for the bugfix
