### ISSUE TITLE
Errors don't disappear when last error is from elm-make

### ISSUE THREAD

**Issue by bengolds** [elm-tooling/elm-language-server#29]
Repro steps:
1. Get a file to have only one `elm-make` error and no `elm-analyse` warning.
2. Fix the `elm-make` error.

Expected:
No errors reported.

Observed:
Last elm-make error still appears in diagnostics.

This doesn't happen if the last error is an `elm-analyse` warning.

(Note: observed in both VSCode and vim)

**Comment by Razzeee** [comment]
Should be addressed now.
