### ISSUE TITLE
Coc.nvim "Server languageserver.elmLS failed to start"

### ISSUE THREAD

**Issue by scottbass47** [elm-tooling/elm-language-server#306]
I'm trying to use the elm language server with Neovim and Coc. However, everytime I open an elm file I get this error message: `[coc.nvim] Server languageserver.elmLS failed to start: Launching server "languageserver.elmLS" using command elm-language-server failed.`

I have installed the elm language server with the command: `npm i -g @elm-tooling/elm-language-server`. My `:CocConfig` has the following settings for the elm LS:
```
"elmLS": {
  "command": "elm-language-server",
  "filetypes": ["elm"],
  "rootPatterns": ["elm.json"],
  "initializationOptions": {
    "elmAnalyseTrigger": "change"
  },
  "trace.server": "verbose"
}
```
Here is my `:CocInfo`
```
## versions

vim version: NVIM v0.5.0-175-g525bb1b55
node version: v14.2.0
coc.nvim version: 0.0.78
coc.nvim directory: C:\Users\Scott\AppData\Local\nvim\plugged\coc.nvim
term: undefined
platform: win32

## Output channel: prettier


## Output channel: languageserver.elmLS

[Error  - 6:37:41 PM] Starting client failed 
Launching server "languageserver.elmLS" using command elm-language-server failed.
```
I don't know how to debug this because there is so little output even with `"trace.server": "verbose"` on in my config. 

## Expected Behavior
The language server should start successfully.

## Current Behavior
The language server is failing to start.

## Steps to Reproduce (for bugs)
1. Install Neovim and CoC (all installations on Windows machine)
2. Run `npm i -g @elm-tooling/elm-language-server`
3. Add elm LS to coc config (see above for config)
4. Try and open elm file

## Your Environment
* Version used: 1.10.0
* Editor used: NVIM v0.5.0-175-g525bb1b55
* Environment name and version (e.g. node.js 5.4): node.js v14.2.0
* Operating System and version: Windows 10 Version 10.0.18363 Build 18363

**Comment by scottbass47** [comment]
I don't know if this is a fix for everyone, but for me changing the command from `elm-language-server` to `elm-language-server.cmd` did the trick. I have a hunch this may because I'm using PowerShell on Windows, but I'm not sure.

**Comment by Razzeee** [comment]
Good find, pretty sure your correct. Should we add this to the readme? Or should it be in the readme of https://github.com/elm-tooling/elm-vim ?

**Comment by scottbass47** [comment]
I think it should be added to the readme here because it's not necessarily a vim issue. Any text editor that launches the server like coc does would have the same issue I'd think.
