### ISSUE TITLE
Trouble starting with Spacemacs Elm layer

### ISSUE THREAD

**Issue by jeongsoolee09** [elm-tooling/elm-language-server#309]
I would first like to thank you for providing this implementation!  However, I am having a little trouble with my Emacs setting things up with this language server.

## Expected Behavior

Every time I create an .elm file, the language server starts up and starts working (provides autocompletion and syntax/type checking).

## Current Behavior

I always get an error message in the minibuffer every time I type something, saying
```
LSP::Error from the Language Server: Request testDocument/codeAction failed with message: No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm (Internal Error)
```

## Steps to Reproduce (for bugs)

1. `npm install --global elm`
2. `npm install -g elm-oracle`
3. `npm install @elm-tooling/elm-language-server`
4. `npm install -g elm elm-test elm-format`
5. Create a directory `Code/Elm` under the home directory
6. `cd` to the said directory and `elm init`
7. `cd` to `src` and create an `hello_world.elm`
8. lsp-mode asks me if it should import the root directory `~/Code/Elm/src`, answer `y`
9. I get an error message in the minibuffer every time I type something, saying
```
LSP::Error from the Language Server: Request testDocument/codeAction failed with message: No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm (Internal Error)
```

So I attempted to add the directory to the workspace by calling `lsp-workspace-folders-add`, but to no avail.

## Context

Here are the contents of my `*lsp-log*` buffer:

```
Command "/usr/local/bin/elm-language-server --stdio" is present on the path.
Command "/usr/local/bin/elm-language-server --stdio" is present on the path.
Found the following clients for /Users/{username}/Code/Elm/src/hello_world.elm: (server-id elm-ls, priority -1)
The following clients were selected based on priority: (server-id elm-ls, priority -1)
Command "/usr/local/bin/elm-language-server --stdio" is present on the path.
Command "/usr/local/bin/elm-language-server --stdio" is present on the path.
Found the following clients for /Users/{username}/code/Elm/src/hello_world.elm: (server-id elm-ls, priority -1)
The following clients were selected based on priority: (server-id elm-ls, priority -1)
Loading Elm tree-sitter syntax from ../../../../../usr/local/lib/node_modules/@elm-tooling/elm-language-server/out/tree-sitter-elm.wasm
No elm.json found. Please run 'elm init' in your main directory.
No elm.json found
Diagnostics were requested due to a file change
No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm
Notification handler 'textDocument/didChange' failed with message: No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm
Diagnostics were requested due to a file open or save
No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm
Diagnostics were requested due to a file change
No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm
Notification handler 'textDocument/didChange' failed with message: No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm
Diagnostics were requested due to a file change
No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm
Notification handler 'textDocument/didChange' failed with message: No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm
Diagnostics were requested due to a file change
No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm
Notification handler 'textDocument/didChange' failed with message: No Elm workspace contains /Users/{username}/code/Elm/src/hello_world.elm
```

## Your Environment

* Version used: 1.10.0
* Editor used: Emacs 26.3 with latest Spacemacs on develop branch
* Environment name and version (e.g. node.js 5.4): node.js v14.8.0 with npm version 6.14.7
* Operating System and version: macOS Catalina

**Comment by Razzeee** [comment]
Can you try to setup the folder above?

**Comment by jeongsoolee09** [comment]
@Razzeee By 'setting up the folder', do you mean running `elm init`? I have done it already.

**Comment by Razzeee** [comment]
No, sorry

> lsp-mode asks me if it should import the root directory ~/Code/Elm/src, answer y

I think this is wrong and it needs to be `~/Code/Elm` as your elm.json is in that folder

**Comment by jeongsoolee09** [comment]
Well, now I'm trying to add `~/Code/Elm` to the workspace via `M-x lsp-workspace-folders-add`, but lsp-mode keeps complaining that `No workspace contains ~/Code/Elm/hello_world.elm`. I tried deleting the language server files under `~/.emacs.d/.cache/lsp/npm/@elm-tooling`, in hope of starting afresh by reinstalling the server, but it did no help :(

**Comment by jeongsoolee09** [comment]
I finally got this working by first doing `M-x lsp-workspace-folders-remove`, closing the elm file, and reopening it. Now it works fine. I'm closing this thread!

**Comment by Razzeee** [comment]
Great, do you feel like there is anything we should improve in the docs?

**Comment by jeongsoolee09** [comment]
Well, a couple of things for anyone using (Spac)emacs:
1. You need to `cd` to the project root directory and run `elm init`, which gives you `elm.json` with a `src` folder. Put the .elm files under the `src` directory and import the project root directory, not the path with `src` at the end.
2. If you persistently get the `No elm workspace contains ...` error, first `M-x lsp-workspace-folders-remove` the current directory and start from step 1.

This essentially simply summarizes the journey I went through, but it might definitely help others who might be struggling.
