### ISSUE TITLE
language-server doesn't provide Content-Length header

### ISSUE THREAD

**Issue by romariolopezc** [elm-tooling/elm-language-server#337]
This error just started happening using Neovim Coc.nvim. According to [this](https://github.com/neoclide/coc.nvim/issues/1327), this is not a bug in coc.nvim but in the language server. Its supposed that the language server implemens this header

I searched the specification https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/ and it says something about the content-length header

## Current Behavior

Uncaught exception logged in coc.nvim
![image](https://user-images.githubusercontent.com/6199588/95285534-a2eaac00-0826-11eb-9865-9794cfee08e7.png)

## Steps to Reproduce (for bugs)

1. Update to latest Coc.nvim
1. Install elm-language-server
1. Open an elm project

## Context

Is hard to write when this is popping up in each keystroke

## Your Environment

```
vim version: NVIM v0.5.0-590-gb39edb5b6
node version: v10.17.0
coc.nvim version: 0.0.79-b1288b0de4
coc.nvim directory: /home/rlopez/.local/share/nvim/plugged/coc.nvim
term: alacritty
platform: linux
```

**Comment by Razzeee** [comment]
A new version fixing this was released.
