### ISSUE TITLE
Support cancellation for requests

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-server#351]
Using cancellation tokens we can cancel requests if they are no longer needed. Since most code is synchronous, we will need to use file based cancellation pipes (this is was Typescript does) added here: https://github.com/microsoft/vscode-languageserver-node/pull/587.

**Comment by Razzeee** [comment]
Need to move to the next branch of language server node for this

**Comment by jmbockhorst** [comment]
Yes, and I've started using the `@next` release in my work in progress.
