### ISSUE TITLE
Vscode: Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by whitecolor** [elm-tooling/elm-language-server#352]
There is an error that happens when opening elm file:
```
[Error - 10:22:43 PM] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'uri' of undefined
```

![image](https://user-images.githubusercontent.com/736697/97737339-acea8c80-1afe-11eb-8d32-c16bc9b6a184.png)

## Possible Solution

Here:

https://github.com/elm-tooling/elm-language-server/blob/87d4be08b9c5f029379f7d897f0935af70ba9825/src/providers/astProvider.ts#L48

and 

https://github.com/elm-tooling/elm-language-server/blob/87d4be08b9c5f029379f7d897f0935af70ba9825/src/providers/astProvider.ts#L58

`params` happen to be of another type do not contain `textDocument` but `document` field with another structure.

## Context
Latest VScode and Insiders.

**Comment by Augustin82** [comment]
Might be the same problem as https://github.com/elm-tooling/elm-language-server/issues/348 ? However, this wouldn't explain why it seems to occur "randomly", right?

**Comment by whitecolor** [comment]
Well no, for me in the simplest setup it happens always as new file opens.

**Comment by Razzeee** [comment]
That's correct, see the merge request I attached
