### ISSUE TITLE
Missing Gizra/elm-debouncer package and server fails to start

### ISSUE THREAD

**Issue by korsmakolnikov** [elm-tooling/elm-language-server#359]
Opening a file on emacs the language server crash with this error on the language server messages buffer
```
Error parsing files for /home/blacksheep/www/mario/apps/presentation/assets/elm.json:
Error: ENOENT: no such file or directory, open '/home/blacksheep/.elm/0.19.1/packages/Gizra/elm-debouncer/2.0.0/elm.json'
```

I'm very new to elm but seems I miss that package on my system so it cannot parse elm.json, but I found out elm doesn't install the packages globally so... Can you help me? 

I'm using doom with emacs 27 and elm is 0.19.1. But I think this is very unrelated to doom emacs since I could get it to work on vim+coc neither.

**Comment by Razzeee** [comment]
Run "elm make src/Main.elm" once. Or save that file with the LS active

**Comment by Razzeee** [comment]
Did this help?
