### ISSUE TITLE
Build and lint with travis

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#36]

**Comment by buinauskas** [comment]
I'd like to help with this if you're willing to give a more details.

**Comment by Razzeee** [comment]
Well I started with here https://github.com/elm-tooling/elm-language-server/pull/37

But I think it's failnig due the the navtive builds and me not including clang etc.  like I do here https://github.com/Razzeee/tree-sitter-elm/blob/master/.travis.yml

It should get way easier when we are able to switch to the wasm version of tree sitter. But it's blocked until somebody tackles https://github.com/tree-sitter/tree-sitter/issues/349
