### ISSUE TITLE
"Create local function" action doesn't show up when asking code actions on a line

### ISSUE THREAD

**Issue by bengolds** [elm-tooling/elm-language-server#377]
Coc in Neovim has three functions for asking for code actions: 
`coc-codeaction-selected` -- this fetches code actions for a selected area (a character, a word, a paragraph)
`coc-codeaction-line` -- this fetches code actions for a given line
`coc-codeaction` -- this fetches code actions for the whole file

`coc-codeaction-line` and `coc-codeaction` seem to show most code actions, with the exception of "create local function":
<img width="935" alt="Screenshot 2020-11-25 at 09 24 32@2x" src="https://user-images.githubusercontent.com/446007/100261751-11cbb380-2f00-11eb-8707-614604eaaab5.png">
(this is `coc-codeaction`, or actions for the whole file)

`coc-codeaction-selected` on _just_ the function that was wrong shows the "create local function" code action.
<img width="428" alt="Screenshot 2020-11-25 at 09 25 14@2x" src="https://user-images.githubusercontent.com/446007/100261863-39228080-2f00-11eb-8694-74835cdef465.png">

From [this](https://gitter.im/neoclide/coc.nvim?at=5fbe19286a738b71d3612cd8) conversation in the Coc gitter, it appears as though the only difference is in the ranges that the LSP sends to the language server. So, `elm-language-server` may only be sending that action back for very specific ranges.

**Comment by Razzeee** [comment]
There's a high likelyhood that https://github.com/elm-tooling/elm-language-server/issues/377 also fixes this.
