### ISSUE TITLE
Vim and Coc install instructions not working

### ISSUE THREAD

**Issue by bigardone** [elm-tooling/elm-language-server#38]
Hi! I'm trying to use it with NeoVim and Coc, but it doesn't work.
Here is the error that pops up whenever I open an Elm file:

```
[coc.nvim] Server elm failed to start: Command "elm-ls" of languageserver.elm is not executable: Error: not found: elm-ls
```

And here is the Coc configuration file:

```json
{
  "suggest.minTriggerInputLength": 1,
  "languageserver": {
    "elm": {
      "command": "elm-ls",
      "args": ["--stdio"],
      "filetypes": ["elm"],
      "rootPatterns": ["elm.json"],
      "initializationOptions": {
        "runtime": "node",
      }
    }
  }
}
```

It doesn't find the `elm-ls` executable, but there are no standalone install instructions. What am I missing?
Thanks in advance :)

**Comment by Razzeee** [comment]
Please try again, as we merged https://github.com/elm-tooling/elm-language-server/pull/40 now. There might still be a problem after that.

**Comment by bigardone** [comment]
Thanks for the quick response :)
After syncing, compiling and linking, I'm now able to make it run, getting a different error though:

```
2019-05-27T15:26:19.788 ERROR (pid:89280) [language-client-client] - The languageserver.elm server crashed 5 times in the last 3 minutes. The server will not be restarted.
2019-05-27T15:26:19.789 INFO (pid:89280) [services] - elm state change: starting => stopped
2019-05-27T15:26:19.834 INFO (pid:89280) [services] - highlight server state change: starting => running
2019-05-27T15:26:19.839 INFO (pid:89280) [services] - service highlight started

## Output channel: languageserver.elm

Invalid option `--stdio'

Usage: elm-language-server [-l|--server-log-file LOGFILE]
                           [--session-log-file SESSIONLOGFILE]
  A Language Server Protocol Implementation for the Elm Language (see
  https://elm-lang.org)
[Info  - 15:26:19] Connection to server got closed. Server will restart.
[Error  - 15:26:19] elm-language-server exited with code: 1
Invalid option `--stdio'
```

It seems like the `--stdio` argument is not supported. If I remove it from Coc's config, it doesn't show any more errors, although I'm not sure if it works as it should because I'm not able to go to definitions, etc...

**Comment by andys8** [comment]
@bigardone Hey, based on the output about logiles, I'd say you could be using accidentally a completely different language server implementation: https://github.com/elm-tooling/elm-language-server-haskell/blob/0f08419eeec90709763a3f53d31cfb2cb2a6b099/app/Main.hs

**Comment by bigardone** [comment]
@andys8 you were right, the executable was linked to the older version. I just deleted it and created the link again, and it's working like a charm!
Thank you very much for the support guys 🙌
