### ISSUE TITLE
Allow renaming type variables

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-server#404]
Need to add logic in `references.ts` for type variables references.

**Comment by Razzeee** [comment]
Can you give an example, I'm unsure what this was.

**Comment by jmbockhorst** [comment]
You should be able to rename the `a` type variable.

```elm
func : a -> a -> a
func x y =
   ...
```

**Comment by Razzeee** [comment]
We seem to already have a problem with goto definition (which is the first occurence of this I guess)

https://github.com/elm-tooling/elm-language-server/commit/e576a3bd2b51671665bf795422e2edbcd8359e75

Even when I add a binding to it, it overlaps with "FunctionParameter" in a non trivial way (at least for me)
