### ISSUE TITLE
Error doesn't show up in file until add/remove import

### ISSUE THREAD

**Issue by bengolds** [elm-tooling/elm-language-server#448]
I've run into a situation where certain errors don't show up in a file if there are errors in another file that isn't even imported. This is my best attempt at a minimal reproduction; not sure if it happens for other classes of error, or there are other ways to get the errors to show up again.

Here's a video showing the behavior:
https://cln.sh/lL9KZz

Attached is the project I used to generate that file.
[error-1-no-error.zip](https://github.com/elm-tooling/elm-language-server/files/5817098/error-1-no-error.zip)

This is on a Mac, in Neovim, on commit ab61c610f31d29f0905874a2a7658140d80c5d41 .

**Comment by jmbockhorst** [comment]
Are these errors happening after you save a file? Can you verify the errors that `elm make {file_you_saved}` gives you are the same as when you hit save in the editor?

**Comment by bengolds** [comment]
The errors don't show up in `src/Main.elm` when I save the file still. If I run `elm-make src/Main.elm`, I get the error I would expect:
<img width="670" alt="Screenshot 2021-01-21 at 11 26 53@2x" src="https://user-images.githubusercontent.com/446007/105401953-a0e10900-5bdb-11eb-8f44-2d6d6ce7e6f1.png">


Does it not repro for you?

**Comment by jmbockhorst** [comment]
If I save `Main.elm` the error from the compiler shows up. Then if I start typing the import, the type inference errors take over, and we don't currently have an error for mismatched function and annotations (but we should track it here: https://github.com/elm-tooling/elm-language-server/issues/406), so the error goes away. If I hit save again, the compiler gives the error again. 

Is something different happening for you?

**Comment by bengolds** [comment]
Yep -- as you can see in the [video linked](https://cln.sh/lL9KZz), the error doesn't appear on `Main.elm` until some arcane series of "imports" is done. Whenever I type `:w` in that video, I'm saving the file.

**Comment by jmbockhorst** [comment]
I see now. That's a weird one. Basically, `elm make` diagnostics are just not showing up sometimes? And those have nothing to do with type inference, so I'm not sure what could be going on. Can you try `master`?

**Comment by bengolds** [comment]
Current status on `master`: it requires two saves to show the error.

Uploading Screenshot 2021-01-21 at 17.52.42.mp4…

**Comment by jmbockhorst** [comment]
Is there anything interesting in the logs when you save and it doesn’t show anything?

**Comment by bengolds** [comment]
Nothing in particular -- even with `elmLs.trace.server: "verbose"`, I don't get hardly any information. Not sure if I'm doing something wrong...

```
## Log of coc.nvim

2021-01-22T17:20:26.929 INFO (pid:5210) [services] - registered service "languageserver.elmLS"
2021-01-22T17:20:26.975 INFO (pid:5210) [services] - registered service "eslint"
2021-01-22T17:20:27.129 INFO (pid:5210) [plugin] - coc.nvim 0.0.80-50544406f0 initialized with node: v12.18.1 after 270ms
2021-01-22T17:20:27.140 INFO (pid:5210) [watchman] - watchman watching project: /Users/bengold/Downloads/elm-ls-demo
2021-01-22T17:20:30.370 INFO (pid:5210) [services] - elmLS state change: stopped => starting
2021-01-22T17:20:30.377 INFO (pid:5210) [language-client-index] - Language server "languageserver.elmLS" started with 5239
2021-01-22T17:20:31.376 INFO (pid:5210) [services] - elmLS state change: starting => running
2021-01-22T17:20:31.381 INFO (pid:5210) [services] - service languageserver.elmLS started
2021-01-22T17:20:32.391 INFO (pid:5210) [completion-complete] - Results from: around,languageserver.elmLS-1
2021-01-22T17:20:32.778 INFO (pid:5210) [attach] - receive request: CocAutocmd [ 'BufWritePre', 1 ]
2021-01-22T17:20:34.914 INFO (pid:5210) [attach] - receive request: CocAutocmd [ 'BufWritePre', 1 ]
2021-01-22T17:20:38.200 INFO (pid:5210) [attach] - receive notification: showInfo []
```

**Comment by bengolds** [comment]
Okay, better now -- I realized that the way to get logs from `Coc` has changed. I've attached the logs.

[logs.txt](https://github.com/elm-tooling/elm-language-server/files/5859456/logs.txt)


I also looked at them in [LSP Inspector](https://github.com/microsoft/language-server-protocol-inspector) (let me know if you have trouble getting it running), I see this at the bottom of the logs. It strangely seems to send the error, and then send a list of empty errors.
<img width="718" alt="Screenshot 2021-01-22 at 17 44 12@2x" src="https://user-images.githubusercontent.com/446007/105564988-74131b80-5cd9-11eb-81e8-f949acf12157.png">

**Comment by Razzeee** [comment]
There's a chance, that this might have also been caused by the parser getting stuck in some circumstances, so we should re-test after landing https://github.com/elm-tooling/elm-language-server/pull/528

**Comment by Razzeee** [comment]
@bengolds could you give master a quick spin now?

**Comment by bengolds** [comment]
It looks good!

**Comment by Razzeee** [comment]
Thank you
