### ISSUE TITLE
Linked editing for function name and type annotation breaks if erasing the whole name

### ISSUE THREAD

**Issue by lydell** [elm-tooling/elm-language-server#452]
Put the cursor at the end of “view”, press backspace 4 times and write “show”.

In the below examples I worked on the `view =` line, but it happens when on the `view :` line as well.

```elm
view : Html msg
view =
```

## Expected Behavior

```elm
show : Html msg
show =
```

## Current Behavior

```elm
 : Html msg
show =
```

Once you’ve backspaced the word completely it’s like the other cursor disappears.

## Possible Solution

Worst case it’s a language server protocol / VSCode limitation.

## Context

This happens to Vim users. Put the cursor anywhere inside “view” and then press `ciw` (change inside word). That removes the word and puts you insert mode, letting you type a new word. So `ciwshow<esc>` changes the word to “show” for example.

## Your Environment

* Version used: The one that comes with 2.0.0 of the VSCode extension
* Editor used: VSCode
* Environment name and version (e.g. node.js 5.4): VSCode 1.52.1
* Operating System and version: macOS Big Sur 11.1

I love the new version btw!

**Comment by Razzeee** [comment]
I think the protocol allows for this. It's just hard for us to keep context. Played a bit with a fix, but wasn't happy.
