### ISSUE TITLE
Remove the `file` root of the outline view

### ISSUE THREAD

**Issue by laurentpayot** [elm-tooling/elm-language-server#458]
The `file` root of the outside view is annoying as it is always present and hides all the useful information when `Collapse All` is clicked.
For instance the outline view of Typescript files does not have a `file` root and show directly the types, functions and variables, even when `Collapse All` is clicked. The same behavior should be expected for any language.

By the way thank you so much for this plugin, it made me go back to VSCode :smiley:

**Comment by jmbockhorst** [comment]
Closed in #460.
