### ISSUE TITLE
"Module Not Found" errors for test dependencies

### ISSUE THREAD

**Issue by SidneyNemzer** [elm-tooling/elm-language-server#467]
## Expected Behavior
Test dependencies are recognized in tests

## Current Behavior
When I save, modules from `elm-explorations/test` like `Expect` and `Test` are underlined with `MODULE NOT FOUND`, but type inference and go-to-definition work fine.

<details>
<summary>(expand for full error)</summary>

```
MODULE NOT FOUND - You are trying to import a `Expect` module:

3| import Expect
          #^^^^^^#
I checked the "dependencies" and "source-directories" listed in your elm.json,
but I cannot find it! Maybe it is a typo for one of these names?

#    Codec
    Dict
    Ease
    Set#

#Hint#: If it is not a typo, check the "dependencies" and "source-directories" of
your elm.json to make sure all the packages you need are listed there!
```
</details>

VSCode attributes the message to `Elm`, while other errors come from `ElmLS` so perhaps part of the plugin is running the regular Elm compiler? Bit of a shot in the dark, but I figured I would mention this just in case.

<details>
<summary>(expand for image)</summary>

![image](https://user-images.githubusercontent.com/21203108/105320201-c0941500-5b7a-11eb-868a-1a0ec2e51e6e.png)

</details>

## Steps to Reproduce

I followed your advice in elm-tooling/elm-language-client-vscode#105 and tested with https://github.com/rtfeldman/elm-spa-example. It looks like the tests aren't actually updated to Elm 0.19 but I see the same behavior anyway. I opened a new issue since 2.0 was a major update for the VSCode plugin.

1. Clone https://github.com/rtfeldman/elm-spa-example
2. Open `tests/RoutingTests.elm`
3. Save the file to trigger the plugin
4. Notice `import Expect` and `import Test` are marked as missing modules. However type inference (on hover) and go-to-definition work as expected on symbols in the file (including the module names that are 'missing').

## Your Environment
* Version used: 2.0.0
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.52.1
* Environment name and version (e.g. node.js 5.4): Node 12.19.0
* Operating System and version: Windows 10

## Other

In general the 2.0 update and type inference has been awesome!

**Comment by jmbockhorst** [comment]
You are correct. This is coming from the compiler itself.

**Comment by jmbockhorst** [comment]
I have verified that this is a Windows only bug due to: https://github.com/elm-tooling/elm-language-server/blob/e7bff3304e6da4cb947d179d9a86f8e5a0f167fc/src/util/elmUtils.ts#L59

**Comment by SidneyNemzer** [comment]
Thanks for the quick response and fix!
