### ISSUE TITLE
In version 2.0.0, returning lambda from the `case` block is reported as Parsing error.

### ISSUE THREAD

**Issue by shamansir** [elm-tooling/elm-language-server#473]
Half of the body of the proper Elm file is reported as Parsing Error in version 2.0.0. The code in the file is marked as an error and marks as erroneous all the files which use this module. When I edit and save this file, the error disappears for some time, but then gets back again when I edit other files.

## Expected Behavior
The parsing error shouldn't be produced. Other proper files shouldn't be affected

## Current Behavior
This is considered as an error by the plugin:

```elm
flipBy : Flip -> Plane a -> Plane a
flipBy how (Plane (width, height) _ as plane) =
    plane |>
        transform
            (case how of
                Horizontal -> \(x, y) -> (width - 1 - x, y)
                Vertical -> \(x, y) -> (x, height - 1 - y))
```

While this isn't:

```elm
flipBy : Flip -> Plane a -> Plane a
flipBy how (Plane (width, height) _ as plane) =
    plane |>
        transform
            (\(x, y) -> (width - 1 - x, y))
```

## Steps to Reproduce (for bugs)
Source code, if would be needed: https://github.com/shamansir/kvant/blob/c8a09ed88c81c894832bb7012b6a4bc3187633b5/src/Kvant/Plane.elm

## Your Environment

* Version used: v2.0.0, Elm v0.19.1
* Editor name and version (e.g. VSCode 1.36.1): 1.52.1
* Environment name and version (e.g. node.js 5.4): node v12.16.1, 
* Operating System and version: macOS Big Sur, 1.11

**Comment by jmbockhorst** [comment]
Running `elm-format` formats the case like this and the parsing error goes away:
```elm
(case how of
    Horizontal ->
        \( x, y ) -> ( width - 1 - x, y )

    Vertical ->
        \( x, y ) -> ( x, height - 1 - y )
)
```

**Comment by Razzeee** [comment]
Yeah, expected that, just didn't have time to run elm format yet

**Comment by Razzeee** [comment]
Problem is the `()` around case, we need the new line at the end of the case. So either putting it in the next line or removing the braces is what gets rid of this.

**Comment by Razzeee** [comment]
https://github.com/elm-tooling/tree-sitter-elm/pull/74
Should help fix the error happening in the first place - but we still prefer you to use elm-format ;)
