### ISSUE TITLE
Handle kernel modules

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-server#475]
We should handle kernel modules without just throwing errors. Possibly we could even parse the js files to have go to definitions. We also need to check how the compiler handles them with type inference.

**Comment by harrysarson** [comment]
So the MVP as far as kernel modules goes is:

1. Do not emit an error for imports that start `Elm.Kernel.` (e.g. ![image](https://user-images.githubusercontent.com/16308754/105579471-c8240b80-5d7e-11eb-8fbf-e95fda5e3054.png))
2. Do not emit "no definition found" errors for things like `Elm.Kernel.XXX.yyy` where there is an `import Elm.Kernel.XXX` at the top of this file. ![image](https://user-images.githubusercontent.com/16308754/105579523-26e98500-5d7f-11eb-9b2c-33ac82f73571.png)

This would leave a large number of false negatives but this has precedent as `elm make` does not emit errors for many issues relating to kernel code (missing imports, missing modules, etc).
