### ISSUE TITLE
Tree sitter parser get stuck in invalid state

### ISSUE THREAD

**Issue by jmbockhorst** [elm-tooling/elm-language-server#484]
Sometimes the parser can get in an invalid state and and it gets stuck in an infinite loop. Not easily reproducible, but it seems to only happen on Windows for me.

**Comment by Razzeee** [comment]
If it's really just windows, line endings are  immediately a suspect.

Anyway, it's going to be a bug in the c++ parser.

**Comment by jmbockhorst** [comment]
It could still be a bug here. I've had this happen before when we use an old tree after a new one is parsed.

**Comment by jmbockhorst** [comment]
Yes, it sounds similar.

**Comment by matheus23** [comment]
I'm having issues with the language sever making my fans spin and using 100% of one core constantly.
As soon as I kill the process, a new one starts and makes my fans spin again :( I feel powerless here :smile: 

I'm on Arch Linux, though, so might not actually be related. Can I help you debug this somehow?
From a first glance, there's nothing suspicious in the (set to verbose) sever logs, but I'll investigate further.

**Comment by Razzeee** [comment]
Did you test this with an open source project or the spa-example in the bast case?

**Comment by matheus23** [comment]
> Did you test this with an open source project or the spa-example in the best case?

Nope! Not yet. But I'm pretty sure I can reproduce it with any elm codebase, I'll take a look!

I created a `.cpuprofile` and looked at it in the chrome dev tools profiler. 99% of the time is spent on `(program)`. According to google this means it's most likely native code. Which leads me to believe this has something to do with tree sitter parsing indeed.

I found this issue about infinite loops in tree sitter, maybe it's relevant/related?

https://github.com/tree-sitter/tree-sitter/issues/288

**Comment by matheus23** [comment]
Oh! I **can't** reproduce this with `elm-spa-example`!

I have an idea, though: In almost all projects I'm generating elm code with https://github.com/monty5811/postcss-elm-tailwind or something similar.

And as far as I know, when you generate files with node, it includes line feeds!

Checking this hypothesis.

**Comment by matheus23** [comment]
Hypothesis wrong. The file is `LF`, but it still causes my fans to spin.

**Comment by matheus23** [comment]
Interestingly, this issue doesn't seem to be caused by tree-sitter.
I've cloned and run the master version of tree-sitter-elm and ran `npx tree-sitter parse Tailwind.elm` (`Tailwind.elm` being the file causing my fans to spin) and it doesn't cause an issue.

Not sure where to look now. What other native code is run with the elm-language server?

**Comment by Razzeee** [comment]
No, it's fine here as @jmbockhorst mentioned above, he suspects the problem to be outside of tree sitter too.

I'm not aware of more native code, maybe the parsing is fine, but we get stuck/slow down in some loop on our side? Maybe try to disable stuff via settings (as far as we allow) and see if it still happens?

**Comment by matheus23** [comment]
Oh, sorry @Razzeee, I missed your message. I've already created a new issue.

**Comment by Orasund** [comment]
Not sure if related, but while working on [elm-ui-widgets](https://github.com/Orasund/elm-ui-widgets) the server crashed after about 15min.

I could not pinpoint the problem any further, but I am using Windows. Maybe something that could be related is that I have two elm.json files (one at `src/` and one of `example/`) with the second one referencing the first.
