### ISSUE TITLE
Separate tests from normal imports/forest

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#49]
At the moment features like completions etc will make it seem like they work if you import the correct things, even if that is from the testing dependencies or vice versa.

**Comment by Razzeee** [comment]
Best would be to have the normal imports/forest and another set of normal imports/forest + test imports/forest

**Comment by Razzeee** [comment]
@jmbockhorst can we close this?

**Comment by jmbockhorst** [comment]
No, we still have one forest for both.
