### ISSUE TITLE
Extension fails to load on new mac m1 chips

### ISSUE THREAD

**Issue by devnacho** [elm-tooling/elm-language-server#492]
When running the extension on a mac m1 chip I see an output error when parsing elm files.

## Expected Behavior
- It should parse elm files in source directory

## Current Behavior
When trying to parse the files inside the source directory it throws the following error:
```
[Error - 9:33:54 PM] Error parsing files for /Users/nachogutierrez/Projects/timeline-v2/assets/elm.json:
Error: fastqueue concurrency must be greater than 1
    at fastqueue (/Users/nachogutierrez/.vscode-insiders/extensions/elmtooling.elm-ls-vscode-2.0.1/server/node_modules/fastq/queue.js:13:11)
    at new AsyncReader (/Users/nachogutierrez/.vscode-insiders/extensions/elmtooling.elm-ls-vscode-2.0.1/server/node_modules/@nodelib/fs.walk/out/readers/async.js:14:23)
```

## Context

I'm not familiar with the code of the extension although I debugged this and read the source code to find the issue.
There's another VS Code extension that fails due to the same reason. [Maybe it helps](https://github.com/lokalise/i18n-ally/issues/460)

## Steps to Reproduce (for bugs)
1. Open Visual Studio Code - Insiders
2. Open Elm File

## Your Environment
* Version used: Elm VS Code extension 2.0.1
* Editor used: Visual Studio Code - Insiders 1.53.0-insider
* Operating System and version: Mac OS Big Sur - Darwin arm64 20.1.0

**Comment by Razzeee** [comment]
Probably due to https://github.com/mrmlnc/fast-glob/releases/tag/3.2.5

I pushed an update to master, are you able to test master?

**Comment by devnacho** [comment]
Thank you very much @Razzeee 

>> I pushed an update to master, are you able to test master?

Happy to test it on master. Not really sure how to do it though as I'm quite new to VS Code. Any good recommendation?

Thank you

**Comment by Razzeee** [comment]
Instructions are here: https://github.com/elm-tooling/elm-language-client-vscode#contributing--debugging

But it seems like npm fooled me, it didn't update the dep in the server repo for some reason. Will have to try later, not sure if I will get to it today.

**Comment by Razzeee** [comment]
I pushed another update, that should make this work in master.

**Comment by jmbockhorst** [comment]
Please test using 2.0.2 and verify this was fixed.

**Comment by Razzeee** [comment]
Closing this, feel free to ping, if it still does not work.
