### ISSUE TITLE
Type inference issues after upgrade to v2

### ISSUE THREAD

**Issue by akoppela** [elm-tooling/elm-language-server#494]
There is an issue with type inference algo which leads to false alarms. Consider following block of code:

```
-- CONFIG

type Config data
    = Config (RequiredConfig data)

type alias RequiredConfig data =
    Data data -> String

type alias Data data =
    { data
        | windowWidth : Int
        , windowHeight : Int
    }

-- PUBLIC CONFIG

type alias PublicConfig =
    Config {}

type alias PublicRequiredConfig =
    RequiredConfig {}

publicConfig : PublicRequiredConfig -> PublicConfig
publicConfig =
    Config
```

## Expected Behavior
I expect it to compile successfuly.

## Current Behavior
LSP diagnostics report an issue at `publicConfig` function. The report is:

```
Type mismatch error.
Expected: `(PublicRequiredConfig) -> PublicConfig`
Found: `(RequiredConfig (Data {  })) -> Config (Data {  })`
```

## Possible Solution
It seems that what LSP finds is wrong. Because it should be `(RequiredConfig {  }) -> Config {  }` instead of `(RequiredConfig (Data {  })) -> Config (Data {  })`.

## Steps to Reproduce (for bugs)
Run LSP diagnostics on provided block of the code.

## Context
The issue reports false alarms.

## Your Environment

* Version used: v2.0.1
* Editor used: Emacs
* Environment name and version (e.g. node.js 5.4): v14.15.1
* Operating System and version: MacOS 10.15.7

**Comment by jmbockhorst** [comment]
Should note that this is the behavior in intellij as well.

**Comment by roberth** [comment]
I've seen a problem like this. As a workaround, I've added a redundant type signature on a let binding, which made the error disappear in my case.

`elmtooling.elm-ls-vscode-2.2.0`, `Elm version 0.19.1`

**Comment by roberth** [comment]
The workaround doesn't work anymore. It most have been a lucky coincidence that it worked for some time.

Version: 2.2.1

I've also started to get syntax errors that shouldn't be there. Those occur in the same file, deeply nested in multiple nested case expressions, list literals, `|>` and a lambda. Normal Elm compiles it just fine.

**Comment by razzeee** [comment]
But your not getting parsing errors like https://github.com/elm-tooling/elm-language-server/issues/610 ?

**Comment by roberth** [comment]
@razzeee It is very similar and I've replied in that thread. Let's focus this thread in the type inference issue though. (sorry for going off topic)
