### ISSUE TITLE
Type mismatch error. Expected and Found contains equal values.

### ISSUE THREAD

**Issue by Yarith** [elm-tooling/elm-language-server#495]
I got today some type mismatch errors reported for compiling code. They were blinking in the past few days already, but now they were persistent, so i can reproduce and report it.

The expected and found values are the same. It gets reported after modification of the document. It seems the type annotation gets out of sync with the inferred types.

I have prepared an example code and attached a video directly under the reproduce steps.

## Expected Behavior
There should be no errors reported.

## Current Behavior
The following error gets reported.
```markdown
Type mismatch error.
Expected: `Accessor data value`
Found: `Accessor data value`
Mismatched fields: 
 Field `get` expected `data -> value`, found `data -> value`
 Field `set` expected `value -> data -> data`, found `value -> data -> data`
```

When the error already visible and you edit a specific other place, it then moves to another line with different error text:
```markdown
Type mismatch error.
Expected: `value`
Found: `value`
```

## Possible Solution
I think the error is only reported when the last change to the document has added or removed a node in the syntax tree. If you modify an existing node the error does not appear or will even be removed.

The behavior feels like a type level referencial comparison between the old syntax tree and the new syntax tree. Only if there are minor changes they seem to be in sync by luck.

Removing some specific type annotations that are related to the type parameters may solve the problem. Which i can rarely do, because then i get MVar and rank errors from the compiler.

Maybe just a problem with type annotations with type parameters in let blocks, when they share the type parameter of the outer scope?

## Steps to Reproduce (for bugs)

1. Copy the example code in an elm language server environment. After the language server is done with loading, there are no errors visible.
2. Now go to the line 73 and add an space after the 7. The error is now getting reported at line 55 wit h the first error message.
3. But if you add another space the error disappears again.
4. If you remove the 7 the error is visible again.
5. Now go to the line 51 and put an space after the equals sign =. The error moved now to the line 59 with the second error message.
6. If you comment out the annotations in line 53 and line 57, the error disappears and all steps above does not cause it again.
7. If you comment out the annotations in line 48 instead, the errors disappears and all steps above does not cause it again too.
8. After saving, the error disappears too.

I have prepared a video which shows the described steps in visual studio code:
[The attached video - 1 minute and 28 seconds, 841KB size](https://user-images.githubusercontent.com/7803088/106364392-f54c5d00-632e-11eb-9dc5-b07dbf568b17.mp4)

### Example code
I have prepared an example code which is neccessary to reproduce the error easily.
```elm
module Main exposing (main)

import Html as H exposing (Html)


type alias Accessor record value =
    { get : record -> value
    , set : value -> record -> record
    }


firstname : Accessor { r | firstname : value } value
firstname =
    { get = .firstname
    , set = \v r -> { r | firstname = v }
    }


lastname : Accessor { r | lastname : value } value
lastname =
    { get = .lastname
    , set = \v r -> { r | lastname = v }
    }


type alias Data =
    { firstname : String
    , lastname : String
    }


type alias DataDescriptor =
    { firstname : Accessor Data String
    , lastname : Accessor Data String
    }


dataDescriptor =
    { firstname = firstname
    , lastname = lastname
    }


type alias Updater value yield =
    value -> ( value, yield )


updateField : (DataDescriptor -> Accessor data value) -> Updater value yield2 -> data -> ( data, yield2 )
updateField accessorSelector updater =
    let
        help data =
            let
                accessor : Accessor data value
                accessor =
                    accessorSelector dataDescriptor

                oldValue : value
                oldValue =
                    accessor.get data

                ( newValue, yield ) =
                    updater oldValue
            in
            ( accessor.set newValue data, yield )
    in
    help


main : Html msg
main =
    let
        something =
            "working" |> String.dropLeft 7
    in
    H.text something

```

## Context
I only wanted to implement a visitor for my data structure. The fields have different types, but have the same operations (getter, setter, repeat, add, label, unit and so on). So i give a record with the possible operations and the actual record. Also sometimes i needed to generate some Cmds.

After i was done i ended up with compiling code but reported errors by the language server after specific edits. The example code is a much shorter version which reproduces the errors.

## Your Environment
* Version used: 2.0.1
* Editor used: 
```
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Datum: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Betriebssystem: Windows_NT x64 10.0.19042
```
* Environment name and version (e.g. node.js 5.4): node 15.6.0
* Operating System and version: Windows 10 Version 20H2 (Build 19042.746)

**Comment by jmbockhorst** [comment]
You were correct in your theory, there was an issue with type annotations being cached inside the let declarations.
