### ISSUE TITLE
Language server crashing repeatedly

### ISSUE THREAD

**Issue by brian-carroll** [elm-tooling/elm-language-server#496]
## Expected Behavior
Shouldn't crash! Ha ha, not sure what else to write for this.

## Current Behavior
The extension keeps popping up a notification telling me the language server crashed 5 times in the last 3 minutes. Actually it takes a lot less than 3 minutes.
Looking at the Output panel, I see the following error
```
TypeError: Cannot read property 'synchronize' of undefined
c:\Users\brian\.vscode\extensions\elmtooling.elm-ls-vscode-2.0.1\server\node_modules\web-tree-sitter\tree-sitter.js:1
var Module=void 0!==Module?Module:{};!function(e,t){"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?module.exports=t():window.TreeSitter=t()}(0,function(){var e,t={};for(e in Module)Module.hasOwnProperty(e)&&(t[e]=Module[e]);var r,n,s=[],o=function(e,t){throw t},_=!1,a=!1;_="object"==typeof window,a="function"==typeof importScripts,r="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,n=!_&&!r&&!a;var i,u,l,d,c="";r?(c=a?require("path").dirname(c)+"/":__dirname+"/",i=function(e,t){return l||(l=require("fs")),d||(d=require("path")),e=d.normalize(e),l.readFileSync(e,t?null:"utf8")},u=function(e){var t=i(e,!0);return t.buffer||(t=new Uint8Array(t)),L(t.buffer),t},process.argv.length>1&&process.argv[1].replace(/\\/g,"/"),s=process.argv.slice(2),"undefined"!=typeof module&&(module.exports=Module),process.on("uncaughtExcep

RuntimeError: abort(TypeError: Cannot read property 'synchronize' of undefined). Build with -s ASSERTIONS=1 for more info.
    at process.fe (c:\Users\brian\.vscode\extensions\elmtooling.elm-ls-vscode-2.0.1\server\node_modules\web-tree-sitter\tree-sitter.js:1:10450)
    at process.emit (events.js:228:7)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:32)
```

The only place I can see an object with a `synchronize` property is at [extension.ts line 156](https://github.com/elm-tooling/elm-language-client-vscode/blob/44d0e578f1221214c0b881f1e71cc5958f682c5f/client/src/extension.ts#L156) in the `clientOptions` object.

## Possible Solution
No idea! The extension was working until fairly recently. I don't know what to look for.

## Steps to Reproduce (for bugs)
1. Re-install elm-test, elm-format and the extension
2. Close and open VS Code
3. Open an Elm file
4. Crash!

## Context
I have syntax highlighting but no other features of the extension such as error highlighting or jump to definition.
I'm working on a side-project, a fork of the Elm compiler with WebAssembly output. I have some Elm files that I use for compiler tests.

## Your Environment

elm-language-client-vscode v2.0.1
VS Code 1.52.1
Node v12.18.1
Windows 10 Home, version 1909
elm 0.19.1
elm-test@0.19.1-revision5
elm-format@0.8.4

**Comment by jmbockhorst** [comment]
Using the latest version 2.0.2, it shouldn't crash anymore, but there will probably still be an error in the log with the root problem.

**Comment by brian-carroll** [comment]
Thanks! I got the 2.02 upgrade and everything seems to work perfectly now! Error highlighting, format-on-save, all looking good. They were broken before.

Very impressed with the response, thanks! Sorry I didn't see the email notification of your reply until now.

I can see a couple of error messages in the logs alright. I have several test Elm apps in the project and it looks like two of the older ones have elm.json files that refer to packages I no longer have installed. I see log messages like `Error parsing files` and `ENOENT: no such file or directory`.

Good work folks! 👍
