### ISSUE TITLE
Version 2.0.2 Causes Issues with the Elm Language Server in Some Instances

### ISSUE THREAD

**Issue by kevinshurtz** [elm-tooling/elm-language-server#499]
Hey everyone!

I'm new to Elm, and am just stating to work through some of the tutorials on the website.  In the process, I encountered some issues with the latest version of the Elm Tooling extension.

## Expected Behavior
After installing the extension, I would anticipate that the Elm Language Server would start successfully, and that I would receive context hints and syntax highlighting for Elm files.

## Current Behavior
I'm not sure if this issue is unique to my setup, but it seems that the Elm Language Server does not start correctly in version 2.0.2 of the extension.  No context hints, suggestions, or syntax highlighting are offered for Elm files, and invoking the `Elm: Restart Elm Language Server` results in the following message:

```
Command 'Elm: Restart Elm Language Server' resulted in an error (command 'elm.commands.restart' not found)
```

If I downgrade back to version 2.0.1 of the extension, however, all of these things return.  I get syntax highlighting and various bits of information in the editor for Elm files.

## Possible Solution
I haven't had a chance to check out the diff between version 2.0.1 and 2.0.2 yet, so I'm not sure what might have caused the issue, but for users, simply switching back to 2.0.1 should fix of the issue.

## Steps to Reproduce (for bugs)
1. Install the latest version of the extension from the Visual Studio Code extension marketplace.
2. Invoke the `Elm: Restart Elm Language Server` task.

## Context
I'm just working through the Elm tutorials and I can just switch back to the previous version for the time being.

## Your Environment
I'm using version 1.52.1 of Visual Studio Code, and I'm running it on Windows 10, version 10.0.21301.1000.  The version of Node on my machine at the time of the error was v14.15.3.

As noted previously, this issue seems isolated to version 2.0.2 of the extension.  Version 2.0.1 seems to work alright on my machine.

Thank you guys for looking into the issue, and I appreciate your work on this awesome project!

**Comment by Razzeee** [comment]
I'm wondering if it's a build problem, as I needed to build it manually, due to some pipeline problems.

Can you try to have a look at the log https://github.com/elm-tooling/elm-language-client-vscode#faq
when it happens again?

**Comment by Razzeee** [comment]
Can you check the new version?

**Comment by kevinshurtz** [comment]
Hey Razzee, I apologize for the late reply!  Since I made this post, I seem to have received a bad Windows Insider update; I've since reloaded my machine with Fedora.

I can confirm that both versions 2.0.2 and 2.0.3 of the extension seem to work for Visual Studio Code on Fedora 33 (Workstation Edition) with GNOME.  The Visual Studio Version I just installed is 1.53.1, and was installed with Flatpak.  Perhaps the issues with the previous version were confined to Windows, or were unique to my setup of Visual Studio Code; I'm not entirely sure.

I apologize for creating an issue and then unexpectedly wiping the environment it was detected on.  So far as I can tell, the latest version of the extension seems to be working as expected.  Thank you for your help. :slightly_smiling_face: 

If there's any additional information I can share, please let me know!

**Comment by Razzeee** [comment]
No worries, it's good reference in case somebody else stumbles upon it.
