### ISSUE TITLE
Basic set of language server features

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#5]
We basically want all that applies from here https://code.visualstudio.com/api/language-extensions/programmatic-language-features

* [Provide Diagnostics](https://github.com/Razzeee/elm-language-server/issues/13)
* [Show Code Completion Proposals](https://github.com/Razzeee/elm-language-server/issues/4)
* [Show Hovers](https://github.com/Razzeee/elm-language-server/issues/8)
* ~~Help With Function and Method Signatures~~
* [Show Definitions of a Symbol](https://github.com/Razzeee/elm-language-server/issues/9)
* [Find All References to a Symbol](https://github.com/Razzeee/elm-language-server/issues/10)
* ~~Highlight All Occurrences of a Symbol in a Document~~
* [Show all Symbol Definitions Within a Document](https://github.com/Razzeee/elm-language-server/issues/11)
* [Show all Symbol Definitions in Folder](https://github.com/Razzeee/elm-language-server/issues/11)
* [Possible Actions on Errors or Warnings](https://github.com/Razzeee/elm-language-server/issues/17)
* [CodeLens - Show Actionable Context Information Within Source Code](https://github.com/Razzeee/elm-language-server/issues/7)
* ~~Show Color Decorators~~
* [Format Source Code in an Editor](https://github.com/Razzeee/elm-language-server/issues/12)
* ~~Format the Selected Lines in an Editor~~
* ~~Incrementally Format Code as the User Types~~
* [Rename Symbols](https://github.com/Razzeee/elm-language-server/issues/14)

I crossed out the ones I think don't make sense, please comment if you disagree. We can still decide in each issue if any of these don't work for elm

**Comment by Razzeee** [comment]
I've added basic providers for each of the above.

**Comment by bengolds** [comment]
Why did you cross out "Help With Function and Method Signatures"? Getting type information on functions as you're working with them would be very valuable.

**Comment by Razzeee** [comment]
@bengolds it needs a trigger like `,` and as params in elm are separated by spaces, we would need to use that as a trigger, but I suspect that will cause more problems.
See: https://code.visualstudio.com/api/language-extensions/programmatic-language-features#help-with-function-and-method-signatures

Looking at it again, I realize that that would happen for other languages, when hitting a `,` or similar. So maybe it is already location aware. 

I will need to try to get this api to work, to say more.

**Comment by bengolds** [comment]
Looking at the API [here](https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp), I don't think the client is location-aware in requesting signatures. Instead, I think anytime a `triggerCharacter` is pressed, it sends a `textDocument/signatureHelp` request with a location. If that location is in the middle of a function, we can return a `SignatureHelp` object. If it's not, we just return `null` and it'll ignore it.

Once I have a chance to look at the code and help out, I can take a stab at this as well.

**Comment by Razzeee** [comment]
Your right, if you want to work on this I played with it here https://github.com/Razzeee/elm-language-server/tree/wip-signature-provider

**Comment by Daniel-V1** [comment]
First off, let me say its awesome to see an elm language server with more than just diagnostics, so thanks for this! I see that you crossed off possible actions on errors and warnings, and was just thinking that the compiler already provides actionable feedback for a decent set of problems (like incorrect type signatures etc) that we could maybe use to cover that. I personally think that would be awesome to see.

**Comment by Razzeee** [comment]
The mentioned ones should all be done and any improvement should be tracked with issues of their own, closing this.
