### ISSUE TITLE
Plugin runs "elm-format" even when "editor.formatOnSave" is set to "false"

### ISSUE THREAD

**Issue by ryannhg** [elm-tooling/elm-language-server#502]
Hey Razzeee  👋 

## Expected Behavior

My expectation is that setting `editor.formatOnSave` to `false` would not run the `elm-format` command.

Either when set for .elm files directly:

```jsonc
{
  // ...
  "[elm]": {
      "editor.formatOnSave": false
  }
}
```

Or whether set for all VS code files:

```jsonc
{
  // ...
  "editor.formatOnSave": false
}
```

## Current Behavior

Currently, the format step is still being run:

![image](https://user-images.githubusercontent.com/6187256/106803509-eb29a780-6629-11eb-9d4f-c0f5e22414c0.png)

## Possible Solution

I noticed there was a place in this repo where we have access to the client settings, but the `formatOnSave` setting is not being checked before `this.format` is called:

https://github.com/elm-tooling/elm-language-server/blob/2b8de53938ef83a71e1c6fc094ce06cfaaeca85b/src/providers/documentFormatingProvider.ts#L71-L76

Maybe adding a conditional around those lines would fix the issue (along with passing it from the client)?

## Steps to Reproduce (for bugs)

1. In your __User Settings__, set `editor.formatOnSave` to `false`.
2. Make a change to an `.elm` file, and save it.
3. Notice that `elm-format` is being run on save.

## Context

I am using this VS code Elm plugin at work, and (for our large code base) I noticed it runs slowly during the format step. I tried to disable the formatting to see if it would improve the performance, but noticed that `elm-format` was still being run, even after disabling formatting in my editor.

## Your Environment

* Version used: __2.0.2__
* Editor used: __VS Code__
* Environment name and version (e.g. node.js 5.4): __Node v10.22.1__
* Operating System and version: __MacOS Catalina – Version 10.15.7__

---

Thank you for all your great work on this plugin so far! 💯

**Comment by Razzeee** [comment]
I fail to reproduce this. Your saying, it's actually editing and formatting your files?

**Comment by ryannhg** [comment]
Interesting– let me confirm that I can reproduce this problem on another machine!

I looked for "`formatOnSave`" in this codebase, and didn't see anywhere that might prevent the formatting from happening:
https://github.com/elm-tooling/elm-language-server/search?q=formatOnSave

**Comment by ryannhg** [comment]
I tried to reproduce this on my other Windows machine, and it looks like it's not a problem!

Sorry for the false alarm! ( I'll close this issue out 😅 )

**Comment by Razzeee** [comment]
> I looked for "`formatOnSave`" in this codebase, and didn't see anywhere that might prevent the formatting from happening:
> [elm-tooling/elm-language-server/search?q=formatOnSave](https://github.com/elm-tooling/elm-language-server/search?q=formatOnSave)

Yes, it should be handled by the editor calling us. We only provide how to format, this setting for e.g. is VSCode specific.
