### ISSUE TITLE
Erratic/broken behavior with Neovim's integrated LSP client

### ISSUE THREAD

**Issue by kwshi** [elm-tooling/elm-language-server#503]
## Expected Behavior
Normal LSP operation.

## Current Behavior
When using elm-language-server with Neovim's built-in language client (configured via [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig)), elm-language-server's parser appears to be completely broken.  I've recorded [two](https://terminalizer.com/view/0d5e62224618) [screencasts](https://terminalizer.com/view/38acf8c54620) demonstrating some of the erratic behavior.  A summary follows:

On opening a new buffer, LSP behaves fairly normally (type checking works, diagnostics make sense, whatever).  After a couple normal editing operations (delete some text, add some text), it appears elm-language-server's internal model of the buffer contents becomes totally malformed, and elm-language-server starts complaining about random, bogus parsing errors & spitting out nonsense diagnostics.  Here are some sample error messages it gives:
- `No definition found for 'mport '.`
- `Parsing error.` (on what _should_ be totally valid Elm code)
- `Could not find a module to import named 'String  ' in `...
- `Unused pattern variable '='`
- `A value named 'nt' is already defined` (in code that does not define any `nt`, only uses `Int` in a type signature).

## Possible Solution

Sorry, but I have no familiarity with the internal workings of elm-language-server or Neovim LSP, so I honestly have no idea where to start suggesting fixes.  A few observations nonetheless:
- This issue does _not_ occur if I use coc.nvim instead of Neovim's built-in LSP client, on the same elm-language-server installation.
- My _other_ language servers (e.g. TypeScript, Python, OCaml) have been working fine with Neovim's built-in LSP client.
My point is that it's _possible_ that the error is on Neovim's side, seeing as their LSP implementation is still "nightly", but since I've only been able to reproduce the problem in the unique combination of Neovim + ElmLS, I don't know how to isolate the problem.

## Steps to Reproduce (for bugs)

1. Set up elm-language-server with Neovim's built-in LSP client.  Follow [instructions to install vim-plug](https://github.com/junegunn/vim-plug), then contents of `~/.config/init.vim`:
   ```vim
   call plug#begin()
   Plug 'neovim/nvim-lspconfig'
   call plug#end()

   lua << EOF 
   require'lspconfig'.elmls.setup{}
   EOF 
   ```
2. Edit literally any Elm file within a project.
3. Make some random changes.

I have made screencasts illustrating this process [here](https://terminalizer.com/view/38acf8c54620) and [here](https://terminalizer.com/view/0d5e62224618), showing the erratic errors that pop up for me.

## Context
*How has this issue affected you? What are you trying to accomplish?*  Ha ha, you're funny.

## Your Environment

* Version used: 2.0.2
* Editor used: Neovim, with built-in LSP
* Environment name and version (e.g. node.js 5.4): Node 14.15.4
* Operating System and version: Void Linux

**Comment by kwshi** [comment]
FWIW, I've made a repository containing a sample Elm project & Neovim config, together with a Dockerfile setting up a fresh Neovim install w/ nothing unnecessary installed.  That should make the problem easier to test & reproduce.

Repository here: https://github.com/kwshi/bug-reports/elm-ls-nvim

**Comment by kwshi** [comment]
Update: I have run into the same bug using coc.nvim after prolonged usage.  It appears that, while coc.nvim is _more_ robust than nvim-lspconfig in resisting elmls total corruption, it is still susceptible to it sometimes.  That leads me to conclude that the error is specific to elmls, not nvim-lspconfig.

![coc-elmls](https://user-images.githubusercontent.com/3887189/106854450-25b63300-6670-11eb-890b-5101f7eda947.png)

**Comment by mjlbach** [comment]
note nvim-lspconfig is just sending the initialization options, this may be because in neovim core we resend the entire buffer on textDidChange instead of the delta. Not sure what coc is doing, but we do have the option for incremental buffer updates.

**Comment by Razzeee** [comment]
@mjlbach 
Hrm, we set the server to incremental sync via https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_synchronization_sc

Am I understanding you correctly, that your client doesn't honor that?

**Comment by mjlbach** [comment]
We set all dynamicRegistration capabilities to false (we don't support dynamic registration). If dynamic registration is false/nil do you assume incremental sync?

**Comment by Razzeee** [comment]
I think we always assume incremental at the moment.

According to https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_synchronization it sounds like clients should always support both?
Might just be weird wording

> Client support for textDocument/didOpen, textDocument/didChange and textDocument/didClose notifications is mandatory in the protocol and clients can not opt out supporting them. This includes both full and incremental synchronization in the textDocument/didChange notification.

**Comment by mjlbach** [comment]
We do technically support incremental buffer updates, it's just disabled by default. @kwshi you can try enabling it to see if it fixes you problem.

```
local custom_attach = function(client)
      if client.config.flags then
        client.config.flags.allow_incremental_sync = true
      end
    end
require('lspconfig').elmls.setup({
   on_attach = custom_attach;
})
```

**Comment by ocharles** [comment]
I am also running into this and from from my limited testing so far, things are back to normal with @mjlbach's suggestion [above](https://github.com/elm-tooling/elm-language-server/issues/503#issuecomment-773922548)

**Comment by mjlbach** [comment]
I'll just enable incremental sync by default for elmls client-side in nvim-lspconfig

@Razzeee Thanks for pointing this out

**Comment by gabriel-sevecek** [comment]
I have this issue using coc.nvim, but it only happens when there are no real error messages.

**Comment by kwshi** [comment]
[@mjlbach's `custom_attach` fix](https://github.com/elm-tooling/elm-language-server/issues/503#issuecomment-773922548) does appear to fix it for me, for now!  If I had to guess, the reason that I encounter this issue occasionally in coc.nvim as well would also have to do with when coc.nvim chooses to do a full/non-incremental sync.  I was switching buffers frequently & had multiple panels open--not sure if that would contribute to this.

**Comment by Razzeee** [comment]
Closing this for now. Feel free to reopen or start a new issue.

**Comment by kwshi** [comment]
OK with this being closed for now, but it's worth keeping in mind that the issue is not _completely_ resolved, in the sense that it appears if any client attempts to do a full/non-incremental sync, that may cause elmls to land in a broken state.  Forcing full sync is a viable workaround, but _perhaps_ the situation can still be improved.

**Comment by Razzeee** [comment]
I still think, if there is anything to improve, it's on the client side, as the spec states, that it needs to support both.

**Comment by kwshi** [comment]
You're right, I think, but I also think it would be preferable for `elm-language-server` to at least have some explicit error case, where it recognizes when a client is not using incremental sync & explicitly crashes/fails/reports an error message, as opposed to "silently" failing with erratic behavior.  For future users running into this issue, having an error message would make it much easier for them to figure out what is wrong, rather than having to google the weird behavior & hopefully find this issue.

**Comment by Razzeee** [comment]
Agreed

**Comment by kevinsjoberg** [comment]
I don't believe this is fixed @razzeee. I'm using [Helix](https://helix-editor.com) and seeing this erratic behaviour occasionally. Not all the time, but it happens every time I sit down and code Elm. See https://asciinema.org/a/dexV5nWbBn5sQ9iDRD5X2r9qB.

All changes are reported using incremental synchronization (I know, because I help develop the editor in question). In the example video above, everything works fine until I save the file, a [formatting request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_formatting) triggers to format the document in question. As you can see by the video above, diagnostics come back, saying there's a parsing error, while in reality, there isn't one.

**Comment by razzeee** [comment]
First log seems sane, the best approach might be to print how the lsp internally thinks the code looks and then see if it matches what your seeing. Basically working backwards to the issue.
