### ISSUE TITLE
UnusedPatternVariable diagnostic is very slow on big files

### ISSUE THREAD

**Issue by matheus23** [elm-tooling/elm-language-server#504]
Continuation from #484.

When my project contains files like this ([Utilities.elm](https://ipfs.runfission.com/ipfs/bafybeid5qds2j2j2mfw6ndp5tz75uak2p2e6d3xs5s4ccghoekl3egvq3e/p/Utilities.elm)) it makes my fans spin indefinitely, because a process running `elm-language-client-vscode/server/out/index.js` runs 100% on one core.

I'm running the `elm-language-client-vscode` master (https://github.com/elm-tooling/elm-language-client-vscode/commit/7532d7fc0caf9a6590b15f817272337f09bc0704).

I've checked that tree-sitter-elm can parse this file and it's just fine.

Turning off the `ElmLS Diagnostics` setting fixes the problem (but is unfortunate, obviously).

I have created a [.cpuprofile](https://ipfs.runfission.com/ipfs/bafybeih5pyz6ibte2naqtcn2535jxlcpublw3gysnyucfxl2fvdz2uoeo4/p/CPU-20210205T115804.043Z.cpuprofile), but I doubt it's helpful. I *think* when I'm profiling a language server extension, I basically only profile the *client* part, but not the *server* part. This results in a profile that contains only native code, as 99% of the time its waiting for messages on sockets (this is my hypothesis). If you know any other way to profile this, I'd be happy to try it.

I would love input in how to further test this issue. Can anyone else reproduce this issue?
Maybe it's related to file size (and it's just running *reeeeally* long), as the file is almost 33kLOC, ~~but it has never run to completion, even after hours~~. This is incorrect! It finishes after ~10 minutes. It seems I got the impression it never finishes, because the process gets restarted once I save any other Elm file?

**Comment by jmbockhorst** [comment]
Thanks for providing a test file as it should help repro it. The file size is definitely a factor here, but I suspect we have something else going on too.

**Comment by matheus23** [comment]
Ok. I've done some delta debugging.

I've enabled the ElmLS Diagnostics again, and systematically turned settings in `elm-analyse.json` on and off.

With these settings, there's no issue:
```json
{
    "checks": {
        "BooleanCase": true,
        "DropConcatOfLists": true,
        "DropConsOfItemAndList": true,
        "NoUncurriedPrefix": true,
        "MapNothingToNothing": true,
        "SingleFieldRecord": true,
        "UnnecessaryListConcat": true,
        "UnnecessaryPortModule": true,
        "UnusedImport": true,
        "UnusedImportAlias": true,
        "UnusedImportedVariable": true,
        "UnusedPatternVariable": false,
        "UnusedTopLevel": true,
        "UnusedTypeAlias": true,
        "UnusedValueConstructor": true,
        "UnusedVariable": true,
        "UseConsOverConcat": true
    }
}
```

However, these settings do make my fans spin for >2 minutes (at least. I interrupted it):
```
{
    "checks": {
        "BooleanCase": true,
        "DropConcatOfLists": true,
        "DropConsOfItemAndList": true,
        "NoUncurriedPrefix": true,
        "MapNothingToNothing": true,
        "SingleFieldRecord": true,
        "UnnecessaryListConcat": true,
        "UnnecessaryPortModule": true,
        "UnusedImport": true,
        "UnusedImportAlias": true,
        "UnusedImportedVariable": true,
        "UnusedPatternVariable": false,
        "UnusedTopLevel": true,
        "UnusedTypeAlias": true,
        "UnusedValueConstructor": true,
        "UnusedVariable": true,
        "UseConsOverConcat": true
    }
}
```json
{
    "checks": {
        "BooleanCase": false,
        "DropConcatOfLists": false,
        "DropConsOfItemAndList": false,
        "NoUncurriedPrefix": false,
        "MapNothingToNothing": false,
        "SingleFieldRecord": false,
        "UnnecessaryListConcat": false,
        "UnnecessaryPortModule": false,
        "UnusedImport": false,
        "UnusedImportAlias": false,
        "UnusedImportedVariable": false,
        "UnusedPatternVariable": true,
        "UnusedTopLevel": false,
        "UnusedTypeAlias": false,
        "UnusedValueConstructor": false,
        "UnusedVariable": false,
        "UseConsOverConcat": false
    }
}
```

So it seems like `UnusedPatternVariable` is the culprit.

**Comment by Razzeee** [comment]
Should be in https://github.com/elm-tooling/elm-language-server/blob/master/src/providers/diagnostics/elmLsDiagnostics.ts#L731 then. You can set breakpoints and maybe figure out what part is slow.

Run a debug session via https://github.com/elm-tooling/elm-language-client-vscode#contributing--debugging
Then open an elm file, so that the server starts and attach the debugger to port 5010 (see debug view in VSCode). The last part is a bit janky, as you need to be fast enough :)

**Comment by jmbockhorst** [comment]
Yes, I've noticed that one taking the most time before. Maybe we can find a more performant tree-sitter query.

**Comment by Razzeee** [comment]
Seems to be the foreach loop here https://github.com/elm-tooling/elm-language-server/blob/master/src/providers/diagnostics/elmLsDiagnostics.ts#L767

**Comment by jmbockhorst** [comment]
Yeah, there's just not a fast way of doing it like this. I was thinking about switching unused diagnostics into the type checker, which would use references from type inference to determine what is unused.

**Comment by Razzeee** [comment]
I think it should be possible with a tag query in tree sitter, but we haven't really used these yet (or know if we can use them)

**Comment by jmbockhorst** [comment]
I came up with a way to cache certain results that should increase performance a decent amount on big files.

**Comment by Razzeee** [comment]
@matheus23 can you give #505 a spin?
