### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by heptalophos** [elm-tooling/elm-language-server#508]
[elmTooling.elm-ls-vscode-unresponsive.cpuprofile.txt](https://github.com/elm-tooling/elm-language-client-vscode/files/5952030/elmTooling.elm-ls-vscode-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `elm-ls-vscode`
- Extension Version: `2.0.2`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.53.0`

:warning: Make sure to **attach** this file from your *home*-directory:
`~\AppData\Local\Temp\elmTooling.elm-ls-vscode-unresponsive.cpuprofile.txt`
[elmTooling.elm-ls-vscode-unresponsive.cpuprofile.txt](https://github.com/elm-tooling/elm-language-client-vscode/files/5952006/elmTooling.elm-ls-vscode-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Razzeee** [comment]
Can you retry with the release from today?

**Comment by heptalophos** [comment]
@Razzeee 
Thanx. Adding the `elm-analyse.json` to v2.0.2, reduced quite a bit the activation time of the extension.

**Comment by heptalophos** [comment]
I updated to the new release (2.0.3), it seems to be working, without causing high cpu load, so I am closing this.
