### ISSUE TITLE
Type inference incorrect when pattern matching lists of lists

### ISSUE THREAD

**Issue by Augustin82** [elm-tooling/elm-language-server#513]
When pattern-matching on a list of lists of data, some patterns seem to confuse the type-inference system. See this example:
```elm
test : List (List Float) -> Float
test listList =
    case listList of
        [ a, b ] :: _ ->
            let
                product : Float
                product =
                    a * b
            in
            product

        _ ->
            0
```

## Expected Behavior
The Elm compiler is happy and the code works as intended. The elm-language-server should be fine with it, too!

## Current Behavior
Instead, it reports a type mismatch on both `a` and `b`:
```
[Elm] [E] Type mismatch error.
Expected: `number`
Found: `List Float`
```

## Possible Solution
No idea, sorry!

## Steps to Reproduce (for bugs)
The code above compiles fine on Ellie. Simply pasting it in your editor (and NOT using the Elm compiler report) should be enough.

## Context
N/A

## Your Environment
* Version used: 2.0.1
* Editor used: neovim + CoC
* Environment name and version: nodejs v10.23.2
* Operating System and version: Ubuntu 20.04.1

**Comment by jmbockhorst** [comment]
Also a bug in intelij.
