### ISSUE TITLE
Add fallback variables for all settings

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#52]

**Comment by Razzeee** [comment]
@andys8 Can you test this? https://github.com/elm-tooling/elm-language-server/commit/c6434c8e76d25a0ce46b776f5acbb55aa9f70b92

**Comment by andys8** [comment]
Hey, I tried to verify the change is working.

## Expectation

Deleting an argument (a line here), would work as expected

```vim
function! elm_ls#GetOptions(buffer) abort
    return {
    \    'runtime': 'node',
    \    'elmPath': ale#Var(a:buffer, 'elm_ls_elm_path'),
    \    'elmFormatPath': ale#Var(a:buffer, 'elm_ls_elm_format_path'),
    \    'elmTestPath': ale#Var(a:buffer, 'elm_ls_elm_test_path'),
    \ }
endfunction
```

## Observation

Deleting `elmPath` will work as expected.
Deleting `elmTestPath` (testing with tests), will not work.
Hardcoding `'elmTestPath': 'elm-test'` will work. 

```
which elm elm-test
/home/ascharf/.asdf/shims/elm
/tmp/fnm-shell-6447466/bin/elm-test
```

I'm not sure, what is going on here. Please keep in mind, this can be local setup, depending on paths and layers of version managers (asdf and fnm), that make a difference here. But you could verify that it is working on your machine if there is no `elmTestPath` argument and `elm-test` is available on the PATH.

**Comment by Razzeee** [comment]
Removed the settings from the client in vscode. Debugged the server and it picked up the fallback variables. So this should be fine.
