### ISSUE TITLE
Missing action to add missing branches in case statements using nVim + Coc

### ISSUE THREAD

**Issue by bigardone** [elm-tooling/elm-language-server#520]
## Expected Behavior

When creating a case statement on a custom type, and only implementing one of the possible types, the code actions for the case line only display the **Add _ branch** action.

![image](https://user-images.githubusercontent.com/1090272/107941170-97a04d80-6f89-11eb-875a-4a78e6a9c4d3.png)

## Current Behavior

It should display an **Add missing branches** action, which implements placeholders for the missing values.

## Steps to Reproduce (for bugs)

1. Using nVim + Coc
2. Declare a custom type `Msg` with multiple values.
3. Implement a case statement for `Msg`, fulfilling only one branch.
4. Display code actions for the case statement line.

## Your Environment

* Version used: 2.0.2
* Editor used: nVim
* Environment name and version (e.g. node.js 5.4): v12.15.0
* Operating System and version: macOS Big Sur

**Comment by Razzeee** [comment]
While this now works, it won't help with a case where you don't have any branches yet as in

```
case x of
```

**Comment by bigardone** [comment]
I just tried with `case` having at least one branch, and it works like a charm 🎉
