### ISSUE TITLE
Saving 'Main.elm': Running 'Elm' Formatter (configure).

### ISSUE THREAD

**Issue by Yarith** [elm-tooling/elm-language-server#527]
This occurs mostly after adding a case ... of expression. When i remember back correctly, i think, everytime this error happened, i added a new case ... of somewhere. 

This problem was reported quite a few time in slack and i experienced it also myself quite often. Sometimes after some specific changes saving the file is not possible and it shows the message in the bottom right corner, that the formatter is being executed. It seems to be already hanging before the save was triggered. Now i was able to reproduce it consistently.

The message comes when saving the document and the extension is already hanging:
```
Saving 'Main.elm': Running 'Elm' Formatter (configure). [Cancel]
```

I have recorded a video how it happens on my computer, the source code is below in the reproduction steps:
[Attached Video - 1 minute and 50 seconds - 1553 KB](https://user-images.githubusercontent.com/7803088/108605174-e3505e00-73b2-11eb-961a-f59f02b119b7.mp4)

## Expected Behavior
Adding a new case ... of should not cause the extension to hang.

## Current Behavior
Existing comments or spacing around a freshly written case ... of causes the extension to hang in some situations. If you try to save any elm file in this state, you end up with the message in the bottom right corner, that the formatter is running.

## Possible Solution
I think the formatter has nothing to do with the hanging extension, because the cpu usage increases immediately after some spaces/comments. I found a very simple code which triggers the problem. See the recorded video to get hints when this happens. Maybe this is somehow related to the folded comment after the case ... of.

## Steps to Reproduce (for bugs)

You can download my test project from this attachment:
[Attached Zip - 1.226 Bytes](https://github.com/elm-tooling/elm-language-server/files/6016030/ElmFormattersBeingExecuted.zip)

1. Setup an vscode environment with elm language server.
2. Create a new project with the starting code of the video.
3. Follow the steps described in the comment block or follow the video.

I hope this helps in solving some kinds of these errors.

### Workaround
1. Add a single line comment at the bottom of the file, beginning at the first character
2. Add round parens around the incomplete case ... of. This solves also the wrong folding of the case ... of. But elm-format will remove these parens and the folding breaks again.

### Source code
Starting code for experiments, contains instructions for reproduction in the comment block.
```elm
module Main exposing (specialText)

-- I displayed the cpu usage of vscode, so you can see,
-- which action will cause the extension to hang.
-- Trivia around case ... of causes sometimes vscode
-- to consume one cpu thread. These are my findings:
-- ⬜ Add a single line comment before a case ... of
--    ⬜ Condition: After the case ... of must be no new line
-- ⬜ Add a new line with at least one space at the beginning
-- ⬜ If you add a single line comment beginning on the
--    first line, you can add spaces directly after the case
-- ⬜ Comments after the case ... of gets folded together.
--    I expect this is somehow related with the cpu usage.


specialText : Maybe String -> String
specialText u =
    case u of
```
## Context
I was writing a bunch of new types and wrote below a toString function. My case ... of was very often the last line in my elm file. After every single case ... of i needed to reload vscode. After i noticed this i tried to break it down and recoded it. If this happens at work this is far worse, because the vscode reload kills all my started servers and watches in the integrated terminal.

## Your Environment

* Version used: 2.0.3
* Editor used:
```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```
* Environment name and version (e.g. node.js 5.4): Node.js v15.6.0
* Operating System and version: Windows 20H2 (Build 19042.804)

**Comment by Razzeee** [comment]
Seems to get stuck in here https://github.com/elm-tooling/elm-language-server/blob/master/src/providers/astProvider.ts#L102

We run it with a second parameter, but setting that one to `undefined` instead doesn't change a thing.

So it seems to be the parser, but so far I failed to get it stuck from the parser test suite directly. Tried to use the old tagged parser version we're using in here too.

**Comment by Yarith** [comment]
I was able to get it stuck in the tree-sitter-elm testsuite.
I have written all test cases for all findings in this issue and you can download it here:
[case_incomplete_issue527.txt - 13 KB](https://github.com/elm-tooling/elm-language-server/files/6017492/case_incomplete_issue527.txt)

These are the test cases of the file:
```
Case without branches followed by newline
Case without branches directly on file end without comment before update
Case without branches directly on file end with comment before update
Case without branches leading with one line comment at file end
Case without branches leading with one line comment + newline
Case without branches followed by new line + space + comment
Case without branches followed by new line + without space + last line comment
Case followed by comment: not fully indented
Case followed by comment: indented as sibling
Case followed by comment: indented inside case
Case followed by comment: indented inside case branch
```

I have not run the tests in the master/v5.0.0 branch yet, because i don't know if the structure of the syntax tree has changed.

To be able to compile tree-sitter-elm@v4.5.0 and run the test i had to do following steps on my computer:

# How to build and run tests on tree-sitter-elm

## Windows

I did the steps in another order, because the npm install told me one by one which component was missing.

1. Clone repository: `git clone https://github.com/elm-tooling/tree-sitter-elm.git -b v4.5.0`
2. Enter directory: `cd tree-sitter-elm`
3. Make sure python is installed and in PATH environment variable
   It seems it is getting found if it is installed in: C:\Python27 or C:\Python37
   You can test PATH with `where.exe py`
4. Install Visual Studio with `C++ Corefeatures`, `Windows SDK` and `MSVC Buildtools` for your platform
5. Execute `npm install`
   You could have skipped 3 and 4, because the install process tells you one by one which component is missing.
6. Make sure that `.\node_modules\tree-sitter-cli\tree-sitter.exe` exists, if not then do:
```batch
cd .\node_modules\tree-sitter-cli\
node .\install.js
cd ..\..
```
7. Maybe this step is unnecessary:
   Because the tree-sitter.exe was missing i tried to execute `npm run build` in hope that it installs the `tree-sitter.exe`.
   `npx tree-sitter` was failing with: ENOENT
8. Run test with `npx tree-sitter test`

**Comment by Razzeee** [comment]
Found and fixed the problem. Not sure if we should extend the test suite, as it should never show up again.

**Comment by Razzeee** [comment]
Probably also https://github.com/elm-tooling/elm-language-server/issues/484 and therefore kind of a duplicate
