### ISSUE TITLE
Add install instructions to README.md

### ISSUE THREAD

**Issue by jssee** [elm-tooling/elm-language-server#53]
There is no mention of installing the `elm-language-server` executable in the readme, there's no releases available either. The closest thing there to install instructions is the editor support section, but without the executable available those wont work (I've tried). 

Installation instructions seem like a pretty standard thing to include in a readme, some might say its the most important thing. If there's a reason they are _not_ present, than this readme should at least include a note addressing the exclusion of them.

**Comment by andys8** [comment]
@razzeee vscode client is publicly available. Maybe release the current server as it is, too? It makes installation more approachable and more people will provide feedback.

**Comment by Razzeee** [comment]
I hoped to get https://github.com/elm-tooling/elm-language-server/pull/46 working before we push the first version to npm. As the rebuilding/downloading is not very nice.

**Comment by jssee** [comment]
@Razzeee we can add a note explaining how things might change in the future, if you think itll be helpful. I'll close this issue for now 👍🏾
