### ISSUE TITLE
Strange behaviors between windows and macos

### ISSUE THREAD

**Issue by theothornhill** [elm-tooling/elm-language-server#546]
Hi!
I'm having some issues between mac and windows with `elmLS`, and have made an issue over at https://github.com/joaotavora/eglot/issues/638 showing the behavior I'm struggling with. 

I'll attach the transcripts from the lsp-log here:
[eglotlog.txt](https://github.com/elm-tooling/elm-language-server/files/6084738/eglotlog.txt)
[lsplog.txt](https://github.com/elm-tooling/elm-language-server/files/6084739/lsplog.txt)
[eglotlogmac.txt](https://github.com/elm-tooling/elm-language-server/files/6084780/eglotlogmac.txt)

## Expected Behavior
`elmLS` shouldn't send incorrectly parsed tokens back to the client so that it can show diagnostics reliably

## Current Behavior
On windows it shows the "erratic" behavior described in https://github.com/elm-tooling/elm-language-server/issues/503

## Possible Solution
Not sure, but it seems like 

## Steps to Reproduce (for bugs)

1. go to https://github.com/joaotavora/eglot/issues/638
2. follow the steps shown in the gifs there

## Context
This only happens on windows with eglot, eglot on mac is fine, and lsp-mode works both places.
(eglot supports incremental sync, but batches requests, rather than sending them one by one)

## Your Environment

* Version used: latest master and 2.0.3 release
* Editor used: emacs with both lsp-mode and eglot.
* Environment name and version (e.g. node.js 5.4): node 12.13 on windows and 15.8.0 on mac
* Operating System and version: windows and mac osx (M1)

**Comment by theothornhill** [comment]
It seems elmLS is particular about paths in URI, and that the drive part of the path needs to be hexified.
https://github.com/joaotavora/eglot/pull/639 fixes this issue, so it seems like it isnt really a bug with elmLS. 

Out of interest, maybe you still could offer some insights as to why the server returns these garbled values as shown in #503 when «:» isnt converted to «%3A»?

**Comment by Razzeee** [comment]
Glad you found this.

I tried to come up with an explanation, but it seemed rather arbitrary. Don't want to add confusion, so best would be to attach a node debugger to your server and maybe step into `astProvider`.

**Comment by theothornhill** [comment]
Thanks for coming back to me.

PR is pushed to eglot now, so I think we can close this. I may go down the debugger route some day :)

I think this can be closed now.
