### ISSUE TITLE
Running elm-format failed

### ISSUE THREAD

**Issue by wandyirawan** [elm-tooling/elm-language-server#553]
## Expected Behavior

when save on vs code, elm code format run

## Current Behavior

show error install elm-format via 'npm install -g elm-format

## Context

i have change my npm global folder to ~/.npm-global, and add it to $PATH in my .profile, 
i have try add it at settings on vs code plugin but nothing help.

## Your Environment

* Version used:2.0.3
* Editor used: visual studio code 
* Environment name and version (e.g. node.js 5.4):  14.15
* Operating System and version: manjaro

**Comment by Razzeee** [comment]
I would suggest installing elm-format via https://elm-tooling.github.io/elm-tooling-cli/

**Comment by wandyirawan** [comment]
> I would suggest installing elm-format via https://elm-tooling.github.io/elm-tooling-cli/

i have try using elm-tooling and start new app with it. still formating on visual code not working.  i will try reinstall vscode to opensource version.

**Comment by wandyirawan** [comment]
case close, this because error code. elm format cant format if code is error. 
when i run elm-format on terminal. elm-format show what wrong in my code  like: 
```

Processing file Counter.elm
Unable to parse file Counter.elm:35:1 To see a detailed explanation, run elm make on the file.

```
better than : install elm-format via 'npm install -g elm-format

**Comment by Razzeee** [comment]
Ah, sorry. Forgot about https://github.com/elm-tooling/elm-language-server/commit/6a6585e858b9970cf72053f81095eaf22ff13091 and that it's not released yet.
