### ISSUE TITLE
elm-analyse.json "excludedPaths" setting compared against absolute file paths

### ISSUE THREAD

**Issue by mcasper** [elm-tooling/elm-language-server#559]
Hey folks 👋 . This issue may be more appropriate on the language server repo itself, but I wanted to sanity check myself and start here.

## Expected Behavior
When using elm-language-client-vscode, setting a relative directory in elm-analyse.json's `excludedPaths` should cause the elm language server to ignore diagnostics for that directory or file.

e.g.
```json
# elm-analyse.json

{
  "excludedPaths": {
    "./src/Generated"
  }
}
```

## Current Behavior
In practice, with a setting like above, diagnostics for that directory are still reported and shown in the editor. This is because the filepath that is being compared to those prefixes is an absolute filepath.

## Possible Solution
Compare excludedPaths prefixes against filepaths relative to the `elm.json` or `elm-tooling.json` directories.

## Steps to Reproduce (for bugs)
I've created a minimal repo for repro.

https://github.com/mcasper/elm-ls-vscode-bug-report
1. `git clone git@github.com:mcasper/elm-ls-vscode-bug-report`
2. Open in vscode with this extension activated
3. Observe the diagnostic warning produced for `Warnings.elm`
4. Update `elm-analyse.json` to the absolute path to the file, e.g.
```json
# elm-analyse.json

{
  "excludedPaths": {
    "/path/to/cloned/repo/src/Warnings.elm"
  }
}
```
5. Restart the language server
6. Observe that the diagnostic warning is properly repressed

## Context
elm-analyse's configuration docs: https://stil4m.github.io/elm-analyse/#/configuration
What I assume are the offending lines: https://github.com/elm-tooling/elm-language-server/blob/main/src/providers/diagnostics/elmLsDiagnostics.ts#L430-L432

## Your Environment
* VSCode 1.54.3
* MacOS 11.2.3
* elm 0.19.1
* elmtooling.elm-ls-vscode v2.0.3

**Comment by Razzeee** [comment]
Thanks for the clear report and the repro 👍🏻

**Comment by mcasper** [comment]
Thank you very much!
