### ISSUE TITLE
Types wrongly reported as not in use

### ISSUE THREAD

**Issue by Augustin82** [elm-tooling/elm-language-server#563]
The language server erroneously reports some types as not being used while they are.

## Expected Behavior
When types are exposed and used elsewhere, they should not appear as "unused".

## Current Behavior
In my `Model.elm` file, some exposed types are reported as being unused whil they are used in the `Main.elm` file.

## Possible Solution
No idea!

## Steps to Reproduce (for bugs)
Here is a repository where I have been able to reproduce the bug using nvim + CoC.
My colleague is using VSCode and has reproduced it with that repo.
https://github.com/Augustin82/repro

## Your Environment
* Version used: 2.1.0
* Editor used: both nvim and VSCode
* Environment name and version (e.g. node.js 5.4): nodejs 12
* Operating System and version: Ubuntu 20.04

**Comment by jfmengels** [comment]
There was a similar issue in `elm-review-unused`'s `NoUnused.Variables`, and the issue was that the types were (wrongly) not considered as used when they're exposed with `exposing (..)`. It might be a different issue for this project, but I hope this helps.

**Comment by Razzeee** [comment]
Seems like we just need to do https://github.com/elm-tooling/elm-language-server/pull/544/files for `type alias` too
