### ISSUE TITLE
`{} ->` presents an error instead of a warning

### ISSUE THREAD

**Issue by david-nimmo-mind-gym** [elm-tooling/elm-language-server#572]
## Expected Behavior

when doing: 

```
case something of 
  Something {} -> 
```
the `{}` should be reported as a warning

## Current Behavior

the above is reported as an error, but the code still compiles.

## Steps to Reproduce (for bugs)

1. As noted above
2.
3.
4.

## Context

Minor issue, but as we're introducing new people to Elm it has been the source of confusion that something reported as an error still compiled.

## Your Environment

* Version used: 2.0.3
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.54.3
* Environment name and version (e.g. node.js 5.4): Node 12.8.1
* Operating System and version: Mac OS Catalina 10.5.7

**Comment by Razzeee** [comment]
I'm not able to replicate this with current main branch
