### ISSUE TITLE
Not working with kak-lsp

### ISSUE THREAD

**Issue by jaredramirez** [elm-tooling/elm-language-server#574]
## Expected Behavior
When running elm-language-server with kak-lsp, should display errors, show hints, etc.

## Current Behavior
ELS is failing to compile elm & can't find an input file. In the `debug` buffer of kakoune, it errors with:
```                                                                                                  
  5│ LSP: Loading Elm tree-sitter syntax from ../../../../../../../nix/store/82ysym9hak1f1avisyqpl6m3l3ys1rq3-node__at_elm-tooling_slash_elm-language-server-2.0.2/lib/node_modules/@elm-tooling/elm-language-server/out/tree-sitter-elm.wasm
  6│ LSP: Found 1 elm.json files for workspace /home/jared/dev/github/replenysh/core/dashboard                                                                                
  7│ LSP: Found 1 unique elmWorkspaces for workspace /home/jared/dev/github/replenysh/core/dashboard                                                                          
  8│ LSP: Starting language server for folder: file:///home/jared/dev/github/replenysh/core/dashboard                                                                         
  9│ LSP: Elm version 0.19.1 detected.                                                                                                                                        
 10│ LSP: Reading elm.json from /home/jared/dev/github/replenysh/core/dashboard/elm.json                                                                                      
 11│ LSP: {"shortMessage":"Command failed with exit code 1: ./node_modules/.bin/elm make","command":"./node_modules/.bin/elm make","exitCode":1,"stdout":"","stderr":"-- NO INPUT --------------------------------------------------------------------\n\nWhat should I make though?  I need specific files like:\n\n    elm make src/Main.elm\n    elm make src/This.elm src/That.elm\n\nI recommend reading through https://guide.elm-lang.org for guidance on what to\nactually put in those files!\n\n","failed":true,"timedOut":false,"isCanceled":false,"killed":false}
 12│ LSP: Glob /home/jared/dev/.../src/elm/**/*.elm 
 13| LSP: Glob ... // All my other dependencies
```

## Steps to Reproduce (for bugs)
Download & setup elm-language-sever and kak-lsp as described in the documentation.

## Context
Just trying to get a great editor experience with Elm!

My `elm-tooling.json` file looks like:
```
{
    "entrypoints": ["./src/elm/Main.elm"]
}
```

## Your Environment
* ELS Vesrion: 2.02
* Editor used: Kakoune v2020.09.01
* Environment name and version (e.g. node.js 5.4): Node v12.20.2
* Operating System and version: MacOS Big Sur 11.2.3
* Kak-LSP Version: 8.0.0

**Comment by Razzeee** [comment]
Hrm, where's the error? 11? That's expected, as we use that to download
your dependencies via elm make.

Jared Ramirez ***@***.***> schrieb am Mi., 14. Apr. 2021,
01:33:

**Comment by phi1-h** [comment]
I have the same Problem, maybe the entrypoints don´t get passed to the lsp?
`elm make $path_to_main` works just fine.

**Comment by Razzeee** [comment]
As stated, the make erroring is intended, it's used to download dependencies, as there is unfortunatly no other way to do that via the elm bin.

**Comment by phi1-h** [comment]
Thanks for your fast answer Razzeee!
`LSP: {"shortMessage":"Command failed with exit code 1: elm make","command":"elm make","exitCode":1,"stdout":"","stderr":"-- NO INPUT --------------------------------------------------------------------\n\nWhat should I make though? I need specific files like:\n\n    elm make src/Main.elm\n    elm make src/This.elm src/That.elm\n\nI recommend reading through https://guide.elm-lang.org for guidance on what to\nactually put in those files!\n\n","failed":true,"timedOut":false,"isCanceled":false,"killed":false}
`
The error is 1 not 11.
If it's still intended what do I need to do to resolve the error?
Or should I ignore it?
Thanks again!

**Comment by Razzeee** [comment]
If that's from initalization (hard to tell without context) it should be fine and is indeed expected.
You can't resolve the error, as we accept that it errors and it shouldn't matter. All other clients also have this error happening.

**Comment by phi1-h** [comment]
OK, thanks.
Unfortunatly the lsp does still not work with kak. 
I see a `Language Server is not initialized, parking request` message in kak.
In the logs I see the following (more than once):
```
DEBG From server:     {
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "capabilities": {
      "codeActionProvider": {
        "resolveProvider": true
      },
      "codeLensProvider": {
        "resolveProvider": true
      },
      "completionProvider": {
        "triggerCharacters": [
          "."
        ]
      },
      "definitionProvider": true,
      "documentFormattingProvider": true,
      "documentSymbolProvider": {
        "label": "Elm"
      },
      "executeCommandProvider": {
        "commands": [
          "elmLS.elmMakeFixer-31441738b83b532d52a0de932b51e61b",
          "elm.installPackage"
        ]
      },
      "foldingRangeProvider": true,
      "hoverProvider": true,
      "referencesProvider": true,
      "renameProvider": {
        "prepareProvider": true
      },
      "selectionRangeProvider": true,
      "textDocumentSync": 2,
      "workspaceSymbolProvider": true,
      "workspace": {
        "fileOperations": {
          "didCreate": {
            "filters": [
              {
                "scheme": "file",
                "pattern": {
                  "glob": "**/*.elm",
                  "matches": "file"
                }
              }
            ]
          },
          "willRename": {
            "filters": [
              {
                "scheme": "file",
                "pattern": {
                  "glob": "**/*.elm",
                  "matches": "file"
                }
              },
              {
                "scheme": "file",
                "pattern": {
                  "glob": "**/",
                  "matches": "folder"
                }
              }
            ]
          },
          "willDelete": {
            "filters": [
              {
                "scheme": "file",
                "pattern": {
                  "glob": "**/*.elm",
                  "matches": "file"
                }
              }
            ]
          }
        }
      },
      "linkedEditingRangeProvider": true
    }
  }
}
}, module: `kak_lsp::language_server_transport:157`

 ERRO panic: panicked at 'Failed to parse response: 
Error("invalid type: map, expected a boolean", line: 0, column: 0)', src/context.rs:127:64, module: kak_lsp:262
```

The context.rs region:
```        
self.batches.insert(
            batch_id,
            (
                ops.len(),
                Vec::with_capacity(ops.len()),
                Box::new(move |ctx, meta, vals| {
                    let results: Vec<R::Result> = vals
                        .into_iter()
                        .map(|val| serde_json::from_value(val).expect("Failed to parse response"))
                        .collect();
                    callback(ctx, meta, results)
                }),
            ),
        );
```
https://github.com/kak-lsp/kak-lsp/blob/master/src/context.rs

Is there something I can do to solve this? Report to kak-lsp?
After this I'll give up and leave you alone ;)

**Comment by Razzeee** [comment]
I think it makes sense to talk to the kak-lsp people, as other clients seem to work fine and their client seems to panic for some reason. They will also likely have an easier time to tell why that is.

**Comment by Razzeee** [comment]
Not sure, but I think it's on their side, let's wait.

**Comment by krobelus** [comment]
> Kak-LSP Version: 8.0.0

That version is quite old, did I mess up the macOS release in January? I thought pushing to https://github.com/kak-lsp/homebrew-kak-lsp was enough, I'm not sure.

I'll take a look at the kak-lsp report.
It looks like some clients send just `"true"` for the `linkedEditingRangeProvider` capability instead of a nested object. I'll investigate.

**Comment by krobelus** [comment]
Ok the spec says that `"true"` is valid`

`linkedEditingRangeProvider?: boolean | LinkedEditingRangeOptions | LinkedEditingRangeRegistrationOptions;`

so this is a bug in `lsp-types`, the library `kak-lsp` uses. I'll submit a fix and report the status in kak-lsp/kak-lsp#484. Sorry for the troubles and thanks for reporting.

**Comment by jaredramirez** [comment]
This is fixed on the kak-lsp side, thanks so much @krobelus!
