### ISSUE TITLE
Request: Offer alias imports in code actions for missing imports

### ISSUE THREAD

**Issue by BendingBender** [elm-tooling/elm-language-server#581]
When an import is missing, this plugin correctly flags the symbol that couldn't be resolved and when triggering a code action for the flagged error also correctly suggests to add a missing import or to add all missing imports.

## Expected Behavior
It would be very helpful if this tooltip could be extended to offer an option to import the missing module via an alias import.

## Current Behavior
The tooltip shown looks like the one in following image:
![grafik](https://user-images.githubusercontent.com/4807083/116428957-b2265b00-a845-11eb-9fda-79867902afa7.png)

## Possible Solution
Given an example like this (example includes highlighted errors):
```elm
module Test exposing (..)

value : Utils.Bem.Bem msg
--      ^^^^^^^^^^^^^
value = Utils.Bem.block "foo"
--      ^^^^^^^^^^^^^^^
```

the code action for the error in the last line should have an additional entry `Import module "Utils.Bem" as "Bem"`. When selected, the code action should alter the code in the following way:

```elm
module Test exposing (..)
import Utils.Bem as Bem

value : Bem.Bem msg     -- note that the previous full module name was replaced with the new alias
value = Bem.block "foo" -- note that the previous full module name was replaced with the new alias
```

## Context
The need to alias module names arises regularly when importing deeply nested modules.

## Your Environment

* Version used:
* Editor name and version (e.g. VSCode 1.36.1): 
* Environment name and version (e.g. node.js 5.4):
* Operating System and version:

**Comment by BendingBender** [comment]
@Razzeee I'd like try to implement it myself, any pointers on where I can start with this? Or do you think that this is too complex for someone not familiar with the code base?

**Comment by Razzeee** [comment]
I think you might want to start with the tests then. Then have a look at how https://github.com/elm-tooling/elm-language-server/blob/4e6746518f5a73e3add1a04f82c812b56a8f1c5f/src/providers/codeAction/importCodeAction.ts#L41 handles this and work backwards from there. Feel free to ask questions.
