### ISSUE TITLE
Incorrect "Could not find module to import named ..." error on long file path

### ISSUE THREAD

**Issue by bwells** [elm-tooling/elm-language-server#589]
I'm receiving an incorrect import error diagnostic `Could not find module to import named 'Request.AssignedTests.CreateAssignedTest' in 'dependencies' or 'source-directories'`

## Expected Behavior
`elm-language-server` reports no import error. 
`elm-language-server` warning matches `elm make` output.

## Current Behavior
elm-language-server reports an import error that does not match CLI `elm make` usage. I am able to build this code via `elm make` with zero errors or warnings. Additionally, other first party code within this source structure is imported without warning. 

## Possible Solution
This seems to be related to the file path length of the import. If I refactor the module from `Request.AssignedTests.CreateAssignedTests` to `Request.Asts.Cats` the import error is no longer reported.

## Steps to Reproduce (for bugs)
1. clone https://github.com/bwells/els-error
2. view `src/Main.elm` to observe import warning error
3. `elm make src/Main.elm` to confirm that the import warning is incorrect

## Context
This is an annoyance, in that I must navigate around incorrect warnings, but I am still able to use elm-language-server in day to day work. 

## Your Environment
* Version used: elm-language-server 2.1.0
* Editor used: Neovim nightly with included LSP client and ALE LSP client.
* Environment name and version (e.g. node.js 5.4): node 16.0.0
* Operating System and version: MacOS 11.3 on ARM

Thanks in advance for the help and for the work that has already gone into elm-language server.

**Comment by Razzeee** [comment]
Can confirm you example to reproduce, even with the lastest version.

**Comment by Razzeee** [comment]
The problem is the path of the file, which ends up as a test dependency due to it having `tests` in the path.

https://github.com/elm-tooling/elm-language-server/blob/main/src/compiler/program.ts#L628

**Comment by bwells** [comment]
Oof. Well I work for a company that offers tests, as in exams, so getting rid of the word "test" in our codebase definitely isn't going to be feasible.

**Comment by Razzeee** [comment]
Agreed, our test handling isn't as nice as it could/should be.
There are some other tickets already tracking it https://github.com/elm-tooling/elm-language-server/issues/497 for e.g.

**Comment by bwells** [comment]
I'm able to run a custom build with a one line patch to essentially disable test detection support, so that has me sorted. Improved test handling would certainly be nice, but my two cents is it's not implementing any sort of interim solution on my account.

**Comment by Razzeee** [comment]
Great, that it's not blocking you. But as we're working on more test stuff, we should hopefully be able to improve this too.
