### ISSUE TITLE
Partially working with elm-ui, via neovim's lsp-config

### ISSUE THREAD

**Issue by aotarola** [elm-tooling/elm-language-server#595]
`elm-language-server` is partially inspecting certain libraries, in this case, `elm-ui`

## Expected Behavior
`elm-language-server` should be able to discover definitions for `import Element exposing (..)`

## Current Behavior
`elm-language-server` is not able to discover definitions for `import Element exposing (..)`

## Steps to Reproduce (for bugs)
1. load up `lsp-config` with [elmls](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#elmls)
2. Install elm-ui : `elm install mdgriffith/elm-ui` 
3. Write a simple elm code
```elm
module Main exposing (main)

import Element exposing (none, text, layout)
import Element.Region exposing (heading)
import Html exposing (Html)


main : Html msg
main =
    layout [] <| text "test"

```

The following is the output of `elm-language-server` in neovim:

![Screen Shot 2021-05-11 at 7 59 38 PM](https://user-images.githubusercontent.com/1557740/117913383-e4ed3c00-b2a6-11eb-87f7-1e289cb2010c.png)

## Context

What is super interesting is that `elm-language-server` is able to see other namespaces such as `import Element.Region exposing (heading)`. 

## Your Environment

* Version used: 2.1.0
* Editor used: neovim  v0.5.0-dev+61aefaf29
* Environment name and version (e.g. node.js 5.4): node.js 14.15.3 
* Operating System and version: OSX Big Sur 11.3.1

**Comment by Razzeee** [comment]
Seems fine in vscode 

![image](https://user-images.githubusercontent.com/5943908/117938215-15fd5900-b307-11eb-918e-9d20467b2eb2.png)

**Comment by aotarola** [comment]
Oh, I forgot to mention that it works on VSCode 😓 , thanks @Razzeee 

what is the best way that I can debug this issue?

**Comment by Razzeee** [comment]
There should be an option to output logs. If the server returns the correct data the client somehow screws it up

**Comment by Razzeee** [comment]
maybe the solution from https://github.com/elm-tooling/elm-language-server/issues/598 helps?

**Comment by aotarola** [comment]
@Razzeee I just tried version `2.2.0` with my current configuration and it works 🎉 . It seems that the issue happens when using version `2.1.0` only (I tried both versions just to confirm). I believe we can safely close this out, Thanks!!! 💚
