### ISSUE TITLE
False positive List.concat hint

### ISSUE THREAD

**Issue by matheus23** [elm-tooling/elm-language-server#605]
![image](https://user-images.githubusercontent.com/1430958/121411590-16b7f800-c964-11eb-9dd1-8c039e31f17f.png)
```elm
test =
    let
        aList =
            if True then
                [ 2, 3 ]

            else
                []
    in
    List.concat
        [ [ 1 ]
        , aList
        , [ 4 ]
        ]
```

## Expected Behavior

No warnings.

## Current Behavior

ElmLS gives me a warning on the `List.concat` expression:

> You should just merge the arguments of `List.concat` to a single list. - ElmLS

## Possible Solution

don't show warnings in these cases. (Optimize for having false negatives sometimes, instead of having false positives sometimes?)

## Steps to Reproduce (for bugs)

1. Paste the code above into e.g. VSCode and wait for ElmLS to scan the file & report warnings

## Your Environment

* Version used: 2.1.0
* Editor used: VSCode 1.56

**Comment by Razzeee** [comment]
Seems like `UnnecessaryListConcat` has a bug. https://stil4m.github.io/elm-analyse/#/messages/UnnecessaryListConcat
Seems fine in elm-analyse, so must be on our side.
