### ISSUE TITLE
LSP problem with parsing elm files in VIM

### ISSUE THREAD

**Issue by mishaszu** [elm-tooling/elm-language-server#611]
## Expected Behavior

I expect the language server to display correct hints according to warnings and errors.

## Current Behavior

It's pretty much the same as described in [this issue](https://github.com/elm-tooling/elm-language-server/issues/503). I got a lot of errors on the valid elm code.
The biggest difference is I use VIM with `coc` and `elm-language-server`  instead of Neovim.
I did vim setup according [elm-vim](https://github.com/elm-tooling/elm-vim) and [elm-tooling/elm-language-server](https://github.com/elm-tooling/elm-language-server).
Here is an example snippet:
```elm
initModel = -- Parsing error .
    { photos =
        [ { url = "1.jpeg" } -- Parsing error .
        , { url = "2.jpeg" } -- Parsing error .
        , { url = "3.jpeg" }
        ]
    , selectedUrl = "1.jpeg"
    }
```
The problem is frequent. It appears after any change spawning random errors, often in different places after save.
I don't use `nvim-lspconfig` and I can't reuse the solution from the ticket I linked.

## Possible Solution

As mentioned in the linked issue elm LSP requires incremental buffer updates. I can't figure out if that's exactly the same problem or how potentially turn it with `coc` for elm (no other LSP I use has the problem).

## Steps to Reproduce (for bugs)

1. Setup LSP with [elm-language-server guide](https://github.com/elm-tooling/elm-language-server)
2. Add [elm-vim]() with vim-plug 
3. Change any elm file

## Context

I'm not able to write elm productively at all with VIM (my main code editor).

## Your Environment

* Version used: 2.2.0
* Editor used: VIM 8.2.3036
* Environment name and version (e.g. node.js 5.4): node 14.16.1; npm 7.18.1
* Operating System and version: Ubuntu 20.04 & Ubuntu 20.04 in WSL

**Comment by mishaszu** [comment]
I disabled Ale for Elm files and it seems fixed the problem.
I checked if problem is caused by enabling Ale and CoC at the same time, but it seems in every configuration problem is caused by Ale. After disabling Ale it works for both vim and neovim configured with CoC.
As the issue was describing the problem with CoC configuration I assume it's solved.

**Comment by Razzeee** [comment]
Thanks for getting back, was really confused by this.
