### ISSUE TITLE
Incorrect type inference for records applied to lists of functions

### ISSUE THREAD

**Issue by SiriusStarr** [elm-tooling/elm-language-server#620]
SSCCE:
```elm
func r =
    List.map ((|>) r) [ \{ foo } -> foo, \{ bar } -> bar ]
```
## Expected Behavior

```elm
func : { a | foo : b, bar : b } -> List b
func r =
    List.map ((|>) r) [ \{ foo } -> foo, \{ bar } -> bar ]
```

## Current Behavior
```elm
func : { a | foo : b } -> List b
func r =
    List.map ((|>) r) [ \{ foo } -> foo, \{ bar } -> bar ]
```

## Additional Observations

Only the **first** function (by order in the list) will be used for the type inference, no matter the number.  A few more examples with their incorrect inferences are provided here to illustrate:

```elm
f1 : { a | foo : b } -> List b
f1 r =
    List.map ((|>) r)
        [ \{ foo } -> foo
        , \{ bar } -> bar
        ]


f2 : { a | bar : b } -> List b
f2 r =
    List.map ((|>) r)
        [ \{ bar } -> bar
        , \{ foo } -> foo
        ]


moreThanTwo : { a | bar : b } -> List b
moreThanTwo r =
    List.map ((|>) r)
        [ \{ bar } -> bar
        , \{ foo } -> foo
        , \{ baz } -> baz
        ]
```

My assumption is that only the type of the **first** element in a list is looked at to determine the type of the list, but this is insufficient if the first element has the inferred type of an extensible record.

Interestingly enough, it looks like more than one element is checked for other cases where the first might be ambiguous, e.g.

```elm
number : Float -> List Float
number i =
    List.map ((|>) i)
        [ (+) 1
        , (/) 2
        ]
```

is correctly inferred as `Float` not as `number`, which is what would be determined from only the first element.

## Context

This seems contrived, but it came up while writing tests, using [`Expect.all`](https://package.elm-lang.org/packages/elm-explorations/test/latest/Expect#all), e.g.

```elm
import Expect

expect =
    Expect.all
        [ \{ foo } -> Expect.equal 1.1 foo
        , \{ bar } -> Expect.equal "2" bar
        ]
```

will infer as 

```elm
expect : { a | foo : Float } -> Expect.Expectation
expect =
    Expect.all
        [ \{ foo } -> Expect.equal 1.1 foo
        , \{ bar } -> Expect.equal "2" bar
        ]
```

rather than the correct

```elm
expect : { a | foo : Float, bar : String } -> Expect.Expectation
expect =
    Expect.all
        [ \{ foo } -> Expect.equal 1.1 foo
        , \{ bar } -> Expect.equal "2" bar
        ]
```

## Your Environment

* Version used: elmtooling.elm-ls-vscode v2.2.0
* Editor used: VS Code v1.57.1 
* Operating System and version: NixOS

**Comment by Razzeee** [comment]
I've tested this in the intelliJ implementation of type inference and it seems to also have this problem.
