### ISSUE TITLE
'getTree' of undefined

### ISSUE THREAD

**Issue by ni-ko-o-kin** [elm-tooling/elm-language-server#624]
_While writing the issue I already found the problem, but maybe someone else gets stuck on the same error and this issue can save him/her some time, so I post it anyway:_

After updating from elm-tooling v1 to v2 I get this error:

Error (before-save-hook): Error running hook "format-all-buffer--from-hook" because: (**error Request textDocument/formatting failed with message: Cannot read property ’getTree’ of undefined (Internal Error)**)

Not only does the formatting not work, any other lsp related requests do not work.

## Expected Behavior
after saving the file the buffer should be formatted

## Current Behavior
the above error occures

## Context
I have no idea how to fix this. I would appreciate any hint how to tackle this.
* The other lsp's (javascript, aso) work without any problem.
* lsp-mode for emacs supports all feautres from the lsp-protocol 3.14
* 

## Your Environment
* Version used: 2.2
* Editor used: emacs 27.2, doom 3.0.0
* Environment name and version: node 14.17.5
* Operating System and version: ubuntu 20.04

**Comment by ni-ko-o-kin** [comment]
Solution: make sure you have installed elm :roll_eyes:

Maybe the LS can check if elm is installed and return "elm is not installed" instead of "'getTree' of undefined".
Otherwise, it should be pretty obvious that the LS need the language to be installed to work.

**Comment by razzeee** [comment]
Yeah, there was a problem, that kept our infrastructure from showing the correct popup :)
