### ISSUE TITLE
elm-language-server won't work with vim/ALE

### ISSUE THREAD

**Issue by jpalardy** [elm-tooling/elm-language-server#635]
Hi there!

Thanks for elm-language-server! It works great with vscode 😄 

On the other hand, it seems broken with vim + ALE… here's what I found:

## Research

ALE doesn't send the `range` property … it always send the whole file. (not the best, but simple)

![Screen Shot 2021-09-15 at 23 35 01](https://user-images.githubusercontent.com/18142/133561956-d953f387-306d-4941-95d6-715529378f51.png)

Meanwhile, LSP makes some assumptions about the message fields:

![Screen Shot 2021-09-15 at 23 36 42](https://user-images.githubusercontent.com/18142/133562253-870b6fba-cf6c-4d53-b68b-a2796a1befc1.png)

(although, I didn't follow all the code here, I'll defer to you)

The [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/) seems to allow for optional `range` (possibly for backward compatibility?)

![Screen Shot 2021-09-15 at 23 40 57](https://user-images.githubusercontent.com/18142/133562903-46630628-c23c-47a4-b2ac-9cc6e56db3c5.png)

## Steps to Reproduce (for bugs)

1. open elm file with vim
2. make a change
3. see everything become a "parsing error"

## Your Environment

* Version used: 2.2.1
* Editor used: vim 8.2
* Environment name and version (e.g. node.js 5.4): node v16.9.1, npm 7.21.1
* Operating System and version: macos (and linux in vagrant)

**Comment by jpalardy** [comment]
If you need any more information, or want me to try something — I'll be available.

Let me know — and thanks again!

**Comment by jpalardy** [comment]
Saw #503, which sent me down the rabbit hole 😅

**Comment by razzeee** [comment]
Interesting, I actually thought the server has the last word via https://github.com/elm-tooling/elm-language-server/blob/main/src/capabilityCalculator.ts#L45

https://microsoft.github.io/language-server-protocol/specification#textDocument_synchronization_sc

**Comment by jpalardy** [comment]
Ah… might be ^

2 thoughts:
- isn't accepting "the whole file content" easier? (I'm willing to pitch it, if that helps)
- what if ALE "cheated" and sent a `range` that covered the whole file — would that work? (I might need some help on what exact values to pass).  If we can make this work, I'll push the patch on ALE on my side (no changes for this repo)

**Comment by razzeee** [comment]
Well, accepting the whole file is bad for performance, it should be easier and in fact, I think we did it before. But internal APIs might still need the correct diff or be patched.

I see no reason, faking it in ALE wouldn't work. Other then the performance not being good, but still better then just breaking :)

**Comment by jpalardy** [comment]
It's worth a shot 😄 

I was reading [Range](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#range) and I'll setup a test on my setup.

I might have to dig deeper into edge conditions (what happens if range is too small/too big? …).

I'll update this thread with what I find.

**Comment by jpalardy** [comment]
Tried to brute force ALE:

![Screen Shot 2021-09-21 at 21 14 55](https://user-images.githubusercontent.com/18142/134282737-3dc15273-a2a2-48bc-8716-f6c6bcecba98.png)

I initially tried to use `end.line` at 999999, but that wasn't working. Then I tried at line counts close to (accounting for off-by-one, etc) and that _ALMOST_ works… (ALE highlighted an error on the last line 😩  , other errors were correct and on the right line too!)

The problem is that the `buffer` passed in is the current buffer, without the previous state. So, passing in the previous `end.line` would require keeping more state between calls to account for additions and deletions…

Meanwhile, I stumbled on this code relating to tsserver:

![Screen Shot 2021-09-21 at 21 16 01](https://user-images.githubusercontent.com/18142/134283136-f564e559-963a-4775-948e-ac1393f2e039.png)

oh, the irony…

Thoughts?

**Comment by jpalardy** [comment]
Another quick test … keeping line count in a global (… I know) variable:

![Screen Shot 2021-09-21 at 21 43 38](https://user-images.githubusercontent.com/18142/134284775-837fd0d2-4949-4dea-a17d-236a5da0939c.png)

and it works!  (of course, not exactly battle-tested)

**Comment by razzeee** [comment]
Is the character end guaranteed to be at 0?

Jonathan Palardy ***@***.***> schrieb am Mi., 22. Sept. 2021,
06:45:

**Comment by jpalardy** [comment]
I picked it up from [the spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#range).

![Screen Shot 2021-09-21 at 23 21 22](https://user-images.githubusercontent.com/18142/134292948-5a1ba7a2-a9ee-4478-8920-d38142c2ed68.png)

- zero-based
- exclusive
- document end at `line: $line_count, character: 0`   // since a 36-line document, goes from 0..35, line 36 is the first line after...

**Comment by razzeee** [comment]
Makes sense

**Comment by jpalardy** [comment]
Hi @razzeee 

Now that elm-ls is running again, I realize how much I've missed this 😄 

I believe the solution belongs in elm-ls, rather than patched elsewhere, since it could fix this for other clients (not just vim + ALE) as well.

What I was thinking was to:
- grab the whole text when `range` is missing (as per spec)
- or, if that doesn't work, "fake" the range like I did in the client…

Multiple options:
- did you want to take a stab at it?
- did you want me to take a stab at it? (longer … not necessarily better either)
- did you want the fix in ALE? (no guarantees, I could open a PR there to discuss)

Let me know

**Comment by razzeee** [comment]
We should at least let ALE know/check if they have issues tracking incremental support.

I would prefer if you could take a look and implement it, but feel free to reach out anytime.

**Comment by jpalardy** [comment]
Sounds good ^

I've been using my patched version since last night and it's … a bit unstable. There seems to be a race-condition when I edit a line and save right away. Forcing another write seems to fix it most times 🤷 

I'll set myself with your code and see what I can come up with. (this might take a while)

**Comment by jpalardy** [comment]
Hi @razzeee 

I had some time to set up and experiment. I did the "easiest" thing: I migrated the line counting logic to the server.

![naive-diff](https://user-images.githubusercontent.com/18142/134798241-af0ce8d9-c208-4f85-8377-8925ef649c9b.png)

It's a bit raw (I'm not a typescript programmer; javascript/elm is my background) ^

- it re-uses the RegExp from `Utils.getIndicesFromRange`
- I'm not too happy with the duplication here (esp. the `tree?.edit` call)
- depending on how you feel, this could be done in a helper...

On the plus side, it works great on my machine. It seems more stable than the ALE patch I've been using since last week.

Did you want to use this as a starting point? Or did you want me to open a PR and iterate there?

**Comment by razzeee** [comment]
I think that would be fine, as it only affects the non range path anyway. A PR would be the best thing to do, I have some small things I would like code differntly (nothing functional).

I'm unsure if we should be doing this based on `range` or if we can know, that the client does not support incremantal sync and act according to that.

**Comment by jpalardy** [comment]
Let me open a PR and we'll fix it there 👍

**Comment by razzeee** [comment]
I think we can close this?
