### ISSUE TITLE
Introduce new argument to function from missing declaration

### ISSUE THREAD

**Issue by Gauteab** [elm-tooling/elm-language-server#636]
When a declaration is missing, it should be possible to introduce that as an argument to the enclosing function.

## Expected Behavior
When requesting an action, or fix, on a `Diagnostics.MissingValue`, there should be an option in the menu to introduce a new argument to the function.
It should also add the inferred type signature if the function already has a type annotation.

## Current Behavior
Requesting the fix only provides an option to `create local function`.

## Possible Solution

I have a work-in-progress implementation of a possible solution:
![Screen Recording 2021-09-16 at 4 03 06 PM](https://user-images.githubusercontent.com/25511262/133626556-380896ba-08c2-4abb-8008-6e3efb8706c7.gif)

## Context
This is really useful when you for example need to thread a value from the model through many functions and need to update arguments frequently.

## Other comments

I was surprised that `create local function` does not create a declaration within a let-block, but rather a new top level function. I can see there is an action for "external functions", but i'm not sure when this is triggered.
Would like to hear if i'm missing something here, or if there is some rework that should be done around these actions.

Would also like some input on some UX details like the name of the action in the menu.

**Comment by razzeee** [comment]
I would try to keep the label as short as possible. So `Add new parameter to function` might be better. I think we usually use the `parameter` wording, but I'm not sure if that's mostly in our code yet or also userfacing.

I think `local function` was the best name we could come up with for a new function in the current file. But yes, the naming is confusing, you might actually want to have the choice between both, if there is a let (or maybe even want to add one, but that might be too many actions most of the time?)

**Comment by Gauteab** [comment]
Alright, cool!

There are a few corner cases left to work out, but I'll try to make a PR soon, and I'll make a separate issue about the `create local function` thing once I've looked into it a bit more :)
