### ISSUE TITLE
Language server fails to start if dependencies are not in ~/.elm folder

### ISSUE THREAD

**Issue by skovmand** [elm-tooling/elm-language-server#646]
First of all thank you for your work on this project!

I have moved to a new machine since I last worked on my elm project. Therefore the packages for my project were not available in the `~/.elm` folder. This made the LS crash on start with a confusing error.

## Expected Behavior
The language server could give a better error message, providing a possible solution.

## Current Behavior
I get the output in the VSCode console:

```
[Info  - 11:25:04 AM] Loading Elm tree-sitter syntax from ../../../../../.vscode/extensions/elmtooling.elm-ls-vscode-2.2.1/server/out/tree-sitter-elm.wasm
[Info  - 11:25:04 AM] Found 1 elm.json files for workspace /Users/<user>/code/elm-project
[Info  - 11:25:04 AM] Found 1 unique elmWorkspaces for workspace /Users/<user>/code/elm-project
[Info  - 11:25:04 AM] Starting language server for folder: file:///Users/<user>/code/elm-project
[Info  - 11:25:04 AM] Elm version 0.19.1 detected.
[Info  - 11:25:04 AM] Reading elm.json from /Users/<user>/code/elm-project/elm.json
[Warn  - 11:25:04 AM] {"shortMessage":"Command failed with exit code 1: elm make","command":"elm make","escapedCommand":"elm make","exitCode":1,"stdout":"","stderr":"-- NO INPUT --------------------------------------------------------------------\n\nWhat should I make though? I need specific files like:\n\n    elm make src/Main.elm\n    elm make src/This.elm src/That.elm\n\nI recommend reading through https://guide.elm-lang.org for guidance on what to\nactually put in those files!\n\n","failed":true,"timedOut":false,"isCanceled":false,"killed":false}
[Error - 11:25:04 AM] Error parsing files for /Users/<user>/code/elm-project/elm.json:
Error: ENOENT: no such file or directory, open '/Users/<user>/.elm/0.19.1/packages/elm/browser/1.0.2/elm.json'
[Error - 11:25:04 AM] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'getTree' of undefined
[Error - 11:25:04 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'getTree' of undefined
  Code: -32603 
[Error - 11:25:04 AM] Request textDocument/foldingRange failed.
  Message: Request textDocument/foldingRange failed with message: Cannot read property 'getTree' of undefined
  Code: -32603 
[Error - 11:25:04 AM] TypeError: Cannot read property 'getTree' of undefined delayed processing of request
[Error - 11:25:05 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'getTree' of undefined
  Code: -32603 
[Error - 11:25:09 AM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Cannot read property 'getTree' of undefined
  Code: -32603 
[Error - 11:27:13 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'getTree' of undefined
  Code: -32603
```

## Possible Solution
If I delete the `.elm-stuff` folder in my project, and run `elm make` from a terminal inside the project folder, elm re-downloads the dependencies for the project and puts them in the `~/.elm` folder. If I then open VSCode, everything works.

## Steps to Reproduce (for bugs)
1. Rename the `~/.elm` folder to something else (alternatively delete it if you don't with to keep it)
2. Open VS Code in the project folder
3. See the error in the VSCode terminal (Open Console -> go to Output -> select `Elm (elm)` in the dropdown)

## Context
I was coming back to a project I did 6 months ago, and had to spend half an hour or so on debugging before I could get started. That could be nice to avoid, and could prevent newcomers from getting started.

## Your Environment
MacOS 11.6
VSCode 1.61 (ARM build)
Extension elm-tooling/elm-language-client-vscode v2.2.1

**Comment by razzeee** [comment]
@skovmand  We actually run `elm make` on start, so if you had restarted the language server, it should have picked up the newly created folder.

**Comment by skovmand** [comment]
@razzeee Sorry for the late delay! I've been in vacation mode. I'm trying to reproduce the error now by renaming my local `~/.elm` folder to something else, but I no longer get the same error as before. This error is no longer there:

```
Message: Request textDocument/foldingRange failed with message: Cannot read property 'getTree' of undefined 
Code: -32603 
```

Elm still complains that it doesn't know what to make, but I guess that is elms problem and not a language server problem. It is weird though, because that error goes away when I rename the folder back to `~/.elm`.

Writing this, I would also like to thank you for your work on the language server. I works really well, and I'm so happy it exists. It gives a great dev experience!

I think this issue can be closed again. I can't reproduce it anymore.

**Comment by razzeee** [comment]
Thank you!

Yes, it's a bit confusing, that we try to run `elm make` and expect it to error. It still downloads stuff fine. Unfortunatly I've got no idea how to make it nicer
