### ISSUE TITLE
Auto import qualified

### ISSUE THREAD

**Issue by jonathanmoregard** [elm-tooling/elm-language-server#663]
## Expected Behavior
When activating quickfix through the vscode command "editor.action.quickFix",
while the cursor is hovering over a non-imported qualified import (such as `Attribute.none`),
I want to get auto-import suggestions for qualified imports (such as "Import Element.Attribute as Attribute").

## Current Behavior
No qualified import available on "quickFix"

## Possible Solution
1. Use pretty much the same logic as for unqualified imports to get the candidates for import
2. Give options to import with the "as [...]" postfix

## Context
Auto importa are nice, it would be lovely to have it for qualified imports as well

**Comment by adamdicarlo0** [comment]
this looks like a duplicate of #581
