### ISSUE TITLE
Type alias not referenced from types

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#68]
![image(1)](https://user-images.githubusercontent.com/5943908/59679886-582bc780-91d0-11e9-8d74-1aa5e22c939e.png)
`NumberAttributes` has 0 references but it’s part of a type (directly above). Should that count as a reference?

**Comment by buinauskas** [comment]
I would certainly count that as a reference. In this exact case it's quite obvious, but this alias could be anywhere in the document and out of sight.

**Comment by Razzeee** [comment]
I can't actually get this problem to show up, with master. So I have to guess that the person that reported this ran an old version of the server.

**Comment by Razzeee** [comment]
@buinauskas please feel free to reach out via the elm-slack and we can talk about some stuff either private or in `#elm-language-server`

**Comment by Razzeee** [comment]
Pushed an update to vscode, this should be fixed by that release.
