### ISSUE TITLE
Progress specification

### ISSUE THREAD

**Issue by Massolari** [elm-tooling/elm-language-server#686]
There is [this plugin](https://github.com/j-hui/fidget.nvim) I'm trying to use in Neovim that displays when the language-server is indexing files.
It works with a variety of language servers, like tsserver, rust analyzer, null-ls, haskell, and some others, but it does not with elm-language-server.
In the README it says that the language server needs to implement the [progress specification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#progress)

## Expected Behavior
When the language server is indexing files, it should appear in the editor, like:

![image](https://github.com/j-hui/fidget.nvim/raw/media/gifs/fidget-demo-rust-analyzer.gif?raw=true)

## Current Behavior
Nothing shows up

## Possible Solution
Check if we implement this specification and if we do, investigate why the plugin doesn't work

## Steps to Reproduce (for bugs)

1. Install the plugin
2. Open an Elm file

## Context
In big projects, elm-language-servers takes a while to index all the files, so, it'd be nice if we have some indication of the progress

## Your Environment

* Version used: 2.4.1
* Editor used: Neovim 0.6.1
* Environment name and version (e.g. node.js 5.4): Node v17.7.1
* Operating System and version: MacOS 12.3

**Comment by IzumiSy** [comment]
For vim-lsp, I opened a PR that approaches this issue.

https://github.com/prabirshrestha/vim-lsp/pull/1335

**Comment by razzeee** [comment]
Server side this has been implemented since the initial release I think. So this problem is likely client side.
