### ISSUE TITLE
Confusion with paths detected by elm-review (windows OS)

### ISSUE THREAD

**Issue by chemacortes** [elm-tooling/elm-language-server#693]
With windows OS, messages from elm-review are not displayed into the editor, only messages from the elm LSP. With linux, all works fine.

## Expected Behavior

With windows, elm-review seems not working with Visual Code and Elm extension.

Messages from LSP and elm-review are listed in the problems pane, but only messages from LSP are displayed into the code editor. Messages from elm-review are missing.

## Current Behavior

I put in `src/Main.elm` an unused import:

```elm
import Html exposing (Html)
```

In the problems pane, I saw messages from LSP and elm-review:

LSP:
```json
[{
	"resource": "/C:/Users/jmcortesa/temp/test-elmreview/src/Main.elm",
	"owner": "Elm",
	"severity": 4,
	"message": "Unused imported type `Html`",
	"source": "ElmLS",
	"startLineNumber": 4,
	"startColumn": 23,
	"endLineNumber": 4,
	"endColumn": 27,
	"tags": [
		1
	]
}]
```

elm-review:
```json
[{
	"resource": "\\Users\\jmcortesa\\temp\\test-elmreview/src\\Main.elm",
	"owner": "Elm",
	"severity": 4,
	"message": "Imported type `Html` is not used",
	"source": "elm-review",
	"startLineNumber": 4,
	"startColumn": 23,
	"endLineNumber": 4,
	"endColumn": 27,
	"tags": [
		1
	]
}]
```

If in the problems pane, I click in the message from elm-review, I got an error message:

```
Unable to open 'Main.elm': Unable to resolve resource c:%5CUsers%5Cjmcortesa%5Ctemp%5Ctest-elmreview/src%5CMain.elm.
```

Something wrong is happening with the path.

## Possible Solution

LSP and elm-review are using distint schemas for the path. Perhaps, vscode has facilities for homogenizing the use of routes.

## Your Environment

* Visual Code: 1.66.2 (user setup)
* Elm: 0.19.1
* Elm-review: 2.7.2
* Node: 14.19.1
* Operating System and version: Windows 10 Pro

**Comment by razzeee** [comment]
Would you be able to build https://github.com/elm-tooling/elm-language-server/pull/694 and test it?

Basically do https://github.com/elm-tooling/elm-language-client-vscode#contributing--debugging and switch the branch of the server repo

**Comment by chemacortes** [comment]
Sorry, but this is my first time debugging with vscode extensions.

I have not success with it. I paste the same message with elm-review as before:

```
[{
	"resource": "/jmcortesa/temp/test-elmreview/src/Main.elm",
	"owner": "Elm",
	"severity": 4,
	"message": "Imported type `Html` is not used",
	"source": "elm-review",
	"startLineNumber": 4,
	"startColumn": 23,
	"endLineNumber": 4,
	"endColumn": 27,
	"tags": [
		1
	]
}]
```

As you can see, the resource path is missing the prefix `/C:/Users` as do LSP:

```
[{
	"resource": "/c:/Users/jmcortesa/temp/test-elmreview/src/Main.elm",
	"owner": "Elm",
	"severity": 4,
	"message": "Unused imported type `Html`",
	"source": "ElmLS",
	"startLineNumber": 4,
	"startColumn": 23,
	"endLineNumber": 4,
	"endColumn": 27,
	"tags": [
		1
	]
}]
```

**Comment by razzeee** [comment]
Can you check if `elm-review --debug --report=json` has the same problem?

**Comment by razzeee** [comment]
Well, we seem to be combining it with the workspace root path https://github.com/elm-tooling/elm-language-server/blob/main/src/providers/diagnostics/elmReviewDiagnostics.ts#L170

So I guess that's for some reason not correct? Still it uses that path before to check if the ReviewConfig.elm even exists :/

**Comment by chemacortes** [comment]
I understand the problem. `workspaceRootPath` is a `URI` like `file:///c%3A/Users/jmcortesa/temp/test-elmreview`. When it is converted into a string with the property `.fsPath` you get `c:/Users/jmcortesa/temp/test-elmreview`. That's right, but this string cannot be parse again into a uri because it take 'c:'  as part of a protocol. Only `.toString()` method guarantees that the string can be parseable again into an uri as the original.

The fix is to keep `workspaceRootPath` as URI, use `Utils.joinPath` instead of `path.join`, and convert into strings with `.fsPath` or `.toString()` on demand:

```
--- a/src/providers/diagnostics/elmReviewDiagnostics.ts
+++ b/src/providers/diagnostics/elmReviewDiagnostics.ts
@@ -100,7 +99,7 @@ export class ElmReviewDiagnostics {
     const workspaceRootPath = this.elmWorkspaceMatcher
       .getProgramFor(filePath)
       .getRootPath();
-    return await this.checkForErrors(workspaceRootPath.fsPath);
+    return await this.checkForErrors(workspaceRootPath);
   };

   private hasType(error: any): error is IElmReviewError {
@@ -108,7 +107,7 @@ export class ElmReviewDiagnostics {
   }

   private async checkForErrors(
-    workspaceRootPath: string,
+    workspaceRootPath: URI,
   ): Promise<Map<string, IElmReviewDiagnostic[]>> {
     const settings = await this.settings.getClientSettings();
     const fileErrors = new Map<string, IElmReviewDiagnostic[]>();       
@@ -116,7 +115,8 @@ export class ElmReviewDiagnostics {
     if (
       settings.elmReviewDiagnostics === "off" ||
       !existsSync(
-        path.join(workspaceRootPath, "review", "src", "ReviewConfig.elm"),
+        Utils.joinPath(workspaceRootPath, "review", "src", "ReviewConfig.elm")
+          .fsPath,
       )
     ) {
       return fileErrors;
@@ -142,7 +142,7 @@ export class ElmReviewDiagnostics {
         elmReviewCommand,
         "elm-review",
         options,
-        workspaceRootPath,
+        workspaceRootPath.fsPath,
         this.connection,
       );
       return fileErrors;
@@ -166,10 +166,7 @@ export class ElmReviewDiagnostics {
           errorObject.type === "review-errors"
         ) {
           errorObject.errors.forEach(({ path, errors }: IFileError) => {
-            const uri = Utils.joinPath(
-              URI.parse(workspaceRootPath),
-              path,
-            ).fsPath;
+            const uri = Utils.joinPath(workspaceRootPath, path).toString();

             fileErrors.set(
               uri,

```

That works now with my windows installation.

**Comment by razzeee** [comment]
Thank you, seems to work fine like that on linux too.
