### ISSUE TITLE
coc.nvim fails to start language server with error about "unregistered dependency token ElmWorkspaces"

### ISSUE THREAD

**Issue by patreeceeo** [elm-tooling/elm-language-server#695]
I've used coc.nvim for a while with a variety of languages and I'm trying to get started with Elm. I've installed this language server and its dependencies in my local node_modules directory and configured coc.nvim like so:

```json
{
  ...
    "elmLS": {
      "command": "./assets/node_modules/.bin/elm-language-server",
      "filetypes": ["elm"],
      "rootPatterns": ["elm.json"],
      "elmPath": "./assets/node_modules/.bin/elm",
      "elmReviewPath": "./assets/node_modules/.bin/elm-review",
      "elmFormatPath": "./assets/node_modules/.bin/elm-format",
      "elmTestPath": "./assets/node_modules/.bin/elm-test",
    },
   ...
}
```

## Expected Behavior
coc.nvim starts the language server and I can write Elm code using neovim and code completion, syntax checking etc.

## Current Behavior
When I start coc.nvim it gives me this message:
```
Server languageserver.elmLS failed to start: Pm [Error]: Request
initialize failed with message: Attempted to resolve unregistered dependency token: "ElmWorkspaces"
at su (/home/patrick/dotfiles/.config/nvim/plugged/coc.nvim/build/index.js:38:224)
lp (/home/patrick/dotfiles/.config/nvim/plugged/coc.nvim/build/index.js:37:11261)
at
at Immediate. <anonymous> (/home/patrick/dotfiles/.config/nvim/plugged/coc.nvim/build/index.js:37:11111)
at process Immediate (node: internal/timers:464:21) {
code: -32603,
data: undefined
```

## Possible Solution
Not sure I can help here just yet. Was looking through the source of both coc.nvim and elm-language-server and it's hard to tell where this error is even coming from. I suspect it's from a dependency of elm-language-server.

## Steps to Reproduce
1. Install elm-language-server and its dependencies
2. Configure coc.nvim
3. Edit a Elm file

## Your Environment
* Version used: 1.6.0
* Editor used: neovim 0.4.3
* Environment name and version: Node 16.3.0
* Operating System and version: Ubuntu 20.04

**Comment by patreeceeo** [comment]
Just tried installing everything globally (` -g @elm-tooling/elm-language-server elm-format elm-test elm-review`) and changing my coc.nvim config to:

```json
{
  ...
    "elmLS": {
      "command": "elm-language-server",
      "filetypes": ["elm"],
      "rootPatterns": ["elm.json"]
    },
  ...
```

But same result.

**Comment by patreeceeo** [comment]
Same result with the latest release of neovim, 0.7.0

**Comment by razzeee** [comment]
Seems like the dependency injection fails for some reason. Probably because vim fails to find a workspace?

**Comment by patreeceeo** [comment]
That gives me an idea... Yup, it must have been because I hadn't created an elm.json file yet. Now that that exists in an ancestor directory to the file I'm editing the LS starts up successfully. So, user error, though in the friendly spirit of Elm perhaps the error message should be more helpful?

**Comment by razzeee** [comment]
Hrm, is there something else that's weird? I can't reproduce this in vscode. I took a project and just deleted the `elm.json` and reloaded the workspace.

**Comment by AndydeCleyre** [comment]
I get the same problem with LSP-elm in sublime text. I'm just going through elm tutorials for the first time so I don't have any idea what `ElmWorkspaces` is yet.

**Comment by razzeee** [comment]
That's an internal thing to the language server, you won't know that from learning elm

**Comment by mattiasdrp** [comment]
I have the same issue in emacs:

```
❯ elm-language-server --version
2.6.0
❯ node -v
v16.19.0
```

I created an empty project with `elm init` and opened `src/Main.elm` and got the exact same message and the lsp-log error displayed 

```
No elm.json found. Please run 'elm init' in your main directory.
No elm.json found
```

But

```
❯ tree
.
├── elm.json
└── src
    └── Main.elm
```

**Comment by tillydray** [comment]
I'm also having this same issue in emacs.

## Your Environment

- Version used: 1.12.0
- Editor used: Doom Emacs GNU Emacs 28.2 (build 1, aarch64-apple-darwin22.2.0, Carbon - Version 169 AppKit 2299.3) of 2023-01-22
- Environment name and version: Node v16.19.0
- Operating System and version: macOS 13.1

**Comment by mattiasdrp** [comment]
@tillydray As you can see from https://github.com/emacs-lsp/lsp-mode/issues/3936, my issue is that projectile was not setting the project root properly. I created a PR for Projectile: https://github.com/bbatsov/projectile/pull/1819.
Do you have the same root issue? In this case, try to set it manually to not include `src`.

@razzeee the issue doesn't come from the elm language server, sorry for the disturbance 😉

**Comment by tillydray** [comment]
Thank you! Works after I remove the workspace folder and re-add the project root instead of project_root/src which is what projectile chose automatically
