### ISSUE TITLE
Repetetive types

### ISSUE THREAD

**Issue by buinauskas** [elm-tooling/elm-language-server#70]
There's quite a lot of repetitive types that are inlined within generic types, such as arrays.

For instance:
``` typescript
private findElmFilesInFolders(
  elmFolders: Array<{ path: string; writable: boolean }>,
): Array<{ path: string; writable: boolean }> {
  let elmFilePaths: Array<{ path: string; writable: boolean }> = [];
  for (const element of elmFolders) {
    elmFilePaths = elmFilePaths.concat(this.findElmFilesInFolder(element));
  }
  return elmFilePaths;
}

private findElmFilesInFolder(element: {
  path: string;
  writable: boolean;
}): Array<{ path: string; writable: boolean }> {
  return glob
    .sync(`${element.path}/**/*.elm`)
    .map(a => ({ path: a, writable: element.writable }));
}
```

The following type appears 4 times in snippet above.
``` typescript
{ path: string; writable: boolean }
```

This could be extracted into a separate interface. This will improve readability and reduce code duplication.

**Comment by Razzeee** [comment]
There are a bunch of these, as I did not take the time to find names. Cause naming is hard :)
Please feel free to improve them, but I'm closing this issue due to the open endedness of this task.
