### ISSUE TITLE
Completion useage

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#75]
At the moment we add completions for sub types/functions to a list, e.g. `Html.div`
But that doesn't really play nice with the spec, as you might end up typing `Html.` then auto complete. Under certain prerequisites this leads to `Html.Html.div` which is not what we want.

Typescript or C# would first let you choose `Html` then would detect that the completion your expanding on is in the Html package and only send the correct functions.

**Comment by Razzeee** [comment]
On the other hand, I really like that it shows you all prefixed versions, as that makes you more aware. Should be good for beginners too.

**Comment by Razzeee** [comment]
I don't think we should act on this.

**Comment by tj** [comment]
FWIW I hit this pretty often, if you forget a function name I'd almost always type `String.*` first and get the double `String.String.fromInt`

**Comment by Razzeee** [comment]
Ok, was more talking about having both to select is fine, it should complete without adding anything obviously. 
Will investigate that again.

**Comment by Razzeee** [comment]
I actually think this might be an vscode bug

**Comment by bigardone** [comment]
Same happening to me using nvim + coc

**Comment by tad-lispy** [comment]
Same here - nvim + coc. I type `Maybe.with` start autocompletion, chose `withDefault` from the list and end up with `Maybe.Maybe.withDefault`.

**Comment by Augustin82** [comment]
Experiencing the same with nvim + CoC.
I do like that it shows you other modules even with the prefix; although it might be counterintuitive, it does help if you're targeting the wrong module (like, you think it's in `Element.Border` but it's in `Element.Font` or something); maybe prioritizing results (first by module, then by all matches) could be nice

**Comment by juanedi** [comment]
I was getting this on emacs pretty much every time I used autocomplete :-(
