### ISSUE TITLE
hoverProvider

### ISSUE THREAD

**Issue by Razzeee** [elm-tooling/elm-language-server#8]
Show hovers for 

- [x] Functions
- [x] Types
- [x] Type alias
- [x] Modules

Even from other files or when they're prefixed/aliased

This is pretty similiar to the definitionProvider, so they could likely share big parts of their code. https://github.com/Razzeee/elm-language-server/issues/9

**Comment by Razzeee** [comment]
Should work as specified here. Ready for testing.

**Comment by bengolds** [comment]
I'm only getting hover results for functions and local parameters -- not for Types, Type Aliases, or Modules. I'm not seeing any error messages, either. Do you see the same issue?

**Comment by Razzeee** [comment]
All the ones you mention need to have docs to show any hovers. So try on something from elm itself ideally. Works for me with vscode.
