### ISSUE TITLE
Bug: Reference count is 0 for variable in let with type annotation.

### ISSUE THREAD

**Issue by anagrius** [elm-tooling/elm-language-server#817]
Reference counts are surprising.

Here is an example:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/157210/199344066-4d0661c9-8173-43e5-81b2-ea1038fbee5c.png">

In this example there are 5 locations where references are displayed:

*module*
The `module` declaration says 1 reference, even though the module is never used.
This is because the definition of the module counts as a reference - I would argue that this is never useful, in any of the example below as well.

*p top-level*
The top-level constant `p` is never used, but the reference says `3`:

1. The definition
2. The type annotation
3. The name in the exposing list

(1) and (2) are not useful since the user is already looking at / interacting with them. They arguably add noise to the list of reference that the user has to mentally filter out when looking up references.

(3) you could argue that the name in the exposing list is a reference, but it is not generally useful, especially since you have `exposed` hint next to it. 

*x*
The top-level constant `x` is never used, but the reference says `1`.

Expected: `0` for reasons already stated.

*y*
The constant `y` in the let-in expression has a type annotation. It is used once, but there is a bug causing this to be `0` always when an annotation is present.

*z*
The constant `z` is used once but says (2) because of the self-reference. Unlike `y` this does not have a type annotation and does not always say `0`.

# Expected

`module Foo = 0`
`p = 0`
`x = 0`
`y = 1`
`z = 1`

**Comment by anagrius** [comment]
Having looked at the code, it seems `References.find` is used for renaming a symbol. For that usage all of the places the symbol occurs is of course needed since they should all be replaced.

But for logical "usages" in the code-base, we don't really want ALL the places a symbol appears, just the places where it is use in an expression.

Maybe `References.find` could take an additional parameter to only include usages in expressions.

**Comment by razzeee** [comment]
I guess it's what https://github.com/elm-tooling/elm-language-server/pull/691 tried to fix?
