### ISSUE TITLE
Why is "documentRangeFormattingProvider" true?

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#83]
format ranges isn't something that is supported by `elm-format`. Why is the capability `true`?

https://github.com/elm-tooling/elm-language-server/blob/1e848edab4862508fea18bb156126eacc40b60e1/src/capabilityCalculator.ts#L31

**Comment by Razzeee** [comment]
Probably a leftover of some tests. While I think it's possible to enable this feature it's probably not worth the hassle.

**Comment by andys8** [comment]
Same. I wouldn't use the feature.
