### ISSUE TITLE
Should diagnostics be executed on dependencies?

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#87]
When jumping into a definition of a third party dependency (one of the best features!), diagnostics are also executed. I'm not sure if this makes sense.

![image](https://user-images.githubusercontent.com/13085980/59966234-8d5e4f80-9519-11e9-8d4f-4d7097b7bdb5.png)

**Comment by Razzeee** [comment]
No, we should not do this.

**Comment by Razzeee** [comment]
Should be fixed by https://github.com/elm-tooling/elm-language-server/commit/bf49c26463bd991ecbd42ab64f1961725e47dcc9
