### ISSUE TITLE
Heavy CPU load when typing

### ISSUE THREAD

**Issue by andys8** [elm-tooling/elm-language-server#89]
I'm in Insert Mode, typing and removing characters, not even leaving insert mode, and `elm-test` is fired multiple times.

This is in a test file. There is increased CPU also in source files, but not as bad. This could be because `elm` is better performing than `elm-test` or there is another difference.

![image](https://user-images.githubusercontent.com/13085980/59976016-327f3380-95bf-11e9-8302-13049a5ea6a1.png)

### Config

```
{
  "diagnostic.refreshAfterSave": true,
  "coc.preferences.formatOnSaveFiletypes": ["elm"],
  "coc.preferences.snippets.enable": false,
  "suggest.minTriggerInputLength": 3,
  "suggest.maxCompleteItemCount": 5,
  "diagnostic.refreshOnInsertMode": false,
  "languageserver": {
    "elmLS": {
      "command": "elm-language-server",
      "args": ["--stdio"],
      "filetypes": ["elm"],
      "rootPatterns": ["elm.json"],
      "trace.server": "verbose",
      "initializationOptions": {
        "runtime": "node",
        "elmPath": "elm",
        "elmFormatPath": "elm-format",
        "elmTestPath": "elm-test"
      }
    }
  }
}
```

LSP 1.0.2 (published), Vim / Coc

### Logs (partial)
```
[...]

[Trace - 2:04:02 PM] Received request 'workspace/configuration - (36)'.
Params: {
    "items": [
        {
            "section": "elmLS"
        }
    ]
}


[Trace - 2:04:02 PM] Sending response 'workspace/configuration - (36)'. Processing request took 0ms
Result: [
    {}
]


[Trace - 2:04:02 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Received new elm-analyse report with 0 messages"
}


Received new elm-analyse report with 0 messages
[Trace - 2:04:02 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/as/Dev/repository/vim-emulation/tests/MainTest.elm",
    "diagnostics": []
}


[Trace - 2:04:02 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/as/Dev/repository/vim-emulation/tests/MainTest.elm",
    "diagnostics": []
}


[Trace - 2:04:02 PM] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "Changed text document, going to parse it. file:///home/as/Dev/repository/vim-emulation/tests/MainTest.elm"
}


[Info  - 2:04:02 PM] Changed text document, going to parse it. file:///home/as/Dev/repository/vim-emulation/tests/MainTest.elm
[Trace - 2:04:02 PM] Received request 'workspace/configuration - (37)'.
Params: {
    "items": [
        {
            "section": "elmLS"
        }
    ]
}


[Trace - 2:04:02 PM] Sending response 'workspace/configuration - (37)'. Processing request took 0ms
Result: [
    {}
]


[Trace - 2:04:02 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Received new elm-analyse report with 0 messages"
}


Received new elm-analyse report with 0 messages
[Trace - 2:04:02 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///home/as/Dev/repository/vim-emulation/tests/MainTest.elm",
    "diagnostics": []
}


[Trace - 2:04:02 PM] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "Changed text document, going to parse it. file:///home/as/Dev/repository/vim-emulation/tests/MainTest.elm"
}


[Info  - 2:04:02 PM] Changed text document, going to parse it. file:///home/as/Dev/repository/vim-emulation/tests/MainTest.elm
[Trace - 2:04:02 PM] Received request 'workspace/configuration - (38)'.
Params: {
    "items": [
        {
            "section": "elmLS"
        }
    ]
}


[Trace - 2:04:02 PM] Sending response 'workspace/configuration - (38)'. Processing request took 0ms
Result: [
    {}
]
```

### Related?

https://github.com/neoclide/coc.nvim/issues/403

**Comment by Razzeee** [comment]
Interesting, as elm-test should only run on save.

Anyway we have been talking about debouncing or at least ignore all but the lastest request. Likely via rxjs.

**Comment by andys8** [comment]
> Interesting, as elm-test should only run on save.

`elm-test` is triggered when diagnostics are. And there is a listener on change. It might be that those events still occur.

```ts
    this.events.on("open", this.getDiagnostics);
    this.events.on("change", this.getDiagnostics);
    this.events.on("save", this.getDiagnostics);
    this.elmAnalyseDiagnostics.on("new-diagnostics", this.newElmAnalyseDiagnostics);
```

**Comment by Razzeee** [comment]
I don't have time to look at the code at the minute, but I'm pretty sure elm-test only runs on save. Or we already changed elm-make to run on change without me knowing :D

**Comment by Razzeee** [comment]
I checked, and test runs on the same events as make. Anyway, it was kinda buggy and not doing anything useful. Might have even caused the process to not terminate? I don't know.

**Comment by andys8** [comment]
Is this commit Relevant? https://github.com/elm-tooling/elm-language-server/commit/8bd883020628511c4eea8c5ddc689018d3bfc795

Do you need more information regarding this issue or can you reproduce it quite well?

**Comment by Razzeee** [comment]
Yes, that's relevant can you see if the behavior improved?

**Comment by andys8** [comment]
I stopped using trunk since it wasn't working anymore. But going to try it now.

**Comment by andys8** [comment]
Okay.

## General

Sources: elm-make and elm-analyse are working
Tests: elm-make is **not working**, but **elm-analyse** is.

## High CPU (this issue)

Seems like it is still existing if I trigger a lot of changes.

**Comment by Razzeee** [comment]
you need failing tests to see that tests are working, otherwise you get nothing, correct?

**Comment by andys8** [comment]
Are we actually running `tests`?? Because it's about syntax parsing and a missing dependency that is added by elm-test.

**Comment by andys8** [comment]
Demo where changing text frequently trigger's lots of `elm-test` instances.

![vokoscreen-2019-06-26_22-23-46](https://user-images.githubusercontent.com/13085980/60212609-f1f31480-9861-11e9-9335-5203ed823a03.gif)

**Comment by andys8** [comment]
Oooookay...

I think we're doing `elm-test --report json tests/MainTest.elm`, which is _running tests_.
But we should run `elm-test make --report json tests/MainTest.elm`, which is _compiling tests_.

**Comment by andys8** [comment]
I see you actually implemented reading tests results. But I think this is totally different feature. Executing the tests on change (this is happening), can't work. Also running test suites takes time and it has do be handled differently.

For linting (is the test compiling?), we can use kinda the same arguments and get the same result structure.

**Comment by andys8** [comment]
I pushed changes, that reverted the commit and use `elm-test` as compiler. Have a look and feel free to add changes.

**Comment by andys8** [comment]
And regarding this issue: We're still triggering execution a lot and on change. `elm-test make` is just faster than `elm-test`.

**Comment by andys8** [comment]
I want diagnostics and any update to happen on save. If I comment this line out, everything works absolutely gorgeous. 
 
https://github.com/elm-tooling/elm-language-server/blob/fc6e16419144f14f17521c0598d36e73fa971daf/src/providers/diagnostics/diagnosticsProvider.ts#L62

No missing diagnostics updates, no CPU peaks, etc. Guess adding the configuration param makes sense again (https://github.com/elm-tooling/elm-language-server/pull/67).

**Comment by Razzeee** [comment]
That change seems to be caused by an oversight in refactoring. I pushed something to master to fix that.

**Comment by andys8** [comment]
Cool. The updated part looks like it is skipping updates when "on change". But why is it still sending not-updated diagnostics every time? Is it necessary or can it also be skipped?

https://github.com/elm-tooling/elm-language-server/blob/3ed46440eb65670593eddf08580a0946058832ca/src/providers/diagnostics/diagnosticsProvider.ts#L115-L131

**Comment by Razzeee** [comment]
well elm analyse diagnostics are still changing on typing, so those should update. We can/should probably diff them, if we can and only send necessary updates.

**Comment by andys8** [comment]
Thanks.

https://github.com/elm-tooling/elm-language-server/commit/3ed46440eb65670593eddf08580a0946058832ca is not running `elm make` on change.

https://github.com/elm-tooling/elm-language-server/commit/4de7937f986c8ea597ceab5472f33e4c361c4dd7#diff-bb40c3cb33fc03e25e56b7e9cd43eec6R67 is adding `make` and parsing the `elm-test` compile results correctly.

Therefore we can close the issue.
