### ISSUE TITLE
Feature Request: publishing in travis.

### ISSUE THREAD

**Issue by cappyzawa** [elm-tooling/elm-language-server#90]
Hi.
I want to latest elm-language-server.
But `@elm-tooling/elm-language-server` is not published in ci.

How is this package published to npm?

I propose ci flow as follows.
the master branch is updated:
* `npm version patch`
* `npm run compile`
* `git push origin <new tag>` and `npm publish`

I want to realize myself, but I do not because I don't know token for publishing this package and deploy-key for pushing this repository to github.

**Comment by Razzeee** [comment]
I don't think we should push to npm with every commit, doesn't seem like a good idea.
We can create tags and have those run the CI. Have the credentials in a secure string like I do here https://github.com/Razzeee/tree-sitter-elm/blob/master/.travis.yml#L33

But at the moment, I don't really see the value, as we want to release working versions to npm.

**Comment by cappyzawa** [comment]
OK. I see:+1:

You want to publish stable version to npm, don't you?

Great!
Thanks for quick reply:ok_woman:

**Comment by Razzeee** [comment]
Yes, that's the plan, if you want more experimental builds, feel free to grab the git and use `npm link`
