### ISSUE TITLE
ALE ignores going to next error

### ISSUE THREAD

**Issue by romariolopezc** [elm-tooling/elm-language-server#93]
Adding this: `let g:ale_linters_ignore = { 'elm': ['make'] }` to vim config file doesn't let ALE go to the next error with `:ALENext -error` (or keybinding).

It detects correctly the error linting it with `>>` but doesn't goes to it.

It correctly cycles through the warnings

Removing it allows to cycle between errors + warnings

This setting is advised in:
https://github.com/antew/vim-elm-language-server#configuration

**Comment by andys8** [comment]
These worked for me with ale

```
nnoremap <silent> <leader>a :ALENext -wrap<CR>
nnoremap <silent> <leader>A :ALENext -wrap -error<CR>
```

So either `elm-language-server` changed something or it's the missing wrap regarding to your cursor position.

**Comment by Razzeee** [comment]
Closing due to missing feedback
