### ISSUE TITLE
Type inference broken when there are comments between arguments on type definition

### ISSUE THREAD

**Issue by jyrodrigues** [elm-tooling/elm-language-server#945]
I'm not 100% sure this issue belongs here (vs. `elm-language-client-vscode`) but I think it does. Let me know if I should move it there.

SSCCE:
```elm
type MyType
    = MyType
        -- First comment
        -- Second comment
        -- Third comment
        Int


someFunction : MyType -> Bool
someFunction mytype =
    case mytype of
        MyType _ ->
            True
```
<img width="472" alt="image" src="https://user-images.githubusercontent.com/4342234/232826772-f9594f5e-0aeb-4f3d-b22c-fd7f1f34339d.png">

## Expected Behavior
No errors.

## Current Behavior
The following error treats the variant `MyType` as taking *4* arguments when it actually takes only one (and has 3 comments):
```
This `case` does not have branches for all possibilities.
Missing possibilities include:
  MyType _ _ _ _
```

## Possible Solution
Once the comments are deleted or moved up the error disappears. It seems that comments are tokenized and somewhere interpreted as type arguments.

The weirdest thing though is that if I check the VSCode plugin box `Only Update Diagnostics On Save
` this error disappears.

I've also seen the error disappear when I save the file but sometimes it does not.

## Steps to Reproduce (for bugs)

1. Copy the code to an Elm file;
2. Edit the file and see the error.

## Your Environment

* Version used: 2.6.0
* Editor used: VSCode
* Environment name and version (e.g. node.js 5.4): Node 19.8.1
* Operating System and version: MacOS 13.2.1

**Comment by jmbockhorst** [comment]
Thanks for reporting. I was able to fix it pretty easily.

**Comment by jyrodrigues** [comment]
Thank you @jmbockhorst!!
