### ISSUE TITLE
Completion of record fields

### ISSUE THREAD

**Issue by tj** [elm-tooling/elm-language-server#96]
First of all thanks this is awesome! I just started learning Elm this week and it's exciting to see there's some nicer tooling. I'm sure you already know these but I thought I would open an issue.

<img width="488" alt="Screen Shot 2019-06-28 at 12 33 08 PM" src="https://user-images.githubusercontent.com/25254/60339720-74ceb900-99a1-11e9-8e26-7e121c5cafca.png">

**Comment by Razzeee** [comment]
Can you please split this into two issues?

**Comment by jmbockhorst** [comment]
@Razzeee This should be fixed in #221.
