### ISSUE TITLE
Completion of variables

### ISSUE THREAD

**Issue by tj** [elm-tooling/elm-language-server#97]
I can't quite nail down when variables do or do not complete properly, but here are a few scenarios:

<img width="532" alt="Screen Shot 2019-06-28 at 12 38 19 PM" src="https://user-images.githubusercontent.com/25254/60339780-a6478480-99a1-11e9-8106-5c32efc6fb44.png">

<img width="493" alt="Screen Shot 2019-06-28 at 1 27 14 PM" src="https://user-images.githubusercontent.com/25254/60342095-75b71900-99a8-11e9-911d-b9fdfbc0d921.png">

**Comment by Razzeee** [comment]
functions from the let scope should now show up in most cases, with master

**Comment by Razzeee** [comment]
The other thing you mentioned is what's tracked in https://github.com/elm-tooling/elm-language-server/issues/79

Closing this for now, feel free to reopen it.
