### ISSUE TITLE
Sublime Text Support

### ISSUE THREAD

**Issue by Jayshua** [elm-tooling/elm-language-server#99]
I'm trying this out in Sublime Text with the LSP package. The basics errors and warnings seem to work fine, but nothing else appears to.

Errors
![image](https://user-images.githubusercontent.com/1654103/60388110-7320f600-9a72-11e9-8b44-86de8fa88bd2.png)

Warnings
![image](https://user-images.githubusercontent.com/1654103/60388117-859b2f80-9a72-11e9-8994-8a2a8ec696ac.png)

Hover over functions fails to show information. Definition and References don't work either.
![image](https://user-images.githubusercontent.com/1654103/60388120-9c418680-9a72-11e9-9d5d-4ff6073b9f9f.png)

Try bringing up some actions to perform
![image](https://user-images.githubusercontent.com/1654103/60388300-ee83a700-9a74-11e9-9504-bda0d62de69e.png)

No picture, but signatureHelp doesn't do anything either

```
LSP:  --> textDocument/signatureHelp
LSP:      None
```

This error appears many, many times in the log, mainly on textDocument/didChange message. The definition requests simply return None though, no errors.

```
LSP: <--  window/logMessage
LSP:      {'type': 3, 'message': 'Changed text document, going to parse it. file:///C:/Users/Jayshua/Projects/elm-lang-server-test/src/Main.elm'}
server: Changed text document, going to parse it. file:///C:/Users/Jayshua/Projects/elm-lang-server-test/src/Main.elm
LSP:  --> textDocument/didChange
server: (node:15048) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'file:///C:/Users/Jayshua/Projects/elm-lang-server-test/src/Main.elm'
server: at Object.openSync (fs.js:451:3)
server: at Object.readFileSync (fs.js:351:35)
server: at ASTProvider.<anonymous> (C:\Users\Jayshua\AppData\Roaming\npm\node_modules\@elm-tooling\elm-language-server\out\providers\astProvider.js:24:42)
server: at Generator.next (<anonymous>)
server: at C:\Users\Jayshua\AppData\Roaming\npm\node_modules\@elm-tooling\elm-language-server\out\providers\astProvider.js:7:71
server: at new Promise (<anonymous>)
server: at __awaiter (C:\Users\Jayshua\AppData\Roaming\npm\node_modules\@elm-tooling\elm-language-server\out\providers\astProvider.js:3:12)
server: at DocumentEvents.ASTProvider.handleChangeTextDocument (C:\Users\Jayshua\AppData\Roaming\npm\node_modules\@elm-tooling\elm-language-server\out\providers\astProvider.js:19:53)
server: at DocumentEvents.emit (events.js:187:15)
server: at DocumentEvents.connection.onDidChangeTextDocument.event (C:\Users\Jayshua\AppData\Roaming\npm\node_modules\@elm-tooling\elm-language-server\out\util\documentEvents.js:7:58)
server: (node:15048) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
```

Here's the configuration I used to get it working:
```
	"clients":
	{
		"elm_language_server":
		{
			"command": ["elm-language-server", "--stdio"],
			"enabled": true,
			"initializationOptions":
			{
				"elmFormatPath": "elm-format",
				"elmPath": "elm",
				"elmTestPath": "elm-test",
				"runtime": "node"
			},
			"languageId": "elm",
			"scopes": ["source.elm"],
			"syntaxes": ["Packages/Elm Language Support/Syntaxes/Elm.sublime-syntax"]
		}
	}
```

I'm very unfamiliar with language server development, but if there's any other information you need or things you want me to try I'm happy to.

**Comment by Razzeee** [comment]
Your using https://github.com/tomv564/LSP in order to get sublime to run or something else?

signatureHelp should not be enabled, as the server is not saying that it can support this. So I'm not sure if that's an error in the LSP client implementation?

Can you confirm, that `C:/Users/Jayshua/Projects/elm-lang-server-test/src/Main.elm` exists?

**Comment by Razzeee** [comment]
Were you able to make any progress?

**Comment by Jayshua** [comment]
Oops. Notification of your first response got buried in my inbox :/.

Yes, Main.elm does exist. Also, yes that's the LSP client I'm using. Don't know about it being an error in the client, like I said I don't know much about the protocol. I could maybe ask the implementor.

**Comment by Razzeee** [comment]
Did you deactivate the "old" sublime plugin?

We should probably build a package for sublime that just detects if it's an elm file and supplies syntax highlighting.

See https://github.com/tomv564/LSP/issues/613 for reference.

**Comment by Jayshua** [comment]
I had most of the "extra" features of that package disabled in its config file. I just tried removing Elm Language Support altogether and using only the Elm.sublime-syntax file by dropping it into my Packages/User folder. Same results as before. Here's the LSP log from startup to a codeActions request and a rename request: https://pastebin.com/6MAKJFqE I'm thinking this is a problem with Sublime LSP maybe? I'm just not familiar enough with what this back-and-forth should look like. Should there be any code actions returned when asking on a function name, and should a rename request work?

**Comment by Razzeee** [comment]
Code Actions might be returned, depending on where in a file you are. Rename should work with function names for e.g.

You've seen this page? https://lsp.readthedocs.io/en/latest/troubleshooting/

Did you enable `log_stderr`?

**Comment by Razzeee** [comment]
It's funny that the log message isn't handled an just get's logged via error logging it seems. We should definatly talk with the plugin authors.

**Comment by Jayshua** [comment]
Yes, log_stderr is on. I assumed that was what was causing the `server: (node:15048) UnhandledPromiseRejectionWarn...` logs in the first message?

**Comment by Razzeee** [comment]
Hrm https://github.com/tomv564/LSP/commit/80196bee77f82c40bee943e9eabd2911be15fc6f

`log_stderr` probably wasn't causing it, but might be the reason why it surfaced. That one might just be a bug of our server, your trying with the last release right?

**Comment by Jayshua** [comment]
Oh sorry. I said "causing" when I meant "causing to be shown."

elm-language-server: 1.1.1 - That's the latest according to npm.

Not sure the version number of LSP I'm on, but sublime is saying it's the latest whatever version it is.

**Comment by Razzeee** [comment]
It's failing for me even earlier if I try to set it up. Best would probably be to talk with the people over at the LSP implementation.
Either via issue or gitter. https://github.com/tomv564/LSP#getting-help

**Comment by Razzeee** [comment]
Seems like there was an update for the LSP plugin in sublime. I could get it to work now :)

**Comment by Razzeee** [comment]
Sublime support has been documented

https://github.com/elm-tooling/elm-language-server#sublime
https://github.com/elm-tooling/elm-language-server#editor-support

**Comment by JohnKacz** [comment]
So I hate to be a bother but right after you closed this Evan went ahead and removed [Elm Language Support](https://packagecontrol.io/packages/Elm%20Language%20Support) and changed it to [Elm Syntax Highlighting](https://packagecontrol.io/packages/Elm%20Syntax%20Highlighting)

I changed 
```
  "syntaxes":
  [
    "Packages/Elm Language Highlighting/src/elm.sublime-syntax
  ],
```
to 
```
  "syntaxes":
  [
    "Packages/Elm Syntax Highlighting/src/elm.sublime-syntax
  ],
```

Everything seems to be working for me

**Comment by Razzeee** [comment]
I already updated it in the readme due to https://github.com/elm-tooling/elm-language-server/issues/131
Anything else I'm missing?

**Comment by JohnKacz** [comment]
Yes sorry to not be more clear. The package is “Elm Syntax Highlighting” but you have “Elm Language Highlighting” in the settings. And (although it’s less important) you reference the now removed “Elm Language Support” package in the paragraph above the example settings.

**Comment by Razzeee** [comment]
Good catch, hopefully fixed now.
